### ISSUE TITLE
DOC typo in user guide

### ISSUE THREAD

**Issue by a234** [kymatio/kymatio#1016]
The saturation in the figures of [gallery_2d/plot_filters](https://www.kymat.io/gallery_2d/plot_filters.html#sphx-glr-gallery-2d-plot-filters-py) is always 0.8. What represents the complex magnitude is the lightness.

This means that

 `fig.suptitle((r"Wavelets for each scales $j$ and angles $\theta$ used."
              "\nColor saturation and color hue respectively denote complex "
              "magnitude and complex phase."), fontsize=13)`

should be changed into

 `fig.suptitle((r"Wavelets for each scales $j$ and angles $\theta$ used."
              "\nColor lightness and color hue respectively denote complex "
              "magnitude and complex phase."), fontsize=13)`

**Comment by janden** [comment]
Looks like these were replaced by simpler captions as part of a554a2a527ce0a235b18be4a1f0e135e8dc5dc70. Closing.
