### ISSUE TITLE
JTFS kwarg-only arguments

### ISSUE THREAD

**Issue by janden** [kymatio/kymatio#1032]
The way it's written right now, `TimeFrequencyScattering` requires all arguments to be kwargs, as opposed to the regular scattering classes (e.g., `Scattering1D`). For consistency, it would be good to follow the same convention here. Is there some specific reason for forcing kwargs here?

@lostanlen @cyrusvahidi

**Comment by lostanlen** [comment]
The idea behind kwarg-only was mine. The four required arguments are shape, Q, J, and J_fr. It's easy to goof up with the order so i think that being explicit is better here.

I would argue that if anything, it's the positional argument form of Scattering1D which should be deprecated. But  can have it either way. What i don't want is to introduce inscrutable positional arguments in user calls to JTFS

**Comment by janden** [comment]
> It's easy to goof up with the order so i think that being explicit is better here.

Right but going from `J, shape, Q` to `J, J_fr, shape, Q` shouldn't be too much of a hurdle here. It also makes the code more verbose. The user still has the option of specifying the kwargs (as in most APIs) if they want to be explicit. Not sure I want to force this on them.

> I would argue that if anything, it's the positional argument form of Scattering1D which should be deprecated. 

That would be quite a breaking change, so I would advise against that.

**Comment by cyrusvahidi** [comment]
> > It's easy to goof up with the order so i think that being explicit is better here.
> 
> Right but going from `J, shape, Q` to `J, J_fr, shape, Q` shouldn't be too much of a hurdle here. It also makes the code more verbose. The user still has the option of specifying the kwargs (as in most APIs) if they want to be explicit. Not sure I want to force this on them.
> 
> > I would argue that if anything, it's the positional argument form of Scattering1D which should be deprecated.
> 
> That would be quite a breaking change, so I would advise against that.

I am in favour of keeping consistency between JTFS and Scat1D in the arguments and making `Q` and `J_fr` kwargs to minimise confusion

**Comment by janden** [comment]
> I am in favour of keeping consistency between JTFS and Scat1D in the arguments and making `Q` and `J_fr` kwargs to minimise confusion.

I'm not following here. Are you saying that we would only require `Q` and `J_fr` to be kwarg-only by allowing `J` and `shape` to be positional?

> Isn't `shape` the only minimum requirement that we should expect from the user?

I think the argument order was decided with the idea that only `J` would be the only required argument (note that `Q` has a default of one in `Scattering1D`). This would be possible when (if) we implement overlap–add type convolutions which don't require the filter size to be specified in advance.

**Comment by lostanlen** [comment]
> I'm not following here. Are you saying that we would only require Q and J_fr to be kwarg-only by allowing J and shape to be positional?

No, in my API everything is kwarg-based. Nothing is allowed to be positional. 


> I think the argument order was decided with the idea that only J would be the only required argument (note that Q has a default of one in Scattering1D). This would be possible when (if) we implement overlap–add type convolutions which don't require the filter size to be specified in advance.

I agree with this argument for Scattering1D but the situation is a little different for JTFS since there is no obvious default value for Q. So even with overlap-add, J, Q, and J_fr are mandatory and will stay that way. That's three required arguments, enough to make me wish to name them explicitly by kwarg rather than pass them by position.

**Comment by lostanlen** [comment]
> I'm not following here. Are you saying that we would only require Q and J_fr to be kwarg-only by allowing J and shape to be positional?

No, in my API everything is kwarg-based. Nothing is allowed to be positional. 


> I think the argument order was decided with the idea that only J would be the only required argument (note that Q has a default of one in Scattering1D). This would be possible when (if) we implement overlap–add type convolutions which don't require the filter size to be specified in advance.

I agree with this argument for Scattering1D but the situation is a little different for JTFS since there is no obvious default value for Q. So even with overlap-add, J, Q, and J_fr are mandatory and will stay that way. That's three required arguments, enough to make me wish to name them explicitly by kwarg rather than pass them by position.

**Comment by janden** [comment]
> No, in my API everything is kwarg-based. Nothing is allowed to be positional.

I got that. My question was in response to @cyrusvahidi's suggestion (https://github.com/kymatio/kymatio/issues/1032#issuecomment-1788684728).

> I agree with this argument for Scattering1D but the situation is a little different for JTFS since there is no obvious default value for Q.

I mean `Q = 8` wouldn't be so bad, would it? As long as it's specified clearly in the docs.

> That's three required arguments, enough to make me wish to name them explicitly by kwarg rather than pass them by position.

You can make that argument for most of the functions in our codebase (e.g. `scattering_filter_factory` has five required arguments). In fact, you could extend that argument to many Python API's. Note that as a caller you always have the ability to name the arguments (and I indeed often do this when I feel it would be confusing otherwise). It's probably a good point to do this in our docstring examples and in our gallery. However, that's quite different from *forcing* the caller to always name the arguments.

As I see it, we have two main options here:

1. Ensure callers always use kwargs.
2. Allow both positional and kwargs.

If we are to follow the principle of least surprise, we should pick one option and apply it uniformly across the codebase. I don't think it makes sense to carve out exceptions for functions that have a certain number of required arguments (indeed, I haven't seen this in any other API).

**Comment by janden** [comment]
> The problem is that a lot of users don't read the docs and just replicate a piece of code they've seen somewhere else, so they are not going to realize that there is a very important design choice here.

I agree. Hence the need for comments in the examples that we give and using named kwargs there. But just because there is a (small, I believe) portion of users that *may* make a mistake shouldn't force the remainder of users to use overly verbose syntax. 

> And we can't use the same default as `Scattering1D` (Q=1) so that would be another element of surprise.

You're right. So no default for `Q`.

> No because users are likely not going to call `scattering_filter_factory`, they will use a frontend.

Maybe. We have an example with it, but I guess most people won't play with it.

> I can live with either option.

Then I suggest we allow both, but make every effort to use named kwargs in examples, gallery, notebooks, etc. Power users can just use the positional arguments.

> My main concern is that i don't want to introduce default values for JTFS's Q, Q_fr, and J_fr.

That's fine with me. Although at the moment, we do have a default value for `Q_fr` (it's one). I think that's quite reasonable, but we can make it required instead.
