### ISSUE TITLE
BUG - my bad

### ISSUE THREAD

**Issue by edouardoyallon** [kymatio/kymatio#1045]
Woops - I screw up by merging some approved PRs whose tests were passing 6 months ago but not now .. maybe we should fix that ..

**Comment by MuawizChaudhary** [comment]
@janden I propose we merge the latest reversion #1047 and then try to fix the tests. Or should we fix in #1047?

**Comment by MuawizChaudhary** [comment]
> FAILED tests/scattering3d/test_utils_scattering3d.py::test_utils - TypeError: exceptions must be derived from Warning, not <class 'NoneType'>

This error occurs in python 3.8. I'll focus on solving this issue first.

**Comment by MuawizChaudhary** [comment]
Seems like this issue results from deprecation of `pytest.warns(None)`. the solution according to this reply [here](https://github.com/scikit-learn/scikit-learn/issues/22572#issuecomment-1047316960) is to replace with `warnings.catch_warnings(record=True)`.

**Comment by MuawizChaudhary** [comment]
>ValueError: Cannot convert '512' to a shape.
This error occurs in the scattering1d test, for keras, in versions >= python3.9.

**Comment by MuawizChaudhary** [comment]
I have no idea why this error occurs in the change in versions. All I know is that this error occurs for versions >= python 3.9, and it occurs on the first test of the keras 1d suite of tests `test_Scattering1D`.

**Comment by MuawizChaudhary** [comment]
#1048 solves this issue.

**Comment by MuawizChaudhary** [comment]
#1048 has resolved this issue.
