### ISSUE TITLE
sphinx-gallery: mnist.py

### ISSUE THREAD

**Issue by edouardoyallon** [kymatio/kymatio#110]
Please do a basic narrive, running script, pretty display. Un comment lline 60 of doc/conf.py to build the doc

Please close this issue only when you're happy with the sphinx-gallery.

**Comment by edouardoyallon** [comment]
@eugenium any news? let's end this up asap.

**Comment by eugenium** [comment]
I'll take care of it on Monday

**Comment by edouardoyallon** [comment]
looks good to me.

**Comment by janden** [comment]
There's still no narrative here. It's just a wall of code...

**Comment by edouardoyallon** [comment]
@eugenium hi

**Comment by edouardoyallon** [comment]
hi @eugenium
