### ISSUE TITLE
3D crashes on CPU

### ISSUE THREAD

**Issue by janden** [kymatio/kymatio#122]
Getting the following error when calling `forward`:
```
  File "/home/janden/projects/kymatio/scattering/scattering3d/scattering3d.py", line 326, in forward
    conv_modulus, method, method_args, j_1))
  File "/home/janden/projects/kymatio/scattering/scattering3d/scattering3d.py", line 175, in _compute_scattering_coefs
    return self._compute_standard_scattering_coefs(input_array)
  File "/home/janden/projects/kymatio/scattering/scattering3d/scattering3d.py", line 105, in _compute_standard_scattering_coefs
    convolved_input = self._low_pass_filter(input_array, self.J)
  File "/home/janden/projects/kymatio/scattering/scattering3d/scattering3d.py", line 85, in _low_pass_filter
    cuda = isinstance(input_array, torch.cuda.FloatTensor)
RuntimeError: cuda runtime error (30) : unknown error at /opt/conda/conda-bld/pytorch_1532584813488/work/aten/src/THC/THCGeneral.cpp:74
```
From what I understand, the code is set up to detect whether the input is GPU and apply the appropriate operators (there's not `cuda()` or `cpu()` functions to convert the transformer like in 1D and 2D). Looks like when I run this without CUDA enabled, it crashes when trying to determine the type of the input tensor. It might be my personal config, but I should mention that `torch.cuda.is_available()` works without crashing.

More bigger picture, do we want to modify this implementation to more closely align with the 1D/2D calling sequence? May make things easier for users (and also prevent the above type of errors).

**Comment by janden** [comment]
This needs to be fixed before release.

**Comment by eickenberg** [comment]
Yeah this is more important than having a skcuda backend for 3D

**Comment by janden** [comment]
Interestingly, this doesn't crash if `method='integral'` is specified. All tests in the 3D suite have this set, which is why Travis doesn't complain.

**Comment by janden** [comment]
Looks like the culprit is `Scattering3D._low_pass_filter` which checks CUDAness of the input using `isinstance(x, torch.cuda.FloatTensor)`. If `method='integral'`, this is never called, so no crash. The only other function checking CUDAness in this instance is `Scattering3D._rotation_covariant_convolution_and_modulus`, which uses `x.is_cuda`.
