### ISSUE TITLE
Clear Instructions for Backend (was: 2d has drastically slowed down on GPU versus pyscatwave)

### ISSUE THREAD

**Issue by eugenium** [kymatio/kymatio#125]
I've compared to imagenet sizes pyscatwave and kymatio 2d. The results are on 1080 Ti and use the script currently in examples/2d/compute_speed.py with a minor change

pyscatwave:
Elapsed time: 5.118290 [s / 10 evals], avg: 0.51 (s/batch)

kymatio:
avg: 3.06 (s/batch)

@edouardoyallon

To reproduce my results in the current speed example set N,M to 224

To reproduce the result for pyscatwave I attach the following script that is almost identical to the kymatio one and can be placed in the pyscatwave. Test done with pyscatwave master.. https://gist.github.com/eugenium/6e4a50f3d18d0e4b5ea42f25b31dbf67

**Comment by eugenium** [comment]
This is still a major issue. I attempted to use the software and could not figure out after 15 min how to make the backend swith correctly.

I attempted to install from pip as in the README. I also attempted to install from source. In both cases I tried to set KYMATIO_BACKEND, as well as KYMATIO_BACKEND_2D... the torch backend is always picked up and no warnings are thrown:

KYMATIO_BACKEND_2D=skcuda, CUDA_VISIBLE_DEVICES=6 python compute_speed.py
==> Testing Float32 with torch backend, on GPU, forward

**Comment by eugenium** [comment]
Looks like this was due to a bug in the pip version that @eickenberg is now aware of !!

**Comment by eickenberg** [comment]
when did you install the pip version? The new one should actually work with
the correct env variables

**Comment by eickenberg** [comment]
I propose to add a *Important for Deep Learning on Imagenet* section to the readme in order to make this very clear.

After release we can think about how to make this whole backend thing better

**Comment by lostanlen** [comment]
I find the collect_env.py script of PyTorch really useful for troubleshooting this kind of backend issues
https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
