### ISSUE TITLE
[MAINT] Update license

### ISSUE THREAD

**Issue by janden** [kymatio/kymatio#157]
First, there's another list of authors there. What to do about it? There's also how it should be named (`LICENSE` seems more standard than `licence.txt`). Finally, it doesn't seem to register with GitHub's license-detection mechanism (license box in top right only says `View license`, not `BSD 3-Clause` or whatever it is that we have).

**Comment by eickenberg** [comment]
Sounds good to me!

**Comment by lostanlen** [comment]
I can update the text of the license right now, but getting GitHub's license detection mechanism to recognize our `LICENSE` as `BSD-3-Clause` might be harder than expected.
See this open issue on the Go language for example:
https://github.com/golang/dep/issues/1431

**Comment by lostanlen** [comment]
Believe it or not, this looks more and more like a `wontfix`
https://github.com/golang/dep/issues/1431#issuecomment-441728253

**Comment by janden** [comment]
Huh. Did you try

https://help.github.com/articles/adding-a-license-to-a-repository/

on a branch to see what it does?

**Comment by lostanlen** [comment]
Yes. It id not possible to set a license on a branch or fork via the GitHub API.
And in kymatio/kymatio -> insights -> community, the license appears in green, which AFAICT is irreversible.

**Comment by janden** [comment]
Bleuh...

It seems like it lets me do it on the main repo. Maybe we could try this and rollback the commit if it doesn't work?

![image](https://user-images.githubusercontent.com/3976052/49055580-18ff4000-f1c6-11e8-8e3b-aec91d107ef9.png)

**Comment by lostanlen** [comment]
Sure, go ahead! Thanks

**Comment by janden** [comment]
Woohoo!

![image](https://user-images.githubusercontent.com/3976052/49055963-97a8ad00-f1c7-11e8-8803-08aee4b202ca.png)

**Comment by lostanlen** [comment]
closed by the capable hands of @janden
