### ISSUE TITLE
[BUG] cache management of 2-D filter banks

### ISSUE THREAD

**Issue by lostanlen** [kymatio/kymatio#175]
A bug found by running `pyflakes` on the Kymatio source.
Originating in code by @edouardoyallon  and @gabrielhuang

It happens in a `try` statement which is itself part of an `except` statement, so the bug is really hard to trigger, but it's there.

https://github.com/kymatio/kymatio/blob/56a846f059ba5e185a7378e4a057f11bea25552a/kymatio/scattering2d/filter_bank.py#L119
`filer_file` should read as `filter_file`

I think that, long term, this caching mechanic would be more elegantly (and more stably) implemented with `joblib.Memory`, and that the calls to `print` could be replaced by `logging`.

One example of joblib-based cache manager which comes very close to what we need here is available in `librosa`, cf. https://github.com/librosa/librosa/blob/master/librosa/cache.py

**Comment by eickenberg** [comment]
> filer_file should read as filter_file

:rofl: 

> I think that, long term, this caching mechanic would be more elegantly (and more stably) implemented with joblib.Memory

unclear to me whether that is good, since joblib saves anonymous hashes, whereas since we know all the parameters that go into filter generation, we can write informative filenames

> and that the calls to print could be replaced by logging

yeah probably a good idea as a general policy. takes some learning though and some decisions

**Comment by edouardoyallon** [comment]
I think I agree with @eickenberg . Long term will decide which solution to chose, for now I believe it's ok; feel free to open a new issue later.(I prefer several issues with single problems rather than several problems into one issue)
