### ISSUE TITLE
Inconsistency in disabling second order

### ISSUE THREAD

**Issue by lostanlen** [kymatio/kymatio#196]
The order of the scattering transform is integer in 1d (`max_order=2`), boolean in 2d (`order2=True`), decided at forward runtime in 3d (`order_2=True`).
I would propose to unify this and make it integer, so that third-order scattering could, in principle, be implemented in the future.
I don't love the name `max_order`. The `max` prefix makes it sound like it's signal-adaptive, whereas it's a static choice.
I suggest `n_orders=2`.
If we want to have different outputs at runtime, we can always have kwarg `orders=[1,2]` in `forward`, but that's another story.

**Comment by lostanlen** [comment]
Either we do it now, either we postpone it to `0.2.0` along with a deprecation, and remove the deprecation in `0.3.0`. Thoughts?

**Comment by lostanlen** [comment]
> Not sure about n_orders. Note that current max_order=2 corresponds to n_orders=3 since we have orders zero, one, and two.
Oh my, that's a good point.
Come to think of it, I like `max_order` more than `n_orders`. Because the `orders` can be changed at runtime between `0` and `max_order-1`. Shall I make a PR?

**Comment by janden** [comment]
> Come to think of it, I like `max_order` more than `n_orders`.

Ok great!

> Because the `orders` can be changed at runtime between `0` and `max_order-1`.

Am I missing something here or do you mean `orders` can contain values between `0` and `max_order`?

> Shall I make a PR?

Yes please!

**Comment by lostanlen** [comment]
> Am I missing something here or do you mean orders can contain values between 0 and max_order?

No, you're right. Anywhere between `0` and `max_order`. And it defaults to `range(0, 1+max_order)`. 
I got bitten by EWD 831 again

**Comment by eugenium** [comment]
wait your telling me I can do Scattering2d(max_order=0)?  lol

**Comment by lostanlen** [comment]
@eugenium I mean, it's a pretty contrived way to compute a Gaussian blur, but who's to say that there will never be a use case for it? :p

**Comment by janden** [comment]
> wait your telling me I can do Scattering2d(max_order=0)? lol

Why not? I think it works in `Scattering1D` already. Go ahead, try it for yourself!

**Comment by lostanlen** [comment]
@eickenberg the kwarg `orders` can be added later.
here we do not have one because we only officially support `orders=range(0, 1+max_order)`
but this kwarg is useful for:
* skipping the zeroth order (in audio for example)
* skipping the second order without having to construct a whole new operator

`max_order` would be stored as `_max_order` (pseudo-immutable) in the object
but
`orders` would be stored as `orders` because it is mutable (as any subset of `range(0, 1+max_order)`)

would you be OK with this agenda?

**Comment by eickenberg** [comment]
>  this kwarg
meaning `orders=` ?

> would you be OK with this agenda?
agenda == 1. add `max_order` now 2. add `orders` some time in the future?
then yes

**Comment by lostanlen** [comment]
yes, `this kwarg` is `orders` :) 
shall we rebase and merge #212 then?

**Comment by eickenberg** [comment]
Yes

**Comment by janden** [comment]
So is this done?

**Comment by lostanlen** [comment]
@janden no, #212 was only for 2D. For 1D it's just a rename. For 3D it's a little bit more involved because at the moment the number of orders is a kwarg of `forward`. It should be made part of the constructor

**Comment by janden** [comment]
Ok. What's the rename in 1D?

**Comment by lostanlen** [comment]
I stand corrected. No rename needed: it's already named `max_order`, as it should. *À la bonne heure!* ;)

**Comment by janden** [comment]
Ok. Agreed about 3D. Will look into that tomorrow. In general, I think we should avoid arguments to `forward` and have these be attributes set in the object (like we did in `Scattering1D`).

**Comment by lostanlen** [comment]
yes, i remember you writing that. i agree. but 3d has a lot of runtime forward kwargs, so it's overdue for a refactoring of the API

**Comment by janden** [comment]
Will make a separate issue.
