### ISSUE TITLE
README needs more resources before 0.1.0-alpha

### ISSUE THREAD

**Issue by lostanlen** [kymatio/kymatio#204]
Our README file needs some love before alpha release
- [x] link to PyPI rather than test simple (in anticipation of release)
- [x] temporarily remove reference to paper for citing
- [x] write contributing guidelines and put a link to them in README
- [x] link to source code, PyPI, and issue tracker (like scikit-learn)

A good model is scikit-learn: https://github.com/scikit-learn/scikit-learn/blob/master/README.rst

**Comment by lostanlen** [comment]
Yes, I began last week with a stub of `CONTRIBUTING.md` (#172 ) which was adapted from scikit-learn but then I got confused with git branches so I closed the PR. We need to start afresh, possibly with some of the things I made in #172

**Comment by edouardoyallon** [comment]
@lostanlen what's the status?
