### ISSUE TITLE
`Scattering3D` crashes for `J != 2`

### ISSUE THREAD

**Issue by janden** [kymatio/kymatio#216]
This was introduced by concatenation along the wrong axis in 36bfb11f29c0e7a3cddfc1eedc23ba84e9c17ea8. Instead of concatenating along axis 1 (that is, the spatial dimension), the concatenation should (of course) be along axis 2 (that is, the filter index/scale dimension).

It was not caught by the test suite since all tests have `J = 2`, which has the special property that the number of first-order scales (3) is equal to the number of second-order scales (2+1). We should modify the test suite so that this doesn't happen.

**Comment by eickenberg** [comment]
:confounded:

**Comment by eickenberg** [comment]
could you open a PR with a test added to the 3d that fails?

**Comment by janden** [comment]
Unfortunately, this cannot be easily resolved at the moment without reverting #210 or severely butchering the `test_against_standard_computations` test in the 3D test suite. The issue is the (incompatible) storage of the output array stored as part of the test and the array output by `Scattering3D`. The former is stored in the layout `(order*integral_power*scale*ell)` (as a flat array), while the latter is stored as `(integral_power, order*scale, ell)` (as a 3D array). Ideally, we'd want to store the output as `(order, integral_power, scale, ell)` which can then be easily flattened, but that's not possible since each order has a different number of scales (unless `J=2`, of course).

One solution is to hardcode the numer of order-one scales in the unit test so that those can be extracted from the stored reference and the array can be permuted to align with the output of `Scattering3D`. Another is to go back to tuples. Another is to permute the output of `Scattering3D` to instead read `(order*scale, integral_power, ell)`, but that would require quite a bit of work.

**Comment by janden** [comment]
> could you open a PR with a test added to the 3d that fails?

Yes.
