### ISSUE TITLE
Make inputs dimension-agnostic (1D/2D)

### ISSUE THREAD

**Issue by janden** [kymatio/kymatio#218]
In other words, make `Scattering*D` operators act only on last dimension without forcing a specific convention on previous dimensions. The output would have the same shape, but this the time/spatial dimension subsampled and another (scattering) dimension added right before it. So we'd have

- in 1D, `batch_shape + (T,)` input gives `batch_shape + (C, T/2**J)` output, and
- in 2D, `batch_shape + (N, M)` input gives `batch_shape + (C, N/2**J, M/2**J)` output,

where `batch_shape` is some (possibly empty) tuple specifying the batch dimensions that are not to be processed and `C` is the number of scattering coefficients.

The 3D case is more complicated since it follows a different output schema compared to the 1D and 2D, which will be addressed in a separate issue. That being said, it would be good if it could mimic the above behavior.

**Comment by lostanlen** [comment]
Thanks for raising this Joakim. For future reference, this originated in PR #215 which closed issue #213, which itself was derived off #158.
Quoting Semver 7:
> Minor version Y (x.Y.z | x > 0) MUST be incremented if new, backwards compatible functionality is introduced to the public API. 

Therefore this change should be marked as `0.2.0`, not `0.1.0-beta`.

**Comment by janden** [comment]
Even if it's backwards-compatible, huh? Didn't know that.

Ok so unless we can push this into `0.1.0-alpha`, `0.2.0` it is. It honestly shouldn't be that hard.

**Comment by lostanlen** [comment]
https://semver.org is an insightful read.
during `0.y.z` phase:
* backwards-incompatible API changes push to `0.(y+1).z`
* backwards-compatible API changes push to `0.(y+1).z`
* bugfix changes push to `0.y.(z+1)`

during `x.y.z` phase where `x>0`:
* backwards-incompatible API changes push to `(x+1).y.z`
* backwards-compatible API changes push to `x.(y+1).z`
* bugfix changes push to `x.y.(z+1)`

**Comment by janden** [comment]
Ok makes sense. Good thing we don't have `x>0` then. Sounds like a pain....
