### ISSUE TITLE
3D output format

### ISSUE THREAD

**Issue by janden** [kymatio/kymatio#222]
Currently, `Scattering3D` takes an input of shape `(B, M, N, O)`, where `B` is the batch size and `M, N, O` is the shape of the input signal. Depending on `method`, the output takes different formats:

- If `method='standard'`, the output is of shape `(B, 2*M*N*O, total_scales, L+1)`, where `total_scales` is the number of scales at all orders, that is `(J+1)+J*(J+1)/2` if `order_2=True`. The factor `2` in the second axis comes from the fact that these are still stored as "complex" values (even though they are real), so every other element along that axis is zero. These zeroes should probably be eliminated.
- If `method='integral'`, the output is of shape `(B, len(integral_powers), total_scales, L+1)`, where `integral_powers` is the argument provided to `forward()`.
- If `method='local'`, the output is of shape `(B, points.shape[1], total_scales, L+1)`, where `points` is the argument provided to `forward()`.

The first question is whether we should provide all these outputs through the same interface. To a certain extent, `'integral'` and `'local'` can be computed from `'standard'`, but this may not be computationally optimal.

The second question is how to structure these outputs to be more consistent with 1D and 2D. I suggest that we adopt a similar output shape `(B, C, M, N, O)`, where the second axis comingles orders, scales, ells, integral powers, and points, as the case may be. Alternatively, for `'integral`' and `'local'`, the third axis could index `integral_powers` or `points` instead of a singleton spatial dimension.

**Comment by janden** [comment]
Need to figure this out before release... @eickenberg, @louity?

**Comment by eickenberg** [comment]
> If method='standard', the output is of shape (B, 2*M*N*O, total_scales, L+1), where total_scales is the number of scales at all orders, that is (J+1)+J*(J+1)/2 if order_2=True.

😱 😱 ❗️ ❗️ ❗️ 

Why do we ravel space and not keep it like every other part of this software package?

> These zeroes should probably be eliminated.

yeah

> where integral_powers is the argument provided to forward()
👎 

> where points is the argument provided to forward()

maybe OK.

> 'integral' and 'local' can be computed from 'standard', but this may not be computationally optimal.

indeed, though I do not know whether the code actually does anything to optimize. But I think these possibilities should be kept because 3D can easily fill up GPU memory.

> I suggest that we adopt a similar output shape (B, C, M, N, O), where the second axis comingles orders, scales, ells, integral powers, and points, as the case may be.

yeah I agree

> Alternatively, for 'integral' and 'local', the third axis could index integral_powers or points instead of a singleton spatial dimension.

yeah why not


I agree that this needs to be addressed.

**Comment by janden** [comment]
> Why do we ravel space and not keep it like every other part of this software package?

:man_shrugging: 
 
> > These zeroes should probably be eliminated.
> 
> yeah

I'm glad we agree on this.
 
> > where integral_powers is the argument provided to forward()
>
> -1

So make this an attribute? This is what #230 suggests.
 
> > where points is the argument provided to forward()
> 
> maybe OK.

Again, #230 is the place to discuss this. For consistency, I'd prefer no arguments to `forward` except for the array.

> > 'integral' and 'local' can be computed from 'standard', but this may not be computationally optimal.
> 
> indeed, though I do not know whether the code actually does anything to optimize. But I think these possibilities should be kept because 3D can easily fill up GPU memory.

Well, you skip a lowpass filter in `integral` and I think `local` replaces that lowpass convolution with an inner product, so those should be non-trivial speedups.

> > I suggest that we adopt a similar output shape (B, C, M, N, O), where the second axis comingles orders, scales, ells, integral powers, and points, as the case may be.
> 
> yeah I agree

Ok good.

> 
> > Alternatively, for 'integral' and 'local', the third axis could index integral_powers or points instead of a singleton spatial dimension.
> 
> yeah why not

Good.

> I agree that this needs to be addressed.

Ok. So if I've understood correctly, this is the plan:

- Remove extraneous zeros in `standard`.
- Do not ravel space in `standard`.
- Make third axis index `integral_powers` (for `integral`) or `points` (for `local`).
- (Remove kwargs and put them as attributes, but again, this is #230)

Does that sound correct?

**Comment by janden** [comment]
> while we're at it, i should add that I don't find the kwarg name `method` to be informative enough. I had this discussion with @eickenberg last month. Him and I came up with the name `sampling` as a replacement for `method`.

Ok. Can you make a separate issue?
