### ISSUE TITLE
Simplify 1D constructor

### ISSUE THREAD

**Issue by janden** [kymatio/kymatio#227]
Right now, there are several arguments to the `Scattering1D` class that are not used: `criterion_amplitude`, `r_psi`, `sigma0`, `alpha`, `P_max`, `eps`. Another argument, `normalize`, is used in one of the tests, but set to its default value (`'l1'`). While it is good to have flexibility, there is currently no evidence that the defaults give unsatisfactory results. Furthermore, having these options make it harder to follow what's going on and increases the burden for us in maintaining backwards compatibility.

This last point is important because there is likely some reduction and refactoring possible here. For example, `criterion_amplitude` and `eps` both refer to a precision in computing the filter bank, while `P_max` refers to the number of periods to use in computing a filter. These could probably be computed from a single tolerance value. Further, `alpha` is the "aliasing tolerance after subsampling" and may be calculated from the `oversampling` parameter (or vice versa). The other parameters, `r_psi`, `sigma0`, and `normalize`, are more independent, but the question remains how to specify them in a way that's simple and compatible with the other transforms.

Until we have decided how to structure these interfaces, I think it's a good idea to fix these parameters to their default values and bring them back into the interface when it's time.

**Comment by eickenberg** [comment]
I agree with this. For the first release I'd propose to either not do anything or, as you suggest, fix the parameters, maybe for the moment in the `build` method as class attributes

**Comment by janden** [comment]
Ok. I like the idea of putting these as attributes and using them during `build`. I'd still keep them out of the docs, though, for now.
