### ISSUE TITLE
[RFC] `method` kwarg is not descriptive enough

### ISSUE THREAD

**Issue by lostanlen** [kymatio/kymatio#239]
This came in discussion over Slack and resurfaced in #222
I would be in favor of renaming the `method` kwarg in `Scattering3D` to something more descriptive, like `sampling`.
Below is a discussion I've have with @eickenberg 3 weeks ago on the topic. You will see that, at first, I'm in favor of the term `averaging`, and then I change my mind to `sampling`.

> lostanlen [21 days ago]
> I would be in favor of renaming the `method` kward in scattering3d, into `averaging`
> so that `standard`, `integral`, and `local`
> would rename to
> `local`, `global`, and `foveal` respectively
> this distinction is also very useful in 1d and 2d, so it could be added in the future without API break
> `points` could be renamed to `foveal_coords` for clarity but that’s a small change that does not require a cross-module deprecation (edited)

Michael [21 days ago]
I agree with all of that except the word foveal - not sure that is the right term, but maybe I also don't completely understand the concept

> lostanlen [21 days ago]
> this is something on which @Mathieu has more expertise, but it’s basically the scattering transform 
> of x(t) computed only at t=0 (or at a small, finite number of points) rather than at every t
> so that spares the convolution with phi for going from U to S, which considerably speeds up the code
> this is super useful in time series forecasting. also when you don’t need invariance to translation because the object is already registered around a natural “center” for you.
> see paper by Chang, Mallat, and Yap in Applied and Computational Harmonic Analysis. It’s brilliant 
> `foveated` might be preferable over `foveal`. `foveated` is computer vision terminology whereas `foveal` relates more to anatomy

Michael [21 days ago]
Oh yeah I know that paper -- I just didn't see a connection to the 3d option of evaluation in specific points, since these need not be foveal points

> lostanlen [21 days ago]
> why not? aren’t they foveal points by virtue of being “specific” (i.e. user-defined)?

Michael [21 days ago]
To me a fovea is a point of concentration of measurements, not just a specific choice of measurements
given a certain budget of measurements but which you get to apply anywhere, for some signals and tasks it is beneficial to concentrate them
e.g. https://bair.berkeley.edu/blog/2017/11/09/learn-to-attend-fovea/
The Berkeley Artificial Intelligence Research Blog
The Emergence of a Fovea while Learning to Attend
The BAIR Blog (135 kB)

> lostanlen [21 days ago]
> ok, so that is necessarily an adaptive thing?
> hm

Michael [21 days ago]
not adaptive necessarily, but concentrating measurements

> lostanlen [21 days ago]
> perhaps `averaging=None` would make the most sense then? (edited)
> well no because that could imply that we return the whole `U` for every `t`, not just near one point `t=0` 

Michael [21 days ago]
i.e. specifying a regular grid of measurements is not foveating, and one can do that in the 3d case. so i don't think it's about foveating but rather just evaluating wherever one wants
but again, I don't even understand what this was implemented for. If it was implemented with foveation in mind, then maybe it's legit to call it that
So I would definitely like to see an `averaging=None` option for returning U, but the evaluation in specific points thing seems to be different from that

> lostanlen [21 days ago]
> right.
> ... and I thought `averaging='foveal'` was clever :/
> I have an idea. It’s good and bad at the same time
> `averaging=x` where the array-like variable `x` contains the point(s) around which we measure the scattering transform
> then `sampling` would be a better term than `averaging`
> (and that could generalize beyond averages, like `ell_p` pooling for instance)
> so `sampling='local'` (default), `sampling='global'` (aka `integral`), `sampling=x` (return U at specific values), `sampling=None` (return U entirely, but that’s out of the scope of 0.1) (edited)

Michael [21 days ago]
is `local` low-passed or how is it different from `None` ?
I like the idea in general

> lostanlen [21 days ago]
> yeah, `local` is low-passed

Michael [21 days ago]
more generally I guess it is an "output transform"
(at the implementation level)

> lostanlen [21 days ago]
> right. but this matters a lot because Kymatio is depth-first to minimize the memory overhead

Michael [21 days ago]
`sampling` seems like a good word for it

> lostanlen [21 days ago]
> so we can’t guarantee that U2 will fit into memory (especially in GPU memory). therefore we “sample” (average, pool, sum, cherry-pick values, whatever) each path before computing the next one

**Comment by lostanlen** [comment]
If you're on board with this, I can write a PR to rename `method` into `sampling`. That frees up the name `method` for more abstract things, and it also makes it more generic so that it can eventually apply to 1D and 2D.

**Comment by janden** [comment]
Sounds good to me.

**Comment by lostanlen** [comment]
oh ... `0.1.0-alpha` is out now. So should I tag this `0.2`?

**Comment by eickenberg** [comment]
we haven't released yet, but i'd still tag this for next release.

**Comment by lostanlen** [comment]
closed by #251. Scattering3d is now known as HarmonicScattering3d, so it's acceptable for it to have its own custom methods for spatial sampling. It's also a win for reproducibility to keep it, and incurs no loss of consistency now that it has a clearly separate class name
