### ISSUE TITLE
Uses for `method='points'`

### ISSUE THREAD

**Issue by eickenberg** [kymatio/kymatio#241]
This seems to me like it is an extremely specific case for a research setting that we don't actually need in the software package.

In a future release I'd prefer replacing it by having the possibility of getting `U` returned and then doing the required sampling oneself.

@gexarcha @louity was/is "points" used a lot by you guys? If it has proved useful it might merit a place in the software. If not, I'd prefer getting rid of it in favor of a simpler codebase

**Comment by lostanlen** [comment]
@eickenberg I know nothing about this, but I can see how, if the locations of the atoms are known (and they are, in the case of a known molecule), it might make sense to only evaluate U at the nuclei of these atoms, and then derive some quantum chemical properties out of the scattering coefficients of "each atom".
Likewise, in the foveated scattering of Mathieu and Ravi, the "points" method is used for prediction: causal wavelets (truncated Gabors) estimate U0 at t=0 (in other words, the present time) to predict the value of x at t=delta for small delta. So having a `points` in 1D would also make sense for that.

These are just my 2c. I defer the decision to @gexarcha @louity @eickenberg  and possibly @AndreuxMath and @beedotkiran too

**Comment by janden** [comment]
Right, but I think @eickenberg's proposed solution is simpler: allow the user to calculate `U` (which we should be doing in any case), then have some way to generate `S` at different products by taking inner products (we can have a different function for this).

In general, I think we want to separate the responsibilities as much as possible between functions. This needs to be balanced with memory constraints (and other concerns), of course. The issue with the proposed solution here is that we're keeping around all of `U` only to compute a few inner products. This goes against the whole DFS approach that we follow in the rest of the code.

**Comment by lostanlen** [comment]
> The issue with the proposed solution here is that we're keeping around all of U only to compute a few inner products. This goes against the whole DFS approach that we follow in the rest of the code.

Ah. To be honest I didn't look at the 3D code for how `points` was implemented. If it's not DFS, then that's another reason to keep it outside Kymatio (as a public-facing library). Then again, I don't see anything that prevent doing these inner products by DFS in the futre ...

**Comment by lostanlen** [comment]
closed by #251. `Scattering3d` is now known as `HarmonicScattering3d`, so it's acceptable for it to have its own custom methods for spatial sampling. It's also a win for reproducibility to keep it, and incurs no loss of consistency now that it has a clearly separate class name
