### ISSUE TITLE
Default value for `Q`

### ISSUE THREAD

**Issue by janden** [kymatio/kymatio#245]
For 2D and 3D, we have defaults for all parameters except `J` and `shape`, but `Scattering1D` also requires `Q`. Should we give a default for this? `Q=8`?

**Comment by janden** [comment]
Will also simplify the paper somewhat, since we don't have to get into a discussion about `Q` this way.

**Comment by janden** [comment]
> Worth asking @AndreuxMath about that.

Yes. @AndreuxMath, could this pose a problem?

> Another point worth keeping track of is the `phi_bw_multiplier`. The definition of `J` changes whether `Q==1` or not, so it's worth putting some thought into this to clarify.

Where does this happen?

**Comment by lostanlen** [comment]
> Where does this happen!

I stand corrected: it's actually independent of `Q`! :)

https://github.com/kymatio/kymatio/blob/master/kymatio/scattering1d/filter_bank.py#L548

**Comment by janden** [comment]
Ok.

**Comment by AndreuxMath** [comment]
Any value of `Q` can be used as default I guess, as long as it is mentioned that this is an important parameter to change depending on data.

**Comment by janden** [comment]
Ok good. Thank you!
