### ISSUE TITLE
Fix ordering of orders

### ISSUE THREAD

**Issue by janden** [kymatio/kymatio#248]
Right now, first- and second-order coefficients are interleaved in 1D and 2D. In 3D, we first have first order, then second order. For consistency, it should be the same across dimensions. I propose we abandon the interleaved format and concatenate.

**Comment by lostanlen** [comment]
Yes. This is a bit of a clash with respect to the spirit of DFS, but much more in line with what's in the paper (Sx defined as the concatenation of S1x and S2x), so let's do it. It also makes extracting the subset of first-order coefficients most convenient. Lastly, it's nicely fitting to their definition that first-order coefficients should be, well ... first in order.

**Comment by lostanlen** [comment]
closed by #246 and #247
