### ISSUE TITLE
`Scattering3d` should be renamed

### ISSUE THREAD

**Issue by lostanlen** [kymatio/kymatio#250]
As pointed out by @eickenberg in https://github.com/kymatio/kymatio/pull/249#issuecomment-447676253, `Scattering3d` is useful for energy regression in quantum chemistry, but has many idiosyncracies (custom spatial sampling, `ell_p` pooling, meaning of `L`, etc.) that cannot be made perfectly consistent with `Scattering1d` or `Scattering2d`.

So it needs a rename ... `SolidHarmonicScattering3d` nicely matches the title of the paper. It's a bit long, but I think that it's fine. It's not a name one would type repeatedly in code, and autocompletion solves that problem in part too.

**Comment by janden** [comment]
Why not `HarmonicScattering3D`? Not all of us are blessed with autocomplete...

**Comment by janden** [comment]
Or like spend 33% of my line length on a class name...

**Comment by eickenberg** [comment]
I'm fine with HarmonicScattering3d. That would allow us to go away from
specifically solid harmonics if we wanted to

**Comment by janden** [comment]
Ok. Are these solid harmonics if it's Gaussian * Y_lm? Wouldn't that be r^l * Y_lm?

**Comment by lostanlen** [comment]
I'm fine with `HarmonicScattering3d`. In fact I'm fine with anything that does not have the name `Spiral` in it :p

**Comment by eickenberg** [comment]
> Wouldn't that be r^l * Y_lm?

Yes, that, sorry.

OH ....

That changes these filters to be not completely  low-pass anymore.

OK still. We are parking this thing in `HarmonicScattering3D` and will clean it up bit by bit. We will be starting from something that gives reasonable results on qm7, so we have a guideline/benchmark to work with.
