### ISSUE TITLE
typos in the README.md

### ISSUE THREAD

**Issue by edouardoyallon** [kymatio/kymatio#256]
> then, set the KYMATIO_BACKEND_2D to skcuda:
> 
> os.environ["KYMATIO_BACKEND_2D"] = "skcuda"

Why only 2D?

**Comment by janden** [comment]
Indeed. I ran `KYMATIO_BACKEND=skcuda pytest kymatio` yesterday and it's fine.

**Comment by lostanlen** [comment]
Yes, #208 considerably simplifies the installation instructions. Feel free to rewrite without special-casing 2D

**Comment by janden** [comment]
Also: do those lines actually work? That is, can we set the environment variables from within Python? I thought they had to be set from outside.

**Comment by lostanlen** [comment]
closed by #258
