### ISSUE TITLE
MAINT+ENH Quality assurance via benchmarking

### ISSUE THREAD

**Issue by eickenberg** [kymatio/kymatio#259]
Our codebase is prone to evolve quite a bit in the future. With every change, it is very easy to incur regressions in speed. Before making major refactorings, such as unifying backends across 1d, 2d, 3d, we need to have systematic benchmarking to check that we are not messing up.

This seems like a good framework with examples online:

https://asv.readthedocs.io/en/stable/

We already have benchmarking scripts called `compute_speed.py` in the examples. To organize this, we should
- Make a folder called `benchmarks`, just like `examples`
- Fill it with benchmarks of the relevant functionalities, including filter generation and forward (and backward) operators

**Comment by edouardoyallon** [comment]
@janden maybe you could refactor following this in order to solve this issue, and add a plugin @ flatiron?
