### ISSUE TITLE
DOC order examples according to runtime + add options to sphinx-makefile to include or exclude

### ISSUE THREAD

**Issue by eickenberg** [kymatio/kymatio#260]
- The sphinx gallery uses file name patterns in the example folder to decide whether to execute the example and recover the plots or not.
- These patterns are set in `conf.py`. Currently the pattern is that everything starting in `plot_` is executed, everything else is just displayed as code
- It is possible to override all `conf.py` configs in the command line args to the sphinx build script.
- We should use this to create 3 tiers of doc building: `full`, in which even the slowest examples are built, `fast`, which should be default and include reasonably timed scripts + I think there already exists an option to turn the gallery off altogether, if one so desired. All these options should go in the make file, e.g. as `make html-full` etc

**Comment by edouardoyallon** [comment]
Is still relevant?
