### ISSUE TITLE
ENH simple unifications

### ISSUE THREAD

**Issue by eickenberg** [kymatio/kymatio#261]
Unifications that seem to be within easy reach are

- **complex magnitude computation:** This is a pointwise operation that doesn't care about the shape of the array
- **nd-fourier:** with an `fftn` type operation, it should be possible to unify fourier by simply specifying the axes that we want the transform to happen on for each different package
- ~~**subsampling:** as long as we are talking about strict diadic subsampling, this can happen independently per axis, both in Fourier and in signal space;~~ CF DISCUSSION IN SLACK 

The way this should be done is to have a folder `backend_common` on the same level as `scattering1d, scattering2d, scattering3d` which implements the general functions. These are then imported into the backends specific to the scattering dimensionality. This procedure gives us the opportunity to unify bit by bit, and also to have the dimensionality-specific backends perform the necessary dimensionality-specific modifications if necessary.

**Comment by lostanlen** [comment]
Yes, this is a good idea. I may be able to devote some time to this.
 @eickenberg I don't understand the filesystem structure you outlined
`kymatio/backend_common/complex.py`
`kymatio/backend_common/fourier.py`
`kymatio/backend_common/sampling.py` ?
Or something else?

**Comment by eickenberg** [comment]
That looks good and could work well I think. It depends on how much code we'll end up with. It could easily evolve from a `backend_common/backend_pytorch.py` to a file structure like the one you outlined (`backend_pytorch_fourier.py` etc). Or start there immediately. We might want to add the actual backend names as folders, instead of this sort of infix.

**Comment by edouardoyallon** [comment]
Hey, one more thing that could make sens is to use some OOP: one could make a class parent that implements common routines and provide the minimal environment to deploy other versions of the scattering, such as: 3D-gabor scattering, roto-translation scattering, roto-translation-separable scattering, harmonic phase scattering, video scattering, ..

For instance, .cuda(), .cpu(), forward(), J, meta, build(), psi, phi are examples of methods and attributes that could be reasonable shared.

**Comment by edouardoyallon** [comment]
Let's forget about OOP (we discussed it with michael). So, if this sounds OK, I'd like to do this via several progressive PR. I think the best feature to share, in a first step, is CDGMM as it's literally the same kernel for 1-2-3 D.

**Comment by janden** [comment]
Agreed on `cdgmm`. `Modulus` is up there, too.

**Comment by edouardoyallon** [comment]
Okay, waiting that one merges several branches before doing anything. I'm a bit concerned by "modulus stable" in 1D, is it really changing anything or is this an overkill?

**Comment by janden** [comment]
> I'm a bit concerned by "modulus stable" in 1D, is it really changing anything or is this an overkill?

From what I understand, it makes sure we have differentiability at zero. That being said, I haven't tested it.

**Comment by edouardoyallon** [comment]
would be awesome to confirm and if yep, adding it to 2D as well

**Comment by janden** [comment]
Yes. And 3D. This is on my TODO list.

**Comment by edouardoyallon** [comment]
instead to create a `common_backend`, I propose to create a folder at the root of the software as I did for `frontend`

**Comment by lostanlen** [comment]
is this issue still relevant? i see no plan for dimension-agnostic backends in the currents PRs

**Comment by MuawizChaudhary** [comment]
It seems like we are waiting to release Kymatio v.2 then we'll start work on the common backend. 

(Personally, I'd be down to work on the unification of the backends over my winter break, even if v.2 is still in review. )

**Comment by lostanlen** [comment]
OK! Presumably that unification won't affect the API, so it's totally OK to defer it to a later stage of dev (v0.2.x or v0.3+).
I just wanted to make sure that it was not getting out of sight given all the outstanding work that you've been putting together towards re: v0.2 !!

**Comment by MuawizChaudhary** [comment]
> Let's forget about OOP (we discussed it with michael). So, if this sounds OK, I'd like to do this via several progressive PR. I think the best feature to share, in a first step, is CDGMM as it's literally the same kernel for 1-2-3 D.

Is this opinion still the same, or might the opinion on having some OOP have changed? I know earlier in a PR (I think #449 ) we were talking about further refactoring the backend in a future update (switching away from the named tuple stuff). Maybe we want to quote that discussion here (I cannot seem to find it)?

**Comment by edouardoyallon** [comment]
This will be done later, the backend begins being pretty pretty flexible

**Comment by janden** [comment]
From @MuawizChaudhary, on `fft1d_c2c` etc. in 1D:
```
Maybe we want to do what we do in the 2d and 3d scattering transform, and pass in which FFT we are doing as a string?
```

**Comment by edouardoyallon** [comment]
I'd like to address the subsampling in a different issue,
