### ISSUE TITLE
ENH tf backend

### ISSUE THREAD

**Issue by eickenberg** [kymatio/kymatio#264]
Can we make a backend using tensorflow or tensorflow eager mode?

This attempt might inform how we can create a useful, better backend structure

**Comment by edouardoyallon** [comment]
Hi,
in order to incorporate tf:
this sould be moved in the backend...
https://github.com/kymatio/kymatio/blob/master/kymatio/scattering2d/scattering2d.py#L110-L129

**Comment by edouardoyallon** [comment]
Are you OK that I try to transfer few issues about Tf in: https://github.com/kymatio/kymatio/projects/1 ? It would clean a bit the Issue list. If yep, I'll copy paste the content there and close this issue. Future discussions could be done there as well!
