### ISSUE TITLE
TST Improve test coverage

### ISSUE THREAD

**Issue by janden** [kymatio/kymatio#265]
Currently, it's ok, but it can be a lot better. One thing to try, as well, would be something like [coveralls](https://coveralls.io/) to keep track.

**Comment by lostanlen** [comment]
This issue is a bit vague. I would suggest we consider it closed once Coveralls is up. And then reopen some issues for certain files that have very low covrage. Otherwise this issue will always remain open / seem out of reach.

**Comment by janden** [comment]
Of course. I just want a place to organize these ideas and set up a plan of attack.
