### ISSUE TITLE
ENH+REF backend logistics + mechanics

### ISSUE THREAD

**Issue by eickenberg** [kymatio/kymatio#266]
Currently, our backend structure is set up at import and cannot be changed after import. This is because at import, the `backend/__init__.py` checks which backend is being used, and just imports `*` from the corresponding backend file. This is then fixed for the whole runtime.

Ways of implementing backends: It's basically about when the decision is made:
- at install
- at import
- at instantiation

I'd like to advocate changing to the latter. This would have the advantage of being able to load whichever backend we wanted, and even used two at the same time. That might come in handy. It would be especially good for testing, because then we could compare things within one script.

Of course, having backend choice at instantiation can be pushed even further to having a different backend for each piece of the scattering transform. This might be pushing it a bit, but I see it as a way of implementing the above.

Key points for being able to do this:
- everything backend-specific must be confined to the backend files. The backend package is only ever imported in there.
- we need a very smart `check_array` function that can figure out which type of array we are getting as input, perform conversion if requested or raise an error if wrong format is received. This function will take some work to write
- Without noticing, I think our code is infused with pytorch-specific commands. We'd need to clean that up.
- we can also easily say for some functionality "hey this isn't implemented yet for this backend"

Advantages of doing this:
- our software doesn't die when a framework becomes unpopular
- it can be used with the major frameworks
- we are forced to think about semantics of the subcomponents of the transforms and to keep our files tidy

Disadvantages:
- it might not be super stable if coded in a rushed manner

**Comment by janden** [comment]
> I'd like to advocate changing to the latter. This would have the advantage of being able to load whichever backend we wanted, and even used two at the same time. That might come in handy. It would be especially good for testing, because then we could compare things within one script.

Agreed.

> Of course, having backend choice at instantiation can be pushed even further to having a different backend for each piece of the scattering transform. This might be pushing it a bit, but I see it as a way of implementing the above.

I don't understand. What's "each piece"?

> 
> Key points for being able to do this:
> 
>     * everything backend-specific must be confined to the backend files. The backend package is only ever imported in there.

So this includes any operation done on a tensor (FFT, mult, subsample, etc., but also shape, reshape, and so on?), since this may be done differently in PyTorch, skcuda, TF, etc. Correct?

>     * we need a very smart `check_array` function that can figure out which type of array we are getting as input, perform conversion if requested or raise an error if wrong format is received. This function will take some work to write

I don't quite follow. If the wrong format is received, should it raise an error or convert? Those are two very different scenarios. Should it convert only in certain circumstances?

>     * Without noticing, I think our code is infused with pytorch-specific commands. We'd need to clean that up.
> 
>     * we can also easily say for some functionality "hey this isn't implemented yet for this backend"

Yes and yes.

> Advantages of doing this:
> 
>     * our software doesn't die when a framework becomes unpopular
> 
>     * it can be used with the major frameworks
> 
>     * we are forced to think about semantics of the subcomponents of the transforms and to keep our files tidy

All good things.

> Disadvantages:
> 
>     * it might not be super stable if coded in a rushed manner

Which brings up the point of timing. It seems like a lot of the previous issues should be addressed before moving on to this, but some more careful planning is needed here.

**Comment by eickenberg** [comment]
> I don't understand. What's "each piece"?

I was thinking: `convolution`, `nonlinearity/modulus/magnitude`, `downsampling`

Maybe there are a few other operations like that. The basic ingredients basically

> So this includes any operation done on a tensor (FFT, mult, subsample, etc., but also shape, reshape, and so on?), since this may be done differently in PyTorch, skcuda, TF, etc. Correct?

Indeed. Most frameworks behave OK, but they all have their quirks. The quirks would need to be ironed out by confining the quirky part to the backend, defining a function there with the correct name, and importing it.

The numpy conventions seem like a good set of rules to adhere to, because all frameworks report back to cpu with numpy arrays. Also this NEP will come in handy https://www.numpy.org/neps/nep-0018-array-function-protocol.html but only in the future

> I don't quite follow. If the wrong format is received, should it raise an error or convert? Those are two very different scenarios. Should it convert only in certain circumstances?

I am imagining a function `check_array(array, backend='pytorch', device='cpu', maybe_other_stuff=None, cast_backend=False, cast_device=False)`. If `cast_...` is set to `True`, and `array` is not of the right type, then it converts, otherwise it raises an error. Improvable, and details to be worked out.

> Which brings up the point of timing. It seems like a lot of the previous issues should be addressed before moving on to this, but some more careful planning is needed here.

Yes, I think this is delicate but there can be a high payoff. Some of the previous issues might inform this procedure. So yeah, I think the other things need to be addressed first.

**Comment by edouardoyallon** [comment]
Closed by #415
