### ISSUE TITLE
ENH+TST find a way of testing GPU code

### ISSUE THREAD

**Issue by eickenberg** [kymatio/kymatio#267]
With not too much investment in 💲 💰  it should be possible to set up a `jenkins` testing suite on amazon aws: The idea is to have a micro machine that costs 1c/h run the jenkins server. When tests should be run, this should somehow spawn a couple of GPU machines with different GPUs, ideally as spot instances, run the tests and then shut them down again.
I looked into this at the very beginning of `kymatio`, but I don't really know how to set this up yet. If anybody has experience with this, feel free to try! :)

**Comment by janden** [comment]
Is there not some way to do this locally? We all have access to GPUs. It would be infinitely cheaper!

**Comment by eickenberg** [comment]
Definitely -- `jenkins` can be set up anywhere

**Comment by janden** [comment]
Ok. I know people have used that here. Will ask.

**Comment by edouardoyallon** [comment]
Do we have some fundings for this? @janden @eugenium @eickenberg @louity

**Comment by janden** [comment]
Haven't had time to look into this yet.
