### ISSUE TITLE
ENH output structure/coefficient ordering

### ISSUE THREAD

**Issue by eickenberg** [kymatio/kymatio#268]
Some different conceivable output shapes for e.g. 2D are

- `(B, everything, h, w)` - this is good for using scattering as a feature extractor for feeding into deep nets
- `(B, J1, L1, h, w) + (B, J1J2mess, L1, L2, h, w)` (could be views on a contiguous array) - good for having a handle on what is what coefficient

There are two questions:
1. How is the output organized in memory
     - we can interleave order 1 and 2
     - we can not interleave order 1 and 2
           (a) we can have J1 move with bigger strides (have it more on the left, more intuitive ordering)
           (b) we can have J2 move with bigger strides (J2 determines output size, better grouping)

2. How is the output presented to the user
    - raw arrays
    - dictionaries indexing relevant subarrays with tuples as keys (this makes dictionary indexing look like array indexing)

There are probably others. This issue is for gathering, and then deciding what is useful to have across all dimensionalities.

**Comment by lostanlen** [comment]
Yes. In a broader sense, there is a question of stability of the output with respect to custom parameters of Kymatio, either at "compile time" (Kymatio constructor) or "run time" (forward of the network).
The different levels of stability are:
1. same sizes, different values
2. same number of dimensions, different sizes
3. same Tensor type, different number of dimensions
4. different return type, same number of output arguments
5. different number of outputs arguments

In my opinion, option (1) is too restrictive for our purposes, and option (5) will create a lot of confusion on the part of the user. So we're more near options (3) or (4).

**Comment by edouardoyallon** [comment]
I think (3) is great, and if:
(B1,B2,..,Bk,M,N) is a batch of size (B1,...,Bk) with images of size (M,N), then I believe it should return a tensor of size:
(B1,B2,...,Bk,J1J2mess,M,N)

Do you agree? How should we input the order of J1J2mess? I think it would be worth to fix this.

**Comment by edouardoyallon** [comment]
So I think given the dict option, this issue can be considered as solved!
