### ISSUE TITLE
ENH scikit-learn-compatible transformer

### ISSUE THREAD

**Issue by eickenberg** [kymatio/kymatio#277]
Add a mixin or wrapper that can use the scattering transform in the context of sklearn:

- Instantiate transformer with image shape
- images are provided as `X`, probably raveled, `X.shape = n_samples, n_features`
- output is also raveled, so that it can go to the next part of a pipeline

**Comment by edouardoyallon** [comment]
Hi. I'm new w.r.t. sk-learn. Can you provide an example? (url, sphynx, ..)
Thanks!

**Comment by edouardoyallon** [comment]
This was merged and added!
