### ISSUE TITLE
Visualization of Scattering Coefficients

### ISSUE THREAD

**Issue by Jonas1312** [kymatio/kymatio#282]
Hi,

First I would like to thank you for the work you have done on Kymatio, really helpful 👍

I would like to visualize scattering coefficients like that for example (first and second orders):
![capture](https://user-images.githubusercontent.com/15847892/50734540-e96a2d00-11a0-11e9-9364-2ee9c6fff56d.JPG)

Do you know if there is an easy way to do that with Kymatio Scattering2D output?

Thank you!

**Comment by lostanlen** [comment]
Dear Jonas,
Thank you for your interest in Kymatio.
The short answer is no: there is no built-in function in Kymatio which allows to replicate subfigures (c) and (d) from the figure above. This figure was done with the MATLAB library ScatNet. Although the development of ScatNet has now been discontinued, you can still use it if all you need is the visualization.
That said, I will personally add that I don't find subfigure (d) particularly intuitive or helpful to understand scattering transform. Various second-order orientations (theta_2) and second-order scales (j2) are arranged within small angular sections of the circle, if they happen to have the same theta1 and j1. This arrangement does not reflect the contiguity in theta_2 nor j_2. At the end of the day, displaying seond-order coefficients while respecting contiguity cannot be done in dimension 2. There needs to be a projection somewhere.
Therefore, I don't see the implementaion of this mode of visualization as a priority in Kymatio. But perhaps other Kymationauts will think otherwise.

**Comment by edouardoyallon** [comment]
Hi Jonas, Vincent,
I agree with Vincent that the priority is not to develop this feature and that this type of visualization has to intrinsic issues, however, I'm not against adding it in a future release. Feel free to propose a PR, my guess is that we'd be happy to add it to a next release, in order to be consistent with formers papers! What do you think @joanbruna?

**Comment by eugenium** [comment]
Just to chime in, forgetting the visualizations with theta2 an j, I think just having some simple utility that automatically extracts the first and second order coefficients in a structured way from the current monolithic output would go along way.  It should be quite simple for someone after to make a visualization like that.

**Comment by Jonas1312** [comment]
Thanks for your answers 👍

I will try to write a script that generates this type of visualization from Kymatio computed coefficients when I have some time. But as @eugenium said it would be really useful to have another structured way to retrieve coefficients from Scattering2D (same issue #268)

**Comment by lostanlen** [comment]
@Jonas1312 sounds good, do keep us posted about that! I would advise to make a separate repository for this visualization. Although it's true that Kymatio 0.1-beta does not output coefficients in a structured way but in a "raveled" (1D) way, it should be relatively easy for you to reverse-engineer that raveling process, and come up with a (theta1, j1, theta2, j2) tuple for every index in the feature vector. Once you've done that, you can use matplotlib to make the polar plot in the fashion of the Bruna and Mallat paper.

**Comment by Jonas1312** [comment]
@lostanlen Yes of course I still plan to do that!
But I'm struggling with #284 even if I pad the input image manually... I haven't had time to solve this problem yet so I'll wait until this bug is fixed

**Comment by Jonas1312** [comment]
I have almost finished the script https://gist.github.com/d897f9c7a5d4c7c857456588089e4ed2
For now the generated visualization doesn't seem to match the one from the paper:

Output from ScatNet:
![capture](https://user-images.githubusercontent.com/15847892/51798759-1cd82e80-2218-11e9-858f-a128eb8a0b13.JPG)
From my script (same input image taken from the paper with a screenshot, resized to 32x32 pixels):
![figure_1](https://user-images.githubusercontent.com/15847892/51798784-2b264a80-2218-11e9-8043-21da1bc0c018.png)

I think the disks' positions in the subplots are ok but the angles are not aligned properly. The `height` parameter in `ax.bar` is also wrong I think. Still not working if `2**J == image_size`.

**Comment by edouardoyallon** [comment]
hi @Jonas1312 , thanks a lot. Do you think it's possible that you include this script as an example in: https://github.com/kymatio/kymatio/tree/master/examples/2d

You will need to follow the guidelines of https://github.com/kymatio/kymatio#building-the-documentation-from-source to compile the documentation (that basically creates html pages), and try to make the presentation of it pretty.

Thanks again!!

**Comment by Jonas1312** [comment]
Sorry for closing and reopening, bad move 🙇

I'll write a pull request when I have time, but right know the code is not finished I think there are few things to fix. As written in my comment above, with the same input image the generated visualization is not exactly the same as the one in the paper.

If we want the exact same visualization I'm going to need the original scatnet script otherwise it might be complicated to guess the exact parameters

**Comment by edouardoyallon** [comment]
The following code, from http://www.cmap.polytechnique.fr/scattering/code/scattering_v2.tgz seems to generate this figure.

```
%%%%%script to generate figure 5 from the paper 'Invariant Scattering Convolution Networks'
%%%%%feb 2012%%%%%%%
%%%%%%Joan Bruna and Stephane Mallat$$$$$$$$$


%%%%%This figure shows two textures with the same power spectrum
%%%%%but different scattering representation. The second texture
%%%%% is a Gaussian process with the power spectrum estimated from 
%%%%%% the first texture.


close all;

options.J=7;
options.wavelet_family='spline';
options.renorm_study=1;
options.M=2;

if 1

%read from Brodatz dataset
[texture]=retrieve_brodatz_data(8,40);
t1=8;
f=texture{t1}{1};

Nim=256;
T=size(texture{t1},2);
T=min(T,6);
Tbis=T;
Tequ=16;

%estimate the power spectrum over the different realisations of the 
%texture
PS1=zeros(Nim);
SC1=[];
for t=1:T
texturec{t1}{t}=crop(texture{t1}{t},Nim,128);
texturec{t1}{t}=texturec{t1}{t}-mean(texturec{t1}{t}(:));
texturec{t1}{t}=texturec{t1}{t}/norm(texturec{t1}{t}(:));
PS1 = PS1 + abs(fft2(texturec{t1}{t}).^2);
t
end
PS1 = PS1 / T;

%power spectrum equalisation
SC3=[];
PS3=zeros(Nim);
eqfilter= sqrt(PS1);
for t=1:Tbis
	[res,met]=scatt((texturec{t1}{t}),options);
	SC1 = [SC1; met.ave];
end
for t=1:Tequ
	%equalized texture
	temp = ifft2(fft2(randn(Nim)).*eqfilter);
	temp=temp-mean(temp(:));
	temp=temp/norm(temp(:));
	PS3 = PS3 + abs(fft2(temp).^2);
	[res,met]=scatt(temp,options);
	SC3=[SC3; met.ave];
end

PS3 = PS3 / Tbis;
if Tbis>1
SC1r = SC1(1,:);
SC1 = mean(SC1);
end
if Tequ >1
SC3var = var(SC3,1);
SC3 = mean(SC3);
end

geq=(ifft2(fft2(randn(Nim)).*eqfilter));

end

%compute scattering displays
copts.renorm_process=0;
[SCA1]=fulldisplay2d(SC1,met,copts);
[SCA3]=fulldisplay2d(SC3,met,copts);


%compute distances

ord1=find(met.order==2);
difer=SC1r(ord1)-SC3(ord1);
ratio1=sum(difer.^2)/(sum(SC3var(ord1)))

ord2=find(met.order==3);
difer=SC1r(ord2)-SC3(ord2);
ratio2=sum(difer.^2)/(sum(SC3var(ord2)))

att1=1.1;
att2=1;

%display results
normvalues(1)=att1*max(max(SCA1{1}(:)),max(SCA3{1}(:)));
normvalues(2)=att2*max(max(SCA1{2}(:)),max(SCA3{2}(:)));
show_two_spectra_dlux(f,SCA1,.5,normvalues);
show_two_spectra_dlux(geq,SCA3,.5,normvalues);
```

Do you think you can fix it and propose a PR? Thanks!

**Comment by edouardoyallon** [comment]
What's exactly different? @joanbruna any opinion?

**Comment by Jonas1312** [comment]
Hi, sorry for late answer I'm quite busy.

> 
> 
> I have almost finished the script https://gist.github.com/d897f9c7a5d4c7c857456588089e4ed2
> For now the generated visualization doesn't seem to match the one from the paper:
> 
> Output from ScatNet:
> ![capture](https://user-images.githubusercontent.com/15847892/51798759-1cd82e80-2218-11e9-858f-a128eb8a0b13.JPG)
> From my script (same input image taken from the paper with a screenshot, resized to 32x32 pixels):
> ![figure_1](https://user-images.githubusercontent.com/15847892/51798784-2b264a80-2218-11e9-8043-21da1bc0c018.png)
> 
> I think the disks' positions in the subplots are ok but the angles are not aligned properly. The `height` parameter in `ax.bar` is also wrong I think. Still not working if `2**J == image_size`.

As shown in the previous comment, the generated visualization does not perfectly match the figure 7 of the paper (with the same input image).

Moreover, each sector must approximates the frequency support of the corresponding wavelet:
![capture](https://user-images.githubusercontent.com/15847892/53679875-18011180-3cd3-11e9-8429-25b661e1d9af.JPG)
which is not implemented yet in my script.

I tried to run the matlab script you sent me @edouardoyallon but it's buggy, it doesn't help much.

**Comment by edouardoyallon** [comment]
Hi,

> Hi, sorry for late answer I'm quite busy.

No worries. Going to handle this PR. I'd really appreciate if you could review it when it'll be ready.

**Comment by edouardoyallon** [comment]
If someone sees something to add to the TODO... otherwhise this is what I'll fix before to push
