### ISSUE TITLE
TST `backward` for complex modulus is not tested

### ISSUE THREAD

**Issue by janden** [kymatio/kymatio#300]
Specifically, codecov reports that [lines 90-105](https://github.com/kymatio/kymatio/blob/master/kymatio/scattering1d/backend/backend_torch.py#L90) of `backend_torch.py` are [never executed](https://codecov.io/gh/kymatio/kymatio/src/master/kymatio/scattering1d/backend/backend_torch.py#L90). This is odd because we specifically test the `backward` function in the [corresponding test](https://github.com/kymatio/kymatio/blob/master/kymatio/scattering1d/tests/test_utils.py#L87). Somehow, torch must be bypassing our code.

**Comment by janden** [comment]
Summary of discussion from #355:

It turns out `pytest` does run the code. If you put an `assert(False)` in there, it crashes. For some reason, `pytest-cov` isn't registering these lines.

**Comment by janden** [comment]
Here's a minimal example:
```
import torch

class MyReLU(torch.autograd.Function):
    @staticmethod
    def forward(ctx, input):
        ctx.save_for_backward(input)
        return input.clamp(min=0)

    @staticmethod
    def backward(ctx, grad_output):
        input, = ctx.saved_tensors
        grad_input = grad_output.clone()
        grad_input[input < 0] = 0
        return grad_input

def test_relu():
    relu = MyReLU.apply

    x = torch.randn((1, ), requires_grad=True)

    y = relu(x)

    y.backward()
```

If you run `pytest --cov --cov-report=term-missing` on this, it'll report the lines in `backward` as misses, even though they are executed.

**Comment by janden** [comment]
So it's not a matter of `pytest-cov` plugin to `pytest`, but in the underlying `coverage.py` package. Running `coverage run pytest` followed by `coverage report` gives the same result.

What could be happening is that the `y.backward()` call eventually disappears into a C extension (see [here](https://github.com/pytorch/pytorch/blob/80927fc068548bd3fd4621c79b9475439d751f3e/torch/autograd/__init__.py#L91)), which `coverage` may have trouble following.

**Comment by janden** [comment]
Looks like `coverage` uses [`sys.settrace`](https://docs.python.org/3/library/sys.html#sys.settrace) internally (see [here](https://coverage.readthedocs.io/en/latest/howitworks.html)). Seems like `sys.settrace` doesn't see what happens after we go into the C extension. Indeed, if we have the following code
```
import sys
import torch

class MyReLU(torch.autograd.Function):
    @staticmethod
    def forward(ctx, input):
        ctx.save_for_backward(input)
        return input.clamp(min=0)

    @staticmethod
    def backward(ctx, grad_output):
        input, = ctx.saved_tensors
        grad_input = grad_output.clone()
        grad_input[input < 0] = 0
        return grad_input

def tracefunc(frame, event, arg):
    print('%s, %s, %s' % (frame, event, arg))
    return tracefunc

if __name__ == '__main__':
    relu = MyReLU.apply

    x = torch.randn((1, ), requires_grad=True)
    y = relu(x)

    sys.settrace(tracefunc)
    y.backward()
    sys.settrace(None)
```
and just run it (no `pytest`, no `coverage`), we get printouts for every line inside PyTorch until the C extension is invoked, then nothing.

**Comment by edouardoyallon** [comment]
alright, is it a known issue? if yes, we can't do much about it..

**Comment by janden** [comment]
> alright, is it a known issue? if yes, we can't do much about it..

I would think so, but would have to dig a little more/check with the `coverage` people.

One workaround is to "simulate" the PyTorch autograd algorithm by calling `forward` and `backward` ourselves. The other way is to add some pragmas to those lines to have `coverage` ignore them.

**Comment by edouardoyallon** [comment]
let's call them explicitely, it's the safer, as the error could be still catched

**Comment by janden** [comment]
Agreed. Will look into this.
