### ISSUE TITLE
BUG scattering3d_qm7.py

### ISSUE THREAD

**Issue by nshervt** [kymatio/kymatio#303]
It seems that line 180 should be modified as follows:
Current:
order_0, order_1, order_2 = [], [], []
Should be:
order_0, orders_1_and_2 = [], []

**Comment by lostanlen** [comment]
Upon checking, you are right:
https://github.com/kymatio/kymatio/blob/master/examples/3d/scattering3d_qm7.py#L180

Could you please open a PR?

**Comment by nshervt** [comment]
Done.
