### ISSUE TITLE
Python 2.7 compatibility?

### ISSUE THREAD

**Issue by janden** [kymatio/kymatio#318]
This is something that may simplify adoption in certain environments. Obviously, making this work is not a trivial amount of effort, so we need to have a discussion on the pros and cons.

**Comment by janden** [comment]
Continuation of discussion in #317.

**Comment by f0k** [comment]
> Obviously, making this work is not a trivial amount of effort

Do we know more about this? `setup.py` uses some Python3-specific features, but 2d scattering should work with `from __future__ import division` in `filter_bank.py`.

**Comment by janden** [comment]
Well that and `print` statements, but that should be a similar import. Otherwise, I don't know that we're using much in the way of 3.X features, you're right.

I think the larger question is future plans and whether this will hamper flexibility in implementing them. But, as you mention, there's no reason we can't drop 2.7 support if it comes to that.

**Comment by f0k** [comment]
> that should be a similar import

Indeed, it's `from future import print_function`.

> I think the larger question is future plans and whether this will hamper flexibility in implementing them. But, as you mention, there's no reason we can't drop 2.7 support if it comes to that.

If there are immediate plans that will require dropping 2.7 support, then we shouldn't invest on enabling it. Otherwise it wouldn't hurt.

I'm still familiar with Python 2/3 idioms, I can take care of that, so the main obstacle seems to be the current solution for version parsing in `setup.py`. We can use `imp` for Python 2, or just parse it as a key-value text file. And then there might be some fun ahead with `unicode` vs `bytes` vs `str`.

**Comment by lostanlen** [comment]
my 2c is that supporting py2.7 is overzealous. 2019 is precisely the year where numpy has stopped supporting py27 in minor releases (new features), and 2020 will be the one in which numpy will stop attending bugs in py27-compatible code

**Comment by janden** [comment]
On the one hand, if it's not too much work, why not? On the other, do we want to spend any time supporting technology that is supposed to be EOL right about now?

I guess it comes down to what fraction of the potential userbase is still 2.7-only? Any estimates here?

**Comment by edouardoyallon** [comment]
I'm against being py27 compatible thanks to the argument of vincent! If numpy doesn't, I don't think we should, even if it has no cost! I think this issue could be closed.

**Comment by f0k** [comment]
I don't have a strong opinion on this. Python 2.7 will be around for a while even if numpy stops fixing 2.7-related bugs in 2020, but more and more research code uses Python 3.

**Comment by janden** [comment]
As of October, 2018, we're talking 16% according to the PSF survey:

https://www.jetbrains.com/research/python-developers-survey-2018/#pyversions_2

In "Data Science", that drops to 10%. I suggest we stay with py35 and close this issue.
