### ISSUE TITLE
Non-Anaconda testing

### ISSUE THREAD

**Issue by janden** [kymatio/kymatio#319]
Currently, all CI scripts run through Anaconda. Given that this is not the only way to run Kymatio (supposedly), should we test in other environments as well (i.e., `pip`)?

**Comment by janden** [comment]
For what it's worth, I'm able to get it running using `pipenv`:
```
pipenv --three
pipenv install torch torchvision pytest
pipenv install
pipenv run pytest kymatio
```
Do we think this makes enough of a difference for testing purposes to add another CI script?

**Comment by edouardoyallon** [comment]
I think it is worth to add. Can you add it?
Thanks!
Edouard
