### ISSUE TITLE
REF Create 2D filterbank in spectral domain

### ISSUE THREAD

**Issue by f0k** [kymatio/kymatio#322]
The 2D Morlet/Gabor filterbank is currently created in the spatial domain and transformed to the spectral domain afterwards. It would be cleaner to construct it in the spectral domain from the start (also to ensure that the imaginary part is really zero).

**Comment by edouardoyallon** [comment]
So: I think this is a great idea yet rather difficult due to some border effects...

**Comment by edouardoyallon** [comment]
@janden https://github.com/scatnet/scatnet/blob/master/filters/morlet_filter_bank_2d.m#L113

It's done in space! Some issues that come to my mind: the filters do not really vanishes for high frequencies; periodization issues for lower resolution(higher scales)

**Comment by janden** [comment]
Huh.. Ok so maybe just forcing the imaginary part to zero is the way to go then?

**Comment by f0k** [comment]
Ah, interesting, so scatnet already dropped the real part in the line that you mentioned. (Side note: It's risky to refer to line numbers in `master`, in general it's better to replace `master` with the first 7 characters of the commit id so the conversation still makes sense later.)

> So: I think this is a great idea yet rather difficult due to some border effects...

Ok... shall we still leave this up for future work or close it because nobody will ever do it?

**Comment by lostanlen** [comment]
@f0k we need to evaluate what will be the benefits of this before diving in. And then think of an API to act upon it.

FWIW here is the inheritance pattern I had designed in `WaveletScattering.jl` (Julia code)

**GROUPS**
```julia
"""Three variables come into play in a wavelet filterbank:
* the spatial variable `V`, which may be multi-dimensional ;
* the scale variable `γ::V`, which is one-dimensional and non-negative ;
* the isometric variable `θ::V`, which belongs to a ""point group"".
A point group is an algebraic group of transformations which have a single
fixed point. Reflections of the real line and rotations of the plane are
examples of such point groups.
Conversely, translations and scalings are not point groups.
"""
abstract AbstractPointGroup

"""The `TrivialGroup` is a finite group of a single neutral element."""
struct TrivialGroup <: AbstractPointGroup end

"""The `ReflectionGroup` is a finite group of two elements, which represents
the reflections of the real line."""
struct ReflectionGroup <: AbstractPointGroup end

"""The `RotationGroup` is a continuous group, which represents the rotations of
the plane. Its orientations are discretized uniformly."""
struct RotationGroup <: AbstractPointGroup
    n_orientations::Int
end
```

**DOMAINS**
```
"""There are two subtypes of `AbstractDomain`:
* `FourierDomain{K}`: filtering is implemented as a product in the Fourier
domain. `K` is the dimension of the Fourier transform.
* `SpatialDomain{K}`: filtering is implemented as a convolution in the spatial
domain, or as a wavelet lifting scheme when it is possible. `K` is the number of
subscripts over which the convolution operates.
"""
abstract type AbstractDomain

struct FourierDomain{K} <: AbstractDomain
    dim::Val{K}
    function FourierDomain{K}(dim::Val{K})
        @assert (K > 0)
        @assert isa(K, Int)
        new(dim)
    end
end
FourierDomain(dim::Int) = FourierDomain{dim}(Val{dim}())


struct SpatialDomain{K} <: AbstractDomain
    dim::Val{K}
    function SpatialDomain{K}(dim::Val{K})
        @assert (K > 0)
        @assert isa(K, Int)
        new(dim)
    end
end
SpatialDomain(dim::Int) = SpatialDomain{dim}(Val{dim}())

const LineDomains = Union{FourierDomain{1},SpatialDomain{1}}
const PlaneDomains = Union{FourierDomain{2},SpatialDomain{2}}
```

**WAVELET CLASSES**
```
abstract type RedundantWaveletClass

struct Gammatone <: RedundantWaveletClass
    order::Int
end
Gammatone() = Gammatone(4)
isdyadic(::Gammatone) = false
issteerable(::Gammatone) = true

struct MexicanHat <: RedundantWaveletClass end
isdyadic(::MexicanHat) = true
issteerable(::MexicanHat) = false

struct Morlet <: RedundantWaveletClass end
isdyadic(::Morlet) = false
issteerable(::Morlet) = true
```


**FILTER BANK SPECIFICATIONS** (immutable)
```
struct Spec2D{T<:Real,D<:PlaneDomains,
        G<:PlaneGroups,W<:RedundantWaveletClass} <: AbstractSpec{T,D,G,W}
    ɛ::Float64
    ϕmeta::ΦMeta
    ψmetas::Array{ΨMeta2D,3}
    class::W
    domain::D
    log2_size::Int
    max_aspectratio::Float64
    max_qualityfactor::Float64
    max_scale::Float64
    motherfrequency::Float64
    n_filters_per_octave::Int
    n_octaves::Int
    pointgroup::G
    signaltype::Type{T}
end
```

**FILTER BANK BEHAVIORS** (mutable)
```
mutable struct Behavior{T<:Real}
    ϕ_log2_sampling::Int
    ψ_log2_samplings::Vector{Int}
    is_ϕ_applied::Bool
    j_range::UnitRange
    log2_oversampling::Int
    max_log2_stride::Int
    pathkey::PathKey
    weighting::AbstractWeighting
    weights::Array{T, 3}
end
```

**FILTER BANKS**
```
abstract type AbstractBank{
    T<:Number,
    D<:AbstractDomain,
    G<:AbstractPointGroup,
    W<:RedundantWaveletClass}

struct Bank2D{
        T<:Number,
        D<:PlaneDomains,
        G<:PlaneGroups,
        W<:RedundantWaveletClass} <: AbstractBank{T,D,G,W}
    ϕ::AbstractFilter{T,D}
    ψs::Array{AbstractFilter{T,D},3}
    behavior::Behavior{T}
    spec::Spec2D{T,D,G,W}
end
```

**Comment by eickenberg** [comment]
fyi for 3d creating filters in spectral domain is already implemented and used

https://github.com/kymatio/kymatio/blob/master/kymatio/scattering3d/filter_bank.py#L155

and this is even for filters that are inherently complex, also in fourier space

**Comment by edouardoyallon** [comment]
> fyi for 3d creating filters in spectral domain is already implemented and used
> 
> https://github.com/kymatio/kymatio/blob/master/kymatio/scattering3d/filter_bank.py#L155
> 
> and this is even for filters that are inherently complex, also in fourier space

AFAIR, there is no boundary issues because the convolutions are periodic, am I correct?

**Comment by eickenberg** [comment]
> AFAIR, there is no boundary issues because the convolutions are periodic, am I correct?

There would be interesting settings in which this is true, but the work that this transform was created for does not work with periodic signals/convolutions. We pad a lot

**Comment by edouardoyallon** [comment]
I think it can be closed... let's focus on creating more filters!
