### ISSUE TITLE
Test for raised errors in torch backend

### ISSUE THREAD

**Issue by janden** [kymatio/kymatio#334]
Specifically, `fft` and `cdgmm` may raise `TypeError`s or `RuntimeError`s which are currently not tested. For example, see [here](https://codecov.io/gh/kymatio/kymatio/src/6e5c430d71a1562a93931eee0f568a9aba489220/kymatio/scattering2d/backend/backend_torch.py#L139).

**Comment by edouardoyallon** [comment]
I'd be happy to raise them if you explain me how to do or give me a snapshot of code!

**Comment by janden** [comment]
The key methods are `pytest.raises` and `pytest.warns`. They're context managers that catch errors and warnings in the executed code. Some docs are [here](https://docs.pytest.org/en/latest/assert.html). An example of how this is done in the 1D code is found in bd5bc8e98af4f027e371f4918c43ab1aa5a6614b.

**Comment by edouardoyallon** [comment]
Thanks, I'll come with a PR asap

**Comment by janden** [comment]
Ok. Thank you!
