### ISSUE TITLE
ENH warning when making doc

### ISSUE THREAD

**Issue by edouardoyallon** [kymatio/kymatio#347]
fresh clone + cd doc + make html leads to:

"WARNING: could not relabel citation reference [paper]"

I'm not sure what's the issue.

**Comment by janden** [comment]
I think this one is my fault. It appeared when I put in the new paper citation. Will look into it.

**Comment by janden** [comment]
Looks like this is related to https://github.com/mcmtroffaes/sphinxcontrib-bibtex/issues/141.
