### ISSUE TITLE
`to` function

### ISSUE THREAD

**Issue by janden** [kymatio/kymatio#351]
TODO (edited by EO):

- [x] method `.to()` for 1D
- [x] method `.to()` for 2D
- [x] method `.to()` for 3D

PyTorch tensors have a `to` function (see https://pytorch.org/docs/stable/tensors.html#torch.Tensor.to), which combines datatype conversion and device copy (i.e., `cpu()` and `cuda()` functions). It might be good to have something similar on our end. This would, for example, simplify device-agnostic code that could simply call
```
scattering.to(x.device)
Sx = scattering(x)
```
instead of
```
if x.is_cuda:
    scattering.cuda()
else:
    scattering.cpu()
Sx = scattering(x)
```
It would also simplify our test suite which is full of such if statements.

A (slightly) related question is how to handle multiple GPUs. Right now, we're restricted to the current GPU as defined by PyTorch.

Finally, all of this needs to be considered with our goal of backend agnosticism in mind. We don't want to commit to hard to the PyTorch infrastructure. Still, I think there could be a way to do this in an appropriate manner.

**Comment by edouardoyallon** [comment]
I did a script
https://github.com/edouardoyallon/pyscatlight/blob/master/classification/main_scatMultiGPU.py#L28-L50

(I got also some for different backends like https://github.com/edouardoyallon/pyscatlight/blob/master/classification/main_scatDistributed.py )

So imho, one should design a function in backend that we call like

```from backend import multigpuscat
```
and we'll do like

```scat=multigpuscat(scat)
```
to let the module use all the visible GPUs.

What do you think?
