### ISSUE TITLE
`cdgmm` doesn't check that both inputs are on the same device

### ISSUE THREAD

**Issue by janden** [kymatio/kymatio#357]
This is at least true for the 2D torch `cdgmm`. It only complains when you try to multiply tensors. We should throw an error instead.

**Comment by janden** [comment]
This seems to be the case for all the other `cdgmm`s as well.

**Comment by edouardoyallon** [comment]
For this specific case, as this routine is common between 1-2-3D, this could be done jointly with #261?

**Comment by janden** [comment]
I think we should do #261 first, then this one. Will be easier that way. Might make sense to do them in the same PR, though.
