### ISSUE TITLE
Include examples in test suite

### ISSUE THREAD

**Issue by janden** [kymatio/kymatio#362]
We've had these break several times, but we don't know about it since these are not tested as part of the CI. They should be tested in some way to make sure everything runs, at least prior to a release.

The biggest issue here is the 3D example, which takes several hours to finish, even on a GPU. Perhaps there is some way of simplifying it?

**Comment by edouardoyallon** [comment]
Well, would be ok to test them, but then is it possible to test them less often than the kymatio?
Similarly, I was wondering if we shouldn't move: 
https://github.com/kymatio/kymatio/blob/master/kymatio/datasets.py

and how to test:
https://github.com/kymatio/kymatio/blob/master/kymatio/caching.py

**Comment by janden** [comment]
> Well, would be ok to test them, but then is it possible to test them less often than the kymatio?

We could do a nightly/weekly test. This doesn't solve the underlying issue of having extremely time-consuming examples. Is this at all desirable?

**Comment by edouardoyallon** [comment]
Related #369

**Comment by edouardoyallon** [comment]
Close via #416
