### ISSUE TITLE
scattering(x) vs scattering.forward(x)

### ISSUE THREAD

**Issue by nshervt** [kymatio/kymatio#367]
It seems that both the following codes 

```
scattering = Scattering2D(J, shape=(M, N))
scattering.forward(x)
```

and 

```
scattering = Scattering2D(J, shape=(M, N))
scattering(x)
```

have the same output, of the same type. Is there any differences between them or any place that one might work better then the other?

**Comment by eugenium** [comment]
It's the same, it follows the nn.Module API of pytorch
