### ISSUE TITLE
python 3.6 required for pip install

### ISSUE THREAD

**Issue by JonathanVacher** [kymatio/kymatio#371]
Hi,

pip install is not working because it requires python 3.6 as indicated here: https://pypi.org/project/kymatio/

Kymatio is supposed to work with python 3.5 as indicated by the logo on the website: https://www.kymat.io/index.html

Thanks,

**Comment by lostanlen** [comment]
Ah yes, i think that this is because we were excited about PEP 498 on literal string interpolation, but did not reflected it in the badges.
https://www.python.org/dev/peps/pep-0498/

What do you think @eickenberg ?

**Comment by eickenberg** [comment]
Wait, where does it break?
We had started out supporting only 3.6 (though it worked in 3.5) and
explicitly added official 3.5 support because people were asking for it.
Aren't we then also testing with 3.5 and our tests pass?

**Comment by JonathanVacher** [comment]
No idea. This is what I get when running pip install:
![kymatio](https://user-images.githubusercontent.com/6490783/54946134-ccc2d300-4f0d-11e9-8ff4-bcdb1ee00c19.png)

**Comment by lostanlen** [comment]
It does not break in Python, it breaks in pip install, because the PyPI page does not list Python 3.5
https://pypi.org/project/kymatio/

**Comment by eickenberg** [comment]
Got it. Will fix

**Comment by edouardoyallon** [comment]
@eickenberg status?

**Comment by wmking** [comment]
Hi Guys, has this not been fixed? Running Python 3.5.3

pip3 install kymatio 

produces error listed in this issue.

**Comment by edouardoyallon** [comment]
Hi, I agree.. I don't have the pypi's password to fix that. It's a bit annoying.. @eickenberg @eickenberg

**Comment by lostanlen** [comment]
@wmking if you insist on Python 3.5, my recommendation is to install from source

**Comment by wmking** [comment]
> @wmking if you insist on Python 3.5, my recommendation is to install from source

Thank you lostanlen, this worked.

**Comment by edouardoyallon** [comment]
This should be fixed
