### ISSUE TITLE
Hello, I have a question about inverse

### ISSUE THREAD

**Issue by strawberry1996** [kymatio/kymatio#373]
I reading your code about scatter inverse, and I train the model use your way, but I don't know, how can I test the model?  for instance, when I scattering, I set L =8, J=2 then I get 17 feature images, What should I input when I invert? Is it 17 scattering images?

**Comment by edouardoyallon** [comment]
I'll add soon a PR with an example of scattering inversion via gradient descent.

**Comment by Jonas1312** [comment]
Not sure if it's what you're looking for but maybe this can help you: [https://github.com/Jonas1312/scattering-networks/blob/master/Python/image_reconstruction/main.py](https://github.com/Jonas1312/scattering-networks/blob/master/Python/image_reconstruction/main.py)

**Comment by edouardoyallon** [comment]
Hi, thanks a lot! Maybe you could do a PR?
