### ISSUE TITLE
Accessing coefficients layer wise

### ISSUE THREAD

**Issue by arshdefoamed** [kymatio/kymatio#376]
I am trying to compare the energy of the signal at different levels of the scattering response. However, I have trouble pointing out which index value corresponds to which level?
Please refer to the code below taken from MNIST classification:

```python
import torch.nn as nn
import torch.optim
from torchvision import datasets, transforms
import torch.nn.functional as F
from kymatio import Scattering2D
import kymatio.datasets as scattering_datasets
import numpy as np 
myDataSet = datasets.MNIST(scattering_datasets.get_dataset_dir('MNIST'),train=True, download=True,transform=transforms.Compose([ transforms.ToTensor()]))
train_loader = torch.utils.data.DataLoader(myDataSet,shuffle=True,batch_size=1)
dataiter = iter(train_loader)
images, labels = dataiter.next()
scattering = Scattering2D(J=2, shape=(28, 28),max_order=2,L=8)
val = scattering.forward(images)
scatterImage = val.detach().numpy()
print(scatterImage.shape)
```
This gives the scatterinf response (1, 1, 81,7,7). However, I am not sure which index corresponds to which level.

Also, I would like to apply SVM to scattering response but am not sure how to handle the data point with dimensions (81,7,7) for each datapoint. Can someone point me in the right direction ?

**Comment by edouardoyallon** [comment]
Hi, this is a good point. 
- We should return a meta with the scattering coefficients!
- Just reshape the 3D tensor 81x7x7 to a vector.

**Comment by edouardoyallon** [comment]
With the
