### ISSUE TITLE
Adding phi_f information in meta

### ISSUE THREAD

**Issue by ghost** [kymatio/kymatio#378]
Hello everyone,

`meta()` is actually only returning center frequencies and bandwiths of psiN_fs. 
Should it also contain information about phi_f ? 

I think it could be useful since users will only need to call `meta()` to get all the frequency-related information.

It will be a minor modification by just adding `phi_f["xi"]` and `phi_f["sigma"]`  ( or `0.0` and `2^-J` ) in the first rows of `meta["xi"]` and `meta["sigma"]`.

**Comment by lostanlen** [comment]
Hello @gdestouet. This is a good idea

**Comment by edouardoyallon** [comment]
Thanks a lot for reporting this. This is a good catch, but now, we removed the meta which is directly in the dictionary of features, cf: https://github.com/kymatio/kymatio/blob/0.2.X/kymatio/scattering2d/core/scattering2d.py#L48-L50 can we consider this issue is address? @janden

**Comment by janden** [comment]
> can we consider this issue is address?

Unfortunately, no. We still don't provide any information about the lowpass filter φ. It could be an additional piece of data in the dict output, I agree, but we don't do that currently.

**Comment by lostanlen** [comment]
this issue interacts with the T vs J idea in 1D. Tagging @janden and @pawarrick

**Comment by lostanlen** [comment]
I'm reading this again and it's becoming difficult due to things like `average='global'` and phi/psi pairs in JTFS

**Comment by lostanlen** [comment]
i don't think it's worth doing. The sigma is very easy to read from `S.phi_f` if needed.
But adding it to the meta is going to cause all sorts of corner cases such as `average='global'` and phi/psi pairs in JTFS. And similarly for frequency averaging.
