### ISSUE TITLE
Unexpected crush with J=1 

### ISSUE THREAD

**Issue by dminskiy** [kymatio/kymatio#379]
Hi, 

I faced the following problem: I get unexpected and unexplained crush when J=1 regardless of other parameters values. Please, find the code and the error message below. 

Here's the code:

```
data = torch.Tensor(np.random.rand(128,3,32,32))
print("shape before scattering: {}".format(data.shape))

scatModel = Scattering2D(J=1,L=8, shape = (32,32), max_order=2)
a = scatModel(data)

print("shape after scattering: {}".format(a.shape))
```

And the error message: 

> shape before scattering: torch.Size([128, 3, 32, 32])
> Traceback (most recent call last):
>   File "/user/HS221/dm00314/PycharmProjects/ScatterNetsTestFramework/venv/mixingMallatTest.py", line 24, in <module>
>     a = scatModel(data)
>   File "/user/HS221/dm00314/PycharmProjects/ScatterNetsTestFramework/venv/lib/python3.5/site-packages/kymatio-0.2.0.dev0-py3.5.egg/kymatio/scattering2d/scattering2d.py", line 235, in __call__
>   File "/user/HS221/dm00314/PycharmProjects/ScatterNetsTestFramework/venv/lib/python3.5/site-packages/kymatio-0.2.0.dev0-py3.5.egg/kymatio/scattering2d/scattering2d.py", line 202, in forward
> KeyError: 0

Is it me or something is wrong?

Thank you, 
Dmitry

**Comment by edouardoyallon** [comment]
Hi Dmitry,

Thanks for opening this issue. Indeed, the value J=1 can't work currently. If J=1 is used, then no second-order coefficient will be included. I'm not sure it makes sens to set this value as valid.

@janden @lostanlen @eickenberg any thoughts? Should it be a legal value?

**Comment by dminskiy** [comment]
@edouardoyallon, thank you for the reply

But this is exactly what I'm trying to do here. I only need 1 order of coefficients which then will be worked on and reused.

Is there any hacky way I can enable J=1?

**Comment by edouardoyallon** [comment]
So, if you impose maxorder=1 and if you modify this line: https://github.com/kymatio/kymatio/blob/master/kymatio/scattering2d/filter_bank.py#L49 such that the resolution 0 of the filterbank is built, then that should work.

**Comment by edouardoyallon** [comment]
Actually, after looking more carefully, nothing forbids to do J=1 there. Feel free to propose a PR!
