### ISSUE TITLE
[BUG] Scattering1D doesn't have a `device` attribute

### ISSUE THREAD

**Issue by eickenberg** [kymatio/kymatio#402]
This would be useful in a multi-gpu context

**Comment by edouardoyallon** [comment]
#398 +1/3D will fix this.

**Comment by janden** [comment]
So what does this mean? `Scattering2D` doesn't seem to have this attribute (it's a kwarg to `to()`, but that's it).

**Comment by edouardoyallon** [comment]
Will be fixed by v2.
