### ISSUE TITLE
inverse of complex wavelet transform

### ISSUE THREAD

**Issue by nshervt** [kymatio/kymatio#403]
I was wondering how can I invert the wavelet transform 
```
U_r = pad(input)
U_0_c = fft(U_r, 'C2C')

# low pass filter
U_1_c = subsample_fourier(cdgmm(U_0_c, phi[0]), k=2**J)
U_J_r = fft(U_1_c, 'C2R')

# high pass filter
for n1 in range(len(psi)):
    j1 = psi[n1]['j']
    U_1_c = cdgmm(U_0_c, psi[n1][0])
    if(j1 > 0):
        U_1_c = subsample_fourier(U_1_c, k=2 ** j1)
    U_1_c = fft(U_1_c, 'C2C', inverse=True)
```
I am specifically confused about what filters to use and how to invert subsamplings.

**Comment by lostanlen** [comment]
@nshervt you need to compute an adjoint filter for each `psi`, convolve them with `U_1_c`, upsample, sum across `j1`, and retain the real part.

**Comment by nshervt** [comment]
@lostanlen How can I create the adjoint filter?

**Comment by lostanlen** [comment]
@nshervt You need to compute a Littlewood-Paley partition function `A(omega)` by summing, in the Fourier domain, the squared moduli of every `psi` as well as half the squared modulus of `phi`. Then you can define the adjoint filter in the Fourier domain as a pointwise quotient between the complex conjugate of `\hat{psi[j1]}(omega)` and `A(omega)`.
