### ISSUE TITLE
[BUG?] Does `.to` need to set `self.device`?

### ISSUE THREAD

**Issue by eickenberg** [kymatio/kymatio#414]
It looks like our `Scattering` objects do not have a `.device` attribute. Is this necessary? And should we add setting this into the `.to` method? Or am I missing something standard

**Comment by edouardoyallon** [comment]
On torch, if #398 is merged, then `.device()` is automatically inherited as well as `to()` because this is a native torch module functionality.

**Comment by edouardoyallon** [comment]
Duplicate of #402 ?

**Comment by edouardoyallon** [comment]
This issue will be closed by v2.
