### ISSUE TITLE
ENH Multiple tensor sizes

### ISSUE THREAD

**Issue by edouardoyallon** [kymatio/kymatio#418]
One should allow multiple dimension instead to hard code the maximum rank of a tensor. The software would be more flexible. I'll add a unit-test for this asap.

- [x] 1D
- [x] 2D
- [ ] 3D

**Comment by MuawizChaudhary** [comment]
We will close this when #534 implements batch size agnosticism.

**Comment by edouardoyallon** [comment]
Since this has been merged, we are done now.
