### ISSUE TITLE
Large binary file in `examples/2d/images`

### ISSUE THREAD

**Issue by janden** [kymatio/kymatio#426]
Currently, this folder contains one file, `baboon.bmp`, which measures 704 kB (there's also a smaller one, `digit.png`, which measures 271 bytes). The whole repository now weighs in at 1.6 MB, so almost half of it is taken up by this one file. As discussed before, we should find alternatives to storing binary blobs in the repository, and, if this is not feasible, to minimize the size of the binaries we do include.

Is it possible this image can be obtained elsewhere, such as TorchVision? If not, is there some other image that is available on demand which could serve the same purpose?

**Comment by lostanlen** [comment]
i would recommend `scipy.misc.ascent` or `scipy.misc.face`

**Comment by edouardoyallon** [comment]
> i would recommend `scipy.misc.ascent` or `scipy.misc.face`

Any pkg which is not `torch`, `tensorflow` sounds good to me.

**Comment by janden** [comment]
It would really be great if we could purge this from the repo by rewriting `master`, but that may be risky given that people are actually using the software now (although, I assume, mostly through `pip`).
