### ISSUE TITLE
`plot_invert_scattering.py` is not portable

### ISSUE THREAD

**Issue by janden** [kymatio/kymatio#427]
Specifically, it has to be run from its own directory, which is inconvenient. The reason is the line https://github.com/kymatio/kymatio/blob/fff9792fa4920a2f1bd04368df524c763c823344/examples/2d/plot_invert_scattering.py#L26 which specifies the image as a relative path from the working directory. Ideally, this would be done in a way that finds the file by looking at the path of the script instead.

**Comment by lostanlen** [comment]
Related: #426. I'm currently working on a PR which will close both of these.

**Comment by MuawizChaudhary** [comment]
@lostanlen How is progress of this PR?

**Comment by edouardoyallon** [comment]
This is nox fiwed!
