### ISSUE TITLE
Max Order for Scattering2D

### ISSUE THREAD

**Issue by tingyuansen** [kymatio/kymatio#428]
Dear Sir/Madam,

Thank you so much for developing the package. The package is really amazing! 

Just a quick question. for one of my application, it would be really great to extend the order to > 2. I am just wondering if there is any way to extend the order? 

Thank you so much!

**Comment by lostanlen** [comment]
Hello @tingyuansen. There is no simple way to extend Kymatio beyond second-order scattering at the moment. The computational graph of Kymatio is based on depth-first search, so second-order scattering is achieved via two nested for loops. To obtain third-order scattering, one would have to write a triply nested for loop.

Note that the github.com/scatnet/scatnet MATLAB/Octave library supports third-order scattering.
