### ISSUE TITLE
UT more tests for the 3D

### ISSUE THREAD

**Issue by edouardoyallon** [kymatio/kymatio#429]
Currently, the coveraging is not good. Tt seems we only test the equality of the 3D scattering's coefficients with some saved one via a single averaging type. Yet there are 3 different averaging possibility, thus I believe we should store coefficients computed from the other averaging type in order to exclude potential bugs.

**Comment by MuawizChaudhary** [comment]
As discussed, we dropped the other methods for averaging the scattering coefficients.
