### ISSUE TITLE
Audio from 1D scattering coefficients

### ISSUE THREAD

**Issue by blibliki** [kymatio/kymatio#442]
Hello! and thank you for making Kymatio!

I am sorry if this is a naive question or if it has been addressed in any way. 
I want to use time-frequency scattering in order to change the texture of an audio file
by synthesizing a new waveform from the audio's computed scattering coefficients.

In the examples "Compute the scattering transform of a speech recording" or "Compute the scattering transform of a synthetic signal"  how would someone create a new file (wav)  in which the scattering transformations of the signal would become audible? I saw the "plot_invert_scattering.py" but I am not sure If I am doing it correctly for the scattering1D.

thank you

**Comment by lostanlen** [comment]
Hello blibliki, welcome to Kymatio.
What you are asking is not yet possible with Kymatio, for two reasons:
(1) Kymatio does not have time--frequency scattering
(2) Kymatio does not have a stable interface for synthesis

At the moment, Kymatio devs are focused on coming up with a unified API for scattering transforms in 1-D, 2-D, and 3-D with interoperable deep learning backends and frontends, so this is relatively low priority for us. In the meantime, your only short-term option is to use MATLAB language alternatives. I am sorry about that.

**Comment by blibliki** [comment]
Thank you for your answer!
I will check MATLAB as advised!
