### ISSUE TITLE
about 1d scattering.forward(x) problem

### ISSUE THREAD

**Issue by yanwencheng** [kymatio/kymatio#443]
Hi, I am learning wavelet time scattering
In MATLAB, scattering feature matrix formula: smat=featureMatrix(sf,S);
If kymatio wants to get the same characteristic matrix, scattering.forward(x)[0] equivalent to the MATLAB formula?
In addition, the MATLAB plot feature map is
![matlab](https://user-images.githubusercontent.com/11845393/67499557-e7337980-f6b3-11e9-8255-2c628d0bf738.jpg)

However, in kymatio, the feature figure is
![QQ截图20191024231350](https://user-images.githubusercontent.com/11845393/67499588-f5819580-f6b3-11e9-80ec-7baf79ba1b52.jpg)

They are different,It puzzled me a little.

**Comment by edouardoyallon** [comment]
Hi, thanks for asking and opening this issue. So, from what I remember/see:

1. The 1D wavelets of kymatio are slightly different from the MATLAB version.
2. The order of compute is pretty different!(ie, the mapping from kymatio's index to scanet's index isn't the identity)
3. I've the impression the commands are giving some different displays.

FYI, in 2D, the results are identical.(to be precise, I found a bug in the MATLAB version by trying to match the outputs)

**Comment by yanwencheng** [comment]
> 您好，感谢您提出并打开此问题。因此，根据我记得/看到的内容：
> 
> 1. 一维小波的运动幅度与MATLAB版本略有不同。
> 2. 计算的顺序完全不同！（即，从kymatio的索引到scanet的索引的映射不是身份）
> 3. 我给这些命令以不同的显示效果。
> 
> 仅供参考，在2D中，结果是相同的（确切地说，我通过尝试匹配输出发现了MATLAB版本中的错误）

Thank you for your answer。
In kymatio, can I think that SX = scattering. Forward (x) formula SX [0] is the scattering characteristic matrix of one-dimensional signal?

**Comment by edouardoyallon** [comment]
I'm not sure what you mean tbh. @lostanlen might answer better this.
