### ISSUE TITLE
garbage error message resulting from type checks

### ISSUE THREAD

**Issue by eickenberg** [kymatio/kymatio#444]
![image](https://user-images.githubusercontent.com/1306635/67516336-56c64c00-f655-11e9-8bc1-f29604077ed0.png)

"Type of A is not the Type of B" ? What is that supposed to mean for a user who just tried to call scattering on a `DoubleTensor`. We need a better error message here. Probably one stating that the input "probably needs to be of dtype float"

**Comment by edouardoyallon** [comment]
good catch but which version are you using?

**Comment by edouardoyallon** [comment]
@janden it seems this is now hardcoded, isn't it?

**Comment by janden** [comment]
The error message? No we can still change it. I've been changing it here and there. Not sure if I got all of the instances of `A` and `B`, but we're getting there. Keeping this open until I've got them all.

**Comment by MuawizChaudhary** [comment]
@edouardoyallon Do your simplifications take care of this?

**Comment by edouardoyallon** [comment]
yes, cf #538
