### ISSUE TITLE
ENH batch agnosticism

### ISSUE THREAD

**Issue by edouardoyallon** [kymatio/kymatio#451]
Hi,

In v2, only some specific dimension of batches are possible. This behavior should be replaced to allow any batch size, such that the output sizes are consistant across different scattering.

**Comment by janden** [comment]
Isn't this already the case? I could have sworn we implemented this a while ago. Is it not retained by the new frontend interface?

**Comment by edouardoyallon** [comment]
no - if we submit a batch of size (10,3,45,56,32,128) with scattering 1D, this will not run.

**Comment by edouardoyallon** [comment]
furthermore, the corresponding tests are not added.

**Comment by janden** [comment]
What about

https://github.com/kymatio/kymatio/blob/fff9792fa4920a2f1bd04368df524c763c823344/kymatio/scattering1d/tests/test_scattering1d.py#L329

?

**Comment by edouardoyallon** [comment]
> kymatio/kymatio/scattering1d/tests/test_scattering1d.py

In 2D*

**Comment by janden** [comment]
https://github.com/kymatio/kymatio/blob/fff9792fa4920a2f1bd04368df524c763c823344/kymatio/scattering2d/tests/test_scattering2d.py#L252

**Comment by janden** [comment]
Something missing in the test, then?

**Comment by edouardoyallon** [comment]
Damn, I didn't know we had implemented this feature. Alright, so I'm closing the issue.
