### ISSUE TITLE
ENH backend should be classes and not namedtuple

### ISSUE THREAD

**Issue by edouardoyallon** [kymatio/kymatio#452]

**Comment by edouardoyallon** [comment]
i handle that tomorrow

**Comment by edouardoyallon** [comment]
does it still apply?

**Comment by janden** [comment]
It's being handled in #631. Feel free to look it over if you have time.

**Comment by MuawizChaudhary** [comment]
Seems like with our backends being classes now this solves the issue. 

Closing for now.
