### ISSUE TITLE
DOC "raise" section in the documentation

### ISSUE THREAD

**Issue by edouardoyallon** [kymatio/kymatio#453]
@MuawizChaudhary observed we should specify when an error is "Raised" in the documentation. Should we?

**Comment by janden** [comment]
I think it's more important to have error messages that are useful to begin with. Note that the [NumPy docstring guide](https://numpydoc.readthedocs.io/en/latest/format.html#docstring-standard) says that “This section should be used judiciously, i.e., only for errors that are non-obvious or have a large chance of getting raised.” Remember, documentation isn't free. Once it's there, we have to maintain it (and make sure that the rest of the codebase is up to the same standard, which would be a lot of work).

**Comment by edouardoyallon** [comment]
So at the end, this means we should not consider it.
