### ISSUE TITLE
On output of 3D scattering

### ISSUE THREAD

**Issue by nshervt** [kymatio/kymatio#454]
According to the following comment in #158, for a 3D input of size (B, M, N, O), the outputs , based on the method, would have the following dimensions:

> The 3D version returns different outputs for different versions.
> 
> - "standard" would return `(B, P, M/2**J, N/2**J, O/2**J)` 
> - "integral" would return `(B, P, 1, 1, 1)` (or `(B, P)` not sure)
> - "local" would return `(B, P, 1)`
> 
> The reason for "integral" is practically dimensionality reduction (among others) because  3D  is typically large. For "local" you have to ask @louity to be certain but I think it's to identify interesting regions in the moduli (e.g. midpoints between bonded atoms in quantum chemistry)
> 
> _Originally posted by @gexarcha in https://github.com/kymatio/kymatio/issues/158#issuecomment-440062949_

Now I have 2 issues:

 1. for an input data with size `torch.Size([1, 128, 128, 128])`, using standard method, I get an output of size `torch.Size([1, 10, 5, 16, 16, 16])` for a scattering with `J = 3` and `L = 4`. This does not follow `(B, P, M/2**J, N/2**J, O/2**J)`  that was mentioned earlier, but looks like `(B, ?, ?, M/2**J, N/2**J, O/2**J)`. I was wondering how to compute values for the dimensions  marked by `?`.

 2. Again, as mentioned in another comment in https://github.com/kymatio/kymatio/issues/158#issuecomment-441827979 and implemented in `scattering3d_qm7`, zeroth order coefficients are computed using `compute_integrals`. However, the example implemented in `compute_speed.py` does not use `compute_integrals`. I was wondering which one is correct, to use or not to use `compute_integrals`?

Thanks!

**Comment by lostanlen** [comment]
We need to make sure that the 3d outputs does not elide trailing singleton dimensions

**Comment by MuawizChaudhary** [comment]
@lostanlen That is done. Is the rest of this issue solved?

**Comment by edouardoyallon** [comment]
@janden can be closed now, isn't it?

**Comment by MuawizChaudhary** [comment]
@janden ?

**Comment by janden** [comment]
Remind me where this was fixed again?

**Comment by mburhanpurkar** [comment]
Hi, I tried running a 3D transform with J=3, L=5, and input size (128, 128, 128) and found an output shape of (B, 10, 6, P) with method='integral', which I don't think is consistent with what's listed here https://www.kymat.io/userguide.html#id14. 

It also looks like 'standard' and 'local' aren't permitted for 3D currently--doing either of these gives me the same output shape as 'integral', but perhaps I'm using the package incorrectly.

**Comment by MuawizChaudhary** [comment]
My intuition/[empirical evidence](https://colab.research.google.com/drive/1Gtzpvy9q7E2R_vuBeOWNdk0w8dkkER0F#scrollTo=qkCPtK6_p3NA) (thanks to @eugenium's tutlege in my research endeavors) tells me that with a `max_order=1`, the output shape will be `(B, C, J+1, L+1, P)` and with `max_order=2`, the output shape will be `(B, C, J+1 + J(J+1)/2, L+1, P)` 

The number depends on the number of filters generated for first order and second order wavelets. I'll submit a pull request shortly.

**Comment by janden** [comment]
Closed by #820.
