### ISSUE TITLE
Parametrizing over backend–device tuples

### ISSUE THREAD

**Issue by janden** [kymatio/kymatio#456]
In the unit tests for the new frontend code, there are many `if` clauses to single out the skcuda backend (since it only works for GPU tensors). We can avoid this by parametrizing over a `backend_device` tuple, which would take values `('torch', 'cpu')`, `('torch', 'gpu')`, and `('torch_skcuda', 'gpu')`, assuming all these are available. This would greatly simplify many of the tests.

**Comment by edouardoyallon** [comment]
... this is now done, isn't it? @janden

**Comment by MuawizChaudhary** [comment]
Seems like it is. Thoughts @janden ?

**Comment by janden** [comment]
Only for 2D torch, as far as I know. Needs to be done in 1D and 3D torch. Not sure how it works in TF. Is there a way to force calculations on CPU?

**Comment by MuawizChaudhary** [comment]
This appears to be done in 1d and 3d torch now. Does not appear to be the case in Tensorflow.

**Comment by MuawizChaudhary** [comment]
Closing the issue for now since it seems resolved. Reopen if you disagree @janden @edouardoyallon
