### ISSUE TITLE
Batch compression and restore

### ISSUE THREAD

**Issue by janden** [kymatio/kymatio#461]
It might be nice to have two functions: `x, batch_shape = compress_batch(x, dim)`, where `dim` corresponds to how many dimensions to “keep” (here, two), and `x = restore_batch(x, batch_shape)`. This way, we can use the functions across dimensions (and frontends) by changing the `dim` parameter.

_Originally posted by @janden in https://github.com/kymatio/kymatio/pull/459_

**Comment by edouardoyallon** [comment]
isn't it... done?

**Comment by MuawizChaudhary** [comment]
This appears to be the logic we utilize in the [scattering](https://github.com/kymatio/kymatio/blob/dev/kymatio/scattering1d/frontend/numpy_frontend.py#L19) functions, tho not as nicely as a function. Please reopen if you think it should be done in the form of a function @janden
