### ISSUE TITLE
MAINT Output size calculation not used.

### ISSUE THREAD

**Issue by MuawizChaudhary** [kymatio/kymatio#476]
https://github.com/kymatio/kymatio/blob/5bf71fd7aab1e60bb12cfaa4a2b42d722a91e893/kymatio/scattering2d/core/scattering2d.py#L17

Since we do not preallocate an array, we do not need to calculate the output sizes. I suggest we keep the calculation of the order 0, 1, 2 sizes, but remove `output_sizes`.

**Comment by edouardoyallon** [comment]
@janden u agree with this suggestion?

**Comment by lostanlen** [comment]
this business of computing output sizes is going to be needed in the Keras layer
ideally we should do it without computing any coefficient

**Comment by edouardoyallon** [comment]
Vincent statement is pretty true... As it's few lines, I'm ok to give it
