### ISSUE TITLE
ModuleNotFoundErrors

### ISSUE THREAD

**Issue by anakin-datawalker** [kymatio/kymatio#480]
- [x] 1D
- [x] 2D
- [x] 3D

Hi everyone,

In the current kymatio-v2 branch, there are no __init__.py files in the kymatio.frontend, kymatio.scattering2d.backend and kymatio.scattering2d.core packages. It leads on my side to ModuleNotFoundErrors when trying to run for instance examples/2d/cifar.py after installing kymatio by python setup.py install (or similarly pip install . in the kymatio head folder). It seems to be linked to the find_packages function of setuptools: "find_packages() walks the target directory, filtering by inclusion patterns, and finds Python packages (any directory). Packages are only recognized if they include an __init__.py file." ([https://setuptools.readthedocs.io/en/latest/setuptools.html#using-find-packages](url)).

Adding empty __init__.py in those packages solved the problem for me.

**Comment by edouardoyallon** [comment]
It seems I can't reproduce the issue, can someone comment about that?

**Comment by edouardoyallon** [comment]
ok found it, thanks!!
