### ISSUE TITLE
SubsampleFourier torch docstrings

### ISSUE THREAD

**Issue by anakin-datawalker** [kymatio/kymatio#481]
Hi everyone,

There seems to be a small mistake in the backend/torch_backend.py and backend/torch_skcuda_backend.py SubsampleFourier function docstrings.

https://github.com/kymatio/kymatio/blob/5bf71fd7aab1e60bb12cfaa4a2b42d722a91e893/kymatio/scattering2d/backend/torch_backend.py#L120-L128

The subsampling is by k, not 2**k (is correct in numpy_backend and tensorflow_backend)

**Comment by eickenberg** [comment]
Ah, good catch. Then it must be called with a power of 2 already.

If you have time, could you make a PR to fix the docstring?

Thanks!

**Comment by anakin-datawalker** [comment]
Sure that should be done.

Best
