### ISSUE TITLE
Remove redundant loading of frontends

### ISSUE THREAD

**Issue by janden** [kymatio/kymatio#488]
Do we wanna define a subclass `ScatteringBase` in the main `kymatio` folder, from which `Scattering*D` subclass inherits from, and all we do here is init the `ScatteringBase`? 

@lostanlen @janden your thoughts are also appreciated.

_Originally posted by @MuawizChaudhary in https://github.com/kymatio/kymatio/diffs_

Right now, the dynamic loading of frontends (i.e., the `self.__class__` trick) is replicated for each of the `Scattering*D` classes. This should be moved into a shared superclass or some auxiliary function.

**Comment by lostanlen** [comment]
Yes. This was discussed at the whiteboard on Thursday with @eickenberg et al.
Related: #489  ?
