### ISSUE TITLE
Template the documentation across frontends

### ISSUE THREAD

**Issue by janden** [kymatio/kymatio#489]
Yes. Let's fix. In the future, we'd probably like to template the docs like they do here:

https://github.com/lebedov/scikit-cuda/blob/4781f2e2aa317c3218f9ce1e226a09d7be81af59/skcuda/cublas.py#L411

_Originally posted by @janden in https://github.com/kymatio/kymatio/diffs_

**Comment by edouardoyallon** [comment]
That's a great suggestion and an impressive mechanism!

**Comment by edouardoyallon** [comment]
This has been very nicely implemented in #546
