### ISSUE TITLE
scattering1d/filter_bank module has too many functions

### ISSUE THREAD

**Issue by lostanlen** [kymatio/kymatio#513]
13 functions, most of them only called once or twice. Surely we can simplify that.

**Comment by lostanlen** [comment]
This is a continuation of #227

**Comment by MuawizChaudhary** [comment]
It'd be nice to make some progress on this soon, not just for JTFS but for having a clean scattering1d potential new developers aren't scared away from.

**Comment by lostanlen** [comment]
i've reduced the number of functions to 10 and brought `filter_bank` under 500 lines (docs included). We could reduce the codebase even more in the future but i would say that this is an good milestone. Closing.
