### ISSUE TITLE
Error in regularized inverse scattering mnist torch example

### ISSUE THREAD

**Issue by MuawizChaudhary** [kymatio/kymatio#542]
In the planned update, one of the examples, `regularized_inverse_scattering_MNIST_torch.py`, errors out. The error I get is 

> RuntimeError: output with shape [1, 28, 28] doesn't match the broadcast shape [3, 28, 28]

This happens on line 94.

**Comment by eugenium** [comment]
Change line https://github.com/kymatio/kymatio/blob/0.2.X/examples/2d/regularized_inverse_scattering_MNIST_torch.py#L86 to  transforms.Normalize((0.5,), (0.5,))

**Comment by edouardoyallon** [comment]
this needs to be check before the release!

**Comment by edouardoyallon** [comment]
Still not fixed
