### ISSUE TITLE
Keras frontend in entry point

### ISSUE THREAD

**Issue by janden** [kymatio/kymatio#555]
> @edouardoyallon @eickenberg Do we want to include the Keras “frontend” in the multiplexer/entry point (i.e., `Scattering2D(J=J, frontend='keras')`? I don't see why not.

Well, sure.

_Originally posted by @edouardoyallon in https://github.com/kymatio/kymatio/pull/553#issuecomment-581949287_

**Comment by edouardoyallon** [comment]
Thishas been done in #563
