### ISSUE TITLE
Make input checks in Torch and NP more specific

### ISSUE THREAD

**Issue by janden** [kymatio/kymatio#558]
Also, why not just make sure it's a `torch.Tensor`? Just checking for `None` is quite restricted.

_Originally posted by @janden in https://github.com/kymatio/kymatio/pull/538_

**Comment by MuawizChaudhary** [comment]
@edouardoyallon Do you think this is a good idea?

**Comment by edouardoyallon** [comment]
> @edouardoyallon Do you think this is a good idea?

Yes I do

**Comment by MuawizChaudhary** [comment]
Taking a look at dev and the backend primitives for each framework in each dimensionality, it looks like we took care of this over the 2020 and 2021 hackathon. 

Closing this for now, @janden @edouardoyallon reopen if you disagree.
