### ISSUE TITLE
Include Keras, sklearn in docs and structure

### ISSUE THREAD

**Issue by janden** [kymatio/kymatio#583]
Right now, it's all one big text. We should split up different subsections for different frontends. At the top, we should have a quick text summarizing the frontend framework and describing how to import them dynamically (using `kymatio.Scattering*D` and specifying `frontend` when creating).

**Comment by edouardoyallon** [comment]
can you point me to the file you want to modify? thanks

**Comment by janden** [comment]
This one:

https://github.com/kymatio/kymatio/blob/master/doc/source/codereference.rst

So basically:

- Intro about frontends, example how to instantiate one “statically”
```
from kymatio.torch import Scattering2D
```
or dynamically
```
from kymatio import Scattering2D
S = Scattering2D(shape, J, frontend='torch')
```
- Doc for torch
- Doc for NP
- Doc for TF
- Doc for Keras
- Doc for sklearn

With all of these being a separate section. Does that makes sense?

**Comment by edouardoyallon** [comment]
yes. @eickenberg ?

**Comment by edouardoyallon** [comment]
https://www.kymat.io/userguide.html we should quickly discuss it here as well.

**Comment by janden** [comment]
Yes and also here: https://github.com/kymatio/kymatio/blame/9577d0f3f212b45d171377d264cbe9de4ed31cf2/README.md#L143
