### ISSUE TITLE
sphinx inverses colors...

### ISSUE THREAD

**Issue by edouardoyallon** [kymatio/kymatio#594]
no clue why, but it can wait v3.

cf here:
https://www.kymat.io/gallery_2d/plot_scattering_disk.html#sphx-glr-gallery-2d-plot-scattering-disk-py
https://www.kymat.io/gallery_2d/plot_invert_scattering_torch.html#sphx-glr-gallery-2d-plot-invert-scattering-torch-py

**Comment by edouardoyallon** [comment]
@MuawizChaudhary would be nice to fix.

**Comment by eickenberg** [comment]
@edouardoyallon can you paste an image and explain which part exactly is inverted?

**Comment by edouardoyallon** [comment]
For the racoon, part of the issue is that the optimization hasn't converged. Should I increase max_iter, the maximum number of iterations?
