### ISSUE TITLE
minor style fix for the doc

### ISSUE THREAD

**Issue by edouardoyallon** [kymatio/kymatio#595]
https://www.kymat.io/codereference.html

Here, the "Exampels" part do not parse well(eg uncleaned colons+ sharp). Not sure why.

**Comment by janden** [comment]
I don't see this. Can you post a screenshot?

**Comment by edouardoyallon** [comment]
As an example:

<img width="654" alt="Screenshot 2020-03-10 at 10 46 14" src="https://user-images.githubusercontent.com/4263222/76324432-5fde4f80-62bc-11ea-93c0-301f37876457.png">

**Comment by janden** [comment]
Ah I see. Yes that should be fixed.

**Comment by janden** [comment]
A more major concern there is that the TF/Keras docs don't show up. Presumably because it can't import TF during the doc building.

**Comment by eickenberg** [comment]
Hang on -- the code should be displayed though?

**Comment by janden** [comment]
The `# Set the parameters for …` stuff? Yeah, it should be set like the examples in 1D and 2D.

**Comment by eickenberg** [comment]
The output of the [sklearn-transformer example](https://www.kymat.io/gallery_2d/plot_sklearn.html#sphx-glr-gallery-2d-plot-sklearn-py) is also broken maybe?

**Comment by eickenberg** [comment]
So in the example Edouard gave, I don't understand what is happening. Does anybody know what's going on?

**Comment by eickenberg** [comment]
> A more major concern there is that the TF/Keras docs don't show up. Presumably because it can't import TF during the doc building.

The code for MNIST-keras is shown though?

**Comment by edouardoyallon** [comment]
> So in the example Edouard gave, I don't understand what is happening. Does anybody know what's going on?

It's a matter of spacing and parsing .. I think the doc requires also a `import tensorflow`... reopening miles 2.

**Comment by eickenberg** [comment]
do you have enough a handle on it to be able to fix it?

Otherwise, can you point me to where I need to look to understand what is going on?
