### ISSUE TITLE
DOC link to the contributors

### ISSUE THREAD

**Issue by edouardoyallon** [kymatio/kymatio#596]
https://github.com/kymatio/kymatio#online-resources should be added here

**Comment by janden** [comment]
There's "List of authors” on there. What else do you want to add?

**Comment by edouardoyallon** [comment]
https://github.com/kymatio/kymatio/blob/master/CONTRIBUTORS.md This link. We made a distinction between the two.

**Comment by janden** [comment]
Right. Yes that makes sense to add. Maybe have that instead of the author list?

**Comment by edouardoyallon** [comment]
I'd put both.
