### ISSUE TITLE
unecessary utils

### ISSUE THREAD

**Issue by edouardoyallon** [kymatio/kymatio#598]
https://github.com/kymatio/kymatio/blob/master/kymatio/scattering2d/utils.py#L26

should be in common or removed.

**Comment by edouardoyallon** [comment]
I agree.

**Comment by janden** [comment]
> I agree.

With what? The reason that `fft2` was there was to remove a certain FutureWarning about fftpack disappearing (which is happening now). Not sure how it's unnecessary?
