### ISSUE TITLE
Circle CI doesn't have TF

### ISSUE THREAD

**Issue by janden** [kymatio/kymatio#600]
As a result, the docs for TF and Keras are not generated (see discussion in #595). Issue seems to be that TF is not installed. The Circle CI log has this
```
WARNING: autodoc: failed to import module 'tensorflow' from module 'kymatio'; the following exception was raised:
No module named 'tensorflow'
WARNING: autodoc: failed to import module 'keras' from module 'kymatio'; the following exception was raised:
No module named 'tensorflow'
```
Can probably be solved by adding `pip install tensorflow` after https://github.com/kymatio/kymatio/blob/9df4b37e49e78e174cdacf436ee8e78315fcbd19/.circleci/config.yml#L49

**Comment by edouardoyallon** [comment]
is it necessary for v2?

**Comment by eickenberg** [comment]
I removed the install of tf because it made all the examples, including the ones that didn't use tf, segfault
