### ISSUE TITLE
MAINT Remove option to not pad

### ISSUE THREAD

**Issue by MuawizChaudhary** [kymatio/kymatio#628]
Currently in the 2d backend we have the option of [simply not doing a padding](https://github.com/kymatio/kymatio/blob/dev/kymatio/scattering2d/backend/torch_backend.py#L13).  This changes the semantic meaning of the `Pad` class object. We should remove this option, as we want this function to always pad.

**Comment by janden** [comment]
@edouardoyallon I believe you added this at some point. Do you want to discuss where this comes from and what it's used for?

**Comment by edouardoyallon** [comment]
It was used for imagenet: sometimes you might have a signal which is large enough to avoid additional padding, and you just crop the final result(which leads to no border effect). For instance, on imagenet, the images might be 256^2 and but the architecture has to process(for legacy reasons) 224^2 images... so instead, one processes the 256^2 image and one crops the final results, thus it's not worth to pad/unpad. Maybe it's fast enough now. Not sure.

**Comment by janden** [comment]
Ah ok. So we'll leave the option in the scattering transform but take it out of the `Pad` module.

**Comment by eickenberg** [comment]
This looks like something to be addressed pre-sprint or at the latest at the sprint.

**Comment by MuawizChaudhary** [comment]
It looks like this was addressed during the 2021 sprint.
