### ISSUE TITLE
Resolution (Question)

### ISSUE THREAD

**Issue by jecampagne** [kymatio/kymatio#633]
Dear Team,
Computing the Scattering(2D) Coeff at a given scale provides all coefficients with a 2D resolution given by (H//2**J, W//2**J), for instance  if J=3, the Scattering coeff at j=1 are given at the same resolution than the ones at j=2, that is to say H//8, W//8. But If I had set J=2, than the scattering coeff at j=1 would have been at resolution H//4, W//4. 
Q: is there a way, or does it make sense to choose the final resolution of the coefficients (I guess this would be at least the same for all of them).
JE

**Comment by edouardoyallon** [comment]
hi, currently there is no possibility to modify the oversampling factor. The rational is that we maintain a higher resolution for high frequency wavelets to avoid aliasing and then we keep working with an oversampling factor (of order 1 or 2, i don't remember the details) - feel free to open an issue if you wish to get this feature
