### ISSUE TITLE
Kymatio Scattering Transform 1D Error 'The input must be contiguous.'

### ISSUE THREAD

**Issue by evertoneie** [kymatio/kymatio#634]
I am starting to work with the Kymatio library, in order to use the Scattering transform as an extractor of 1D signal characteristics. The final idea is to classify 1D signals.

I followed the example available at the link

https://www.kymat.io/gallery_1d/plot_classif_torch.html#sphx-glr-gallery-1d-plot-classif-torch-py

Based on this example, I imported three .mat files that contain the compiled data from the COOLL dataset (https://coolldataset.github.io/). Two variables were imported:

x2 contains the values ​​of the appliance currents. x2 is a matrix with 840 lines and 4 * 8192 columns. y2 contains the Label list. It has 840 positions, one for each appliance.

I'm trying to calculate the coefficients of the Scattering1D transform for each of the signals that x2 contains. For this, I am doing the following:

```
T=32768;
J=8;
Q=12;
if use_cuda:
    scattering.cuda()
    
    x2 = x2.cuda()
    y2 = y2.cuda()

Sx_all = scattering.forward(x2)
```
When I do this, the following error appears:

```
RuntimeError                              Traceback (most recent call last)
<ipython-input-62-26c538d90a70> in <module>()
      1 #Sx_all = scattering(x2)
----> 2 Sx_all = scattering.forward(x2)

1 frames
/usr/local/lib/python3.6/dist-packages/kymatio/backend/torch_backend.py in input_checks(x)
      9 
     10     if not x.is_contiguous():
---> 11         raise RuntimeError('The input must be contiguous.')
     12 
     13 def _is_complex(x):

RuntimeError: The input must be contiguous.
```
This error does not appear when I run the original program, from the example available at https://www.kymat.io/gallery_1d/plot_classif_torch.html#sphx-glr-gallery-1d-plot-classif-torch-py.

What exactly does the error message 'The input must be contiguous' mean, and how do you suggest I fix the problem? I tried to read the library documentation but I still haven't solved the problem.

Thank you very much for your help.

**Comment by evertoneie** [comment]
I believe that I have found the solution, using tensor.contiguous().
```
x2 = x_all_import['x_all'] 

x2 = torch.from_numpy(x2)
x2 = x2.contiguous();


y2 = y_all_import['y_all']
y2 = y2.flatten()  


y2 = torch.from_numpy(y2)
y2 = y2.contiguous();
```

**Comment by eickenberg** [comment]
Hi @evertoneie 

That is indeed the solution.

Thanks for reporting in detail. This will help others who run into the same problem!
