### ISSUE TITLE
How to inverse wavelet tranform to a original signal

### ISSUE THREAD

**Issue by LittleFlyingSheep** [kymatio/kymatio#636]
Thank you for your work! I have a question about how to inverse wavelet tranform to a original signal. Does it like you show in [https://github.com/kymatio/kymatio/blob/master/examples/1d/reconstruct_torch.py](url)? 

I viewed the code and find you inverse it by training the scatting. Is there a exist function (like iSTFT for STFT) for inverse wavelet process?

**Comment by lostanlen** [comment]
Hello @LittleFlyingSheep, you may use PyWavelets to compute a wavelet transform in 1-D or 2-D, both forward and inverse: 
https://pywavelets.readthedocs.io/en/latest/

Kymatio is a library for scattering transforms, which is a nonlinear operator. Inverting the scattering transform is not impossible but not as straighforward as inverting a wavelet transform.

Two papers which use Kymatio as a generative model are:
* in 1D. "wav2shape: Hearing the Shape of a Drum Machine" by Han Han and myself
* in 2D. "Particle gradient descent model for point process generation" by Brochard, Błaszczyszyn, and Mallat

I hope this helps!

**Comment by LittleFlyingSheep** [comment]
Hi, @lostanlen. Thank you very much! Your answer is so helpful that I know what is my need now.

**Comment by lostanlen** [comment]
I'm glad i could help. Good luck with your research
