### ISSUE TITLE
How can I use Kymatio for image feature representation

### ISSUE THREAD

**Issue by nouraIT** [kymatio/kymatio#638]

**Comment by edouardoyallon** [comment]
https://www.kymat.io/gallery_2d/mnist_keras.html#sphx-glr-gallery-2d-mnist-keras-py

**Comment by nouraIT** [comment]
like they did in this paper 
https://www.researchgate.net/publication/341889024_On_Matching_Finger-Selfies_Using_Deep_Scattering_Networks

**Comment by lostanlen** [comment]
@nouraIT if you want to replicate the findings of the paper, your safest option is to contact the authors directly. It seems like they are not using Kymatio but ScatNet, which is a MATLAB implementation: https://github.com/scatnet/scatnet

That being said, we expect the results of ScatNet and Kymatio to be roughly the same

**Comment by nouraIT** [comment]
I tried the documentation to produce the same results but the only relevant example I could find is Scattering disk display. how can I get the features of an image the way the paper did? I'm only asking because I've been stuck for a while trying to implement the DSN part.

**Comment by lostanlen** [comment]
@nouraIT again, i recommend that you contact the authors for replication.
Edouard has shared a link to compute the scattering features of an image with Kymatio: https://www.kymat.io/gallery_2d/mnist_keras.html#sphx-glr-gallery-2d-mnist-keras-py
or with ScatNet: https://www.di.ens.fr/data/software/scatnet/quickstart-image/
