### ISSUE TITLE
[Todo] Compatibility with python 3.8/3.9(?)

### ISSUE THREAD

**Issue by edouardoyallon** [kymatio/kymatio#642]
We need to add it to the unit tests.

**Comment by janden** [comment]
So it looks like 3.8 should be fine, but TF is not supported on 3.9 yet. Normally, this shouldn't be a problem (we can support torch/np/sklearn on 3.9) but the way our test suite is set up, we have to run the tests on all backends (see #584). Once that is resolved, we can extend to 3.9 (and just skip testing TF there for now).
