### ISSUE TITLE
Problem of scattering network used in adversarial training

### ISSUE THREAD

**Issue by momo1986** [kymatio/kymatio#644]
Hello, dear kymatio team.

I want to use scattering network in adversarial training.

However, I met some problems.
https://github.com/edouardoyallon/scalingscattering/issues/8

I want to do inverse operation to make the tensor after scattering back to its original shape.

I am not sure, whether there is some APIs for interface.

Thanks & Regards!
Momo

**Comment by edouardoyallon** [comment]
Hi @momo1986, I think you should move to kymatio rather than this old implementation. I'm not sure to understand the issue with the reshaping,y et I close the issue as I believe using kymatio should resolve your issues.
