### ISSUE TITLE
T → N

### ISSUE THREAD

**Issue by janden** [kymatio/kymatio#656]
As part of our discussion on separating the wavelet scale from the averaging scale, we realized that the variable T is already being used in 1D for the size of the signals. In the 2D code (and in scatnet, I think), this is denoted N, so I suggest we rename T to N. This would then free up T as the averaging scale parameter.

**Comment by janden** [comment]
Ping @lostanlen.

**Comment by lostanlen** [comment]
yes, N is good. Eventually i'd like to make this argument optional (i.e. defaulting to some multiple of Q * 2**J) and rely on overlap-add convolutions (#305). But it's too early for that.

**Comment by janden** [comment]
Agreed. Will put together a PR.

**Comment by janden** [comment]
Agreed. Will put together a PR.
