### ISSUE TITLE
The reconstructed signals look completely different than the original signal even though the loss from the reconstruction is pretty low. 

### ISSUE THREAD

**Issue by Vin-itall** [kymatio/kymatio#675]
I have been trying to perform scattering transform to a time-series data and the reconstructed motifs are completely different than the original motifs. For example. 

Original Motifs from a time series.

![Screenshot 2021-03-04 at 8 50 38 AM](https://user-images.githubusercontent.com/12558361/110186585-04fa0e00-7dd3-11eb-8e12-3a2656e9dd71.png)

And the reconstructed motifs look like this. 

![Screenshot 2021-03-04 at 8 50 55 AM](https://user-images.githubusercontent.com/12558361/110186611-10e5d000-7dd3-11eb-9052-e7bfb4ef4ede.png)

Am I missing out on some parameters? Or is there a possible explanation for this behaviour?

**Comment by edouardoyallon** [comment]
Hi, thanks for your msg, to me, w.r.t. a l^2 loss, they look the same. Have you considered using a log? Maybe @lostanlen will have more insightful comments

**Comment by Vin-itall** [comment]
I haven't used log loss, I'll try that out too. Since, the length of the signal is 1000 time units I am using J = 9.

**Comment by edouardoyallon** [comment]
Alright. What is weird too me is that despite the high value of $J$, the figures of (b) seem to spike at the same time. J=9 might be slightly high, and I'd consider using smaller values (which might be simpler to compute). Again, @lostanlen will have probably more insightful comments.

**Comment by Vin-itall** [comment]
@edouardoyallon I think I tried out smaller values for J. I'll double check it and let you know.

**Comment by lostanlen** [comment]
Hello @Vin-itall , my guess is that `J` is indeed to high for the task. 
Besides, can you try adding an offset to the input signal and see if the same offset also appears in the reconstructed signal? If it doesn't, make sure that the difference at the zeroth order (`S_0`) appears in the loss function for reconstruction

**Comment by Vin-itall** [comment]
Hi @lostanlen  thanks for your input, I'll try out your suggestions and get back to you.

**Comment by Vin-itall** [comment]
Waiting on fix for #678

**Comment by Vin-itall** [comment]
@lostanlen  Hey, lower value for J did the trick. Thanks a lot for your input. Is there some resource where I can read up on how J impacted the reconstruction? If so please let me know.

**Comment by lostanlen** [comment]
Glad it's working, @Vin-itall 
You can refer to Figure 10 of: Andén, Lostanlen, and Mallat. "Joint time-frequency scattering" IEEE SPL
rows (b), (d) and (f) correspond to increasing values of J
https://www.lostanlen.com/wp-content/uploads/2019/12/anden2019tsp.pdf
