### ISSUE TITLE
Phase synchrony

### ISSUE THREAD

**Issue by zeydabadi** [kymatio/kymatio#676]
Hello all,

I wonder how can I utilize Kymatio for Phase synchrony analysis of two 1D signals?
I appreciate any thoughts/suggestions.

Thank you,
Mahmoud

**Comment by lostanlen** [comment]
Hello @zeydabadi, the simplest approach i could think of would be the cross-correlation between the scattering features of your two signals.

**Comment by zeydabadi** [comment]
> Hello @zeydabadi, the simplest approach i could think of would be the cross-correlation between the scattering features of your two signals.

Thanks for your response. In this case, what would be the benefit of doing cross-correlation using scattering features versus original signals?

**Comment by lostanlen** [comment]
The benefit would be stability to deformations (time warps in the 1D case).
If one of your two signals is warped nonlinearly with respect to the other, cross-correlation in the raw signal domain will fail to retrieve the best alignment whereas cross-correlation in the domain of scattering features will remain robust to that perturbation

**Comment by edouardoyallon** [comment]
Hi @zeydabadi , if that sounds good to you, I think this should move to the new section "Discussion". Thus I close this issue, as issue should just be here to report issues with the software. Thanks!
