### ISSUE TITLE
TypeError: 'module' object is not callable, in the progress of computing scattering by ScatteringTorch1D 

### ISSUE THREAD

**Issue by Bitter13044** [kymatio/kymatio#678]
Hello, all.
I tried fsdd classification in example projects (https://www.kymat.io/gallery_1d/plot_classif_torch.html#sphx-glr-gallery-1d-plot-classif-torch-py), but the error occurred at `Sx_all = scattering.forward(x_all)`.

OS: Linux Ubuntu 
Python version 3.7
PyTorch version 1.8.0

Detail 
> /usr/local/lib/python3.7/dist-packages/kymatio/frontend/torch_frontend.py in forward(self, x)
     21         input_checks(x)
     22 
---> 23         return self.scattering(x)
     24 
     25     _doc_array = 'torch.Tensor'
>
>/usr/local/lib/python3.7/dist-packages/kymatio/scattering1d/frontend/torch_frontend.py in scattering(self, x)
    119                        vectorize=self.vectorize,
    120                        size_scattering=size_scattering,
--> 121                        out_type=self.out_type)
    122 
    123         if self.out_type == 'array' and self.vectorize:
>
>/usr/local/lib/python3.7/dist-packages/kymatio/scattering1d/core/scattering1d.py in scattering1d(x, pad, unpad, backend, J, psi1, psi2, phi, pad_left, pad_right, ind_start, ind_end, oversampling, max_order, average, size_scattering, vectorize, out_type)
     76 
     77     # compute the Fourier transform
---> 78     U_0_hat = fft(U_0, 'C2C')
     79 
     80     # Get S0
>
>/usr/local/lib/python3.7/dist-packages/kymatio/backend/base_backend.py in __call__(self, x, direction, inverse)
     56 
     57     def __call__(self, x, direction='C2C', inverse=False):
---> 58         return self.fft_forward(x, direction=direction, inverse=inverse)

>/usr/local/lib/python3.7/dist-packages/kymatio/backend/base_backend.py in fft_forward(self, x, direction, inverse)
     51                 output = self.ifft(x)
     52             else:
---> 53                 output = self.fft(x)
     54 
     55         return output
>
>/usr/local/lib/python3.7/dist-packages/kymatio/scattering1d/backend/torch_backend.py in <lambda>(x)
    132 
    133 
--> 134 fft = FFT(lambda x: torch.fft(x, 1, normalized=False),
    135     lambda x: torch.ifft(x, 1, normalized=False),
    136     lambda x: torch.irfft(x, 1, normalized=False, onesided=False),
>
>TypeError: 'module' object is not callable

Thank you,
Bitter13044

**Comment by edouardoyallon** [comment]
Hi Bitter13044,
Thanks for reporting it. I'm going to propose a fix today.
Best,
EO

**Comment by edouardoyallon** [comment]
Hi, this is should be fixed by #679 (soon merged)

**Comment by Bitter13044** [comment]
Hello @edouardoyallon, thank you for your effort.
I'm looking forward to the update.

**Comment by OverLordGoldDragon** [comment]
Fixed in dev, set to merge with master.
