### ISSUE TITLE
Is master branch stable?

### ISSUE THREAD

**Issue by OverLordGoldDragon** [kymatio/kymatio#680]
Last release was a year ago. I'm running into some bugs with`torch` backend that are fixed in current master. Is master branch recommended?

**Comment by edouardoyallon** [comment]
The issue is pytorch. Please checkout this branch: https://github.com/kymatio/kymatio/pull/679 (which is waiting to get merged)

**Comment by OverLordGoldDragon** [comment]
Thanks; it's also `cupy` (no attribute `util`, fixed in master).

**Comment by edouardoyallon** [comment]
yeah it's quite annoying.. looking forward to merge those - thanks for reporting it
