### ISSUE TITLE
'builtin_function_or_method' object has no attribute 'fft' ('torch_skcuda' backend)

### ISSUE THREAD

**Issue by OverLordGoldDragon** [kymatio/kymatio#681]
Same error with either install:

`pip install git+https://github.com/kymatio/kymatio.git@master`
`pip install git+https://github.com/edouardoyallon/kymatio.git@torch17`

<details>
  <summary><b>code + output</b></summary>

```python
import numpy as np
import torch
import cupy
import kymatio
from kymatio.torch import Scattering1D
_ = [print(m.__name__, m.__version__) for m in (np, torch, cupy, kymatio)]

x = np.random.randn(1024)
T = x.shape[-1]
J = 6
Q = 16
scattering = Scattering1D(J, T, Q, backend='torch_skcuda')

xt = torch.as_tensor(x)
Scx = scattering(xt)
```
```
numpy 1.18.5
torch 1.7.1
cupy 8.3.0
kymatio 0.3.dev0
Traceback (most recent call last):

  File "C:\untitled10.py", line 19, in <module>
    Scx = scattering(xt)

  File "D:\Anaconda\envs\pyt\lib\site-packages\torch\nn\modules\module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)

  File "D:\Anaconda\envs\pyt\lib\site-packages\kymatio\frontend\torch_frontend.py", line 23, in forward
    return self.scattering(x)

  File "D:\Anaconda\envs\pyt\lib\site-packages\kymatio\scattering1d\frontend\torch_frontend.py", line 121, in scattering
    out_type=self.out_type)

  File "D:\Anaconda\envs\pyt\lib\site-packages\kymatio\scattering1d\core\scattering1d.py", line 78, in scattering1d
    U_0_hat = fft(U_0, 'C2C')

  File "D:\Anaconda\envs\pyt\lib\site-packages\kymatio\backend\base_backend.py", line 58, in __call__
    return self.fft_forward(x, direction=direction, inverse=inverse)

  File "D:\Anaconda\envs\pyt\lib\site-packages\kymatio\backend\base_backend.py", line 53, in fft_forward
    output = self.fft(x)

  File "D:\Anaconda\envs\pyt\lib\site-packages\kymatio\scattering1d\backend\torch_backend.py", line 134, in <lambda>
    fft = FFT(lambda x: torch.view_as_real(torch.fft.fft(torch.view_as_complex(x))),

AttributeError: 'builtin_function_or_method' object has no attribute 'fft'
```
</details>

**Comment by edouardoyallon** [comment]
Right, so: can you try to use the torch17_backend when using torch <=1.7 and otherwise torch_backend when torch >1.7 (sorry for this situation, it's not us..) Does it fix your issue?

**Comment by OverLordGoldDragon** [comment]
@edouardoyallon If you mean `backend='torch'` with `torch 1.7.1`, the error persists. If it helps, Win 10 x64, Python 3.7.9.

Btw I'm mainly reporting for your notice, my use is primarily with studying the code; got tripped with `cupy.util`, but fine otherwise.

**Comment by edouardoyallon** [comment]
Can you try to use backend='torch17_skcuda'?
https://github.com/kymatio/kymatio/pull/679/files#diff-09dede65a58346e201c282dd2ce84d02b0c3bf73ed7d2ce766399a8992ed14e4

**Comment by OverLordGoldDragon** [comment]
`backend='torch17_skcuda'` yields

<details>
  <summary><b>output</b></summary>

```python
D:\Anaconda\envs\pyt\lib\site-packages\kymatio\scattering1d\backend\torch17_skcuda_backend.py:12: UserWarning: The function torch.fft is deprecated and will be removed in PyTorch 1.8. Use the new torch.fft module functions, instead, by importing torch.fft and calling torch.fft.fft or torch.fft.fftn. (Triggered internally at  ..\aten\src\ATen\native\SpectralOps.cpp:567.)
  fft = FFT(lambda x: torch.fft(x, 1, normalized=False),
Traceback (most recent call last):

  File "C:\Desktop\School\Deep Learning\DL_Code\seizure_preprocessing\untitled10.py", line 19, in <module>
    Scx = scattering(xt)

  File "D:\Anaconda\envs\pyt\lib\site-packages\torch\nn\modules\module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)

  File "D:\Anaconda\envs\pyt\lib\site-packages\kymatio\frontend\torch_frontend.py", line 23, in forward
    return self.scattering(x)

  File "D:\Anaconda\envs\pyt\lib\site-packages\kymatio\scattering1d\frontend\torch_frontend.py", line 121, in scattering
    out_type=self.out_type)

  File "D:\Anaconda\envs\pyt\lib\site-packages\kymatio\scattering1d\core\scattering1d.py", line 84, in scattering1d
    S_0_c = cdgmm(U_0_hat, phi[0])

  File "D:\Anaconda\envs\pyt\lib\site-packages\kymatio\backend\torch_backend.py", line 193, in cdgmm
    raise TypeError('Input and filter must be of the same dtype.')

TypeError: Input and filter must be of the same dtype.
```
</details>

**Comment by edouardoyallon** [comment]
torch17 too?

**Comment by OverLordGoldDragon** [comment]
```python
ImportError: Backend torch17 not found!
```

**Comment by OverLordGoldDragon** [comment]
Also just upgraded to `pytorch 1.8.0`, all errors the same (but didn't test master branch)

**Comment by edouardoyallon** [comment]
A bit of help with the PR(s) would be welcome, the team (including myself) is a bit overwhelmed with work - if u need access to my repo, lmk

**Comment by OverLordGoldDragon** [comment]
I'll it consider once time-freq scattering's ready for a vectorized 1D port. For one I'd suggest not supporting both `<=` and `>` pytorch versions, instead just requiring users to upgrade, since with PyTorch I don't think there's much reason not to, and supporting both can get quite messy.

**Comment by eickenberg** [comment]
> with PyTorch I don't think there's much reason not to

Apart from the current slow-down using the complex number type, of which I don't know what exactly could be causing it. Maybe @edouardoyallon  you now have some insight into this?

**Comment by OverLordGoldDragon** [comment]
@eickenberg Slower how? I just tested `fft`, multiplication, addition, and division of `complex64` and `complex128`, 1.7.1 vs 1.8.0, not seeing a difference.

<details>
  <summary>bench code</summary>

```python
import torch
import torch.fft as tfft
from timeit import timeit

def timer(fn, number=100):
    print(timeit(fn, number=number) / number)

x = torch.randn((300, 240000), dtype=torch.complex128, device='cuda') * (1 + 2j)
timer(lambda: tfft.fft(x, dim=-1))
timer(lambda: x * (2 - 1j) / (x**1.5 + 1))
```
</details>

**Comment by eickenberg** [comment]
Thanks for running that benchmark.
@edouardoyallon do you remember what caused a slow-down when benching complex numbers?
Maybe it is something that happened on the release candidate but not on the release?

**Comment by edouardoyallon** [comment]
> Thanks for running that benchmark.
> @edouardoyallon do you remember what caused a slow-down when benching complex numbers?
> Maybe it is something that happened on the release candidate but not on the release?

I'd love to run automatically a proper benchmark using asv. I'd like to isolate the slow part.
