### ISSUE TITLE
input tensor and filter torch device mismatch

### ISSUE THREAD

**Issue by rastegah** [kymatio/kymatio#715]
Hello @kymatio 

When using `Scattering1D` with the `torch` backend, in some instances I get the following error:

```~/venvs/nsf/lib/python3.8/site-packages/kymatio/scattering1d/core/scattering1d.py in scattering1d(x, pad, unpad, backend, J, psi1, psi2, phi, pad_left, pad_right, ind_start, ind_end, oversampling, max_order, average, size_scattering, vectorize, out_type)
     82 
     83     if average:
---> 84         S_0_c = cdgmm(U_0_hat, phi[0])
     85         S_0_hat = subsample_fourier(S_0_c, 2**k0)
     86         S_0_r = fft(S_0_hat, 'C2R', inverse=True)

~/venvs/nsf/lib/python3.8/site-packages/kymatio/backend/torch_backend.py in cdgmm(A, B, inplace)
    202     if B.device.type == 'cpu':
    203         if A.device.type == 'cuda':
--> 204             raise TypeError('Input must be on CPU.')
    205 
    206     if _is_real(B):

TypeError: Input must be on CPU.
```

My input is always on `cuda` - I'm assuming the issue is because the 0th order LPF coefficients are on `cpu`. However, I cannot find an explicit way to tell Kymatio to put these tensors on GPU. 

Note that this issue does not always arise when input tensors are on GPUs. Perhaps I am missing some configuration ...

Could we safely send wavelet tensors to the same device as the input tensor?

---

Thank you,

Cyrus

**Comment by lostanlen** [comment]
Hello @rastegah. Could you help us narrow down the issue by sharing your code? What is the size of your input?
Is the issue only in 1D or also in 2D?

Thanks

**Comment by OverLordGoldDragon** [comment]
Call `scattering.cuda()` before passing the input. We should make the error message mention this @kymatio

```python
from kymatio.torch import Scattering1D
import torch

T = 2048
scattering = Scattering1D(6, T, 16).cuda()

x = torch.randn(T, device='cuda')
out = scattering(x)
```

**Comment by rastegah** [comment]
@OverLordGoldDragon thanks that solved it - somehow this was handled automatically in other cases
