### ISSUE TITLE
Implementation and examples for DCT and PCA

### ISSUE THREAD

**Issue by tushar00jain** [kymatio/kymatio#741]
I was wondering if there's any plan to also include DCT in the mix to reduce the number of scattering coefficients and an implementation of classification using PCA affine subspace selection as mentioned in the paper?

**Comment by lostanlen** [comment]
Hello @tushar00jain
Here are some relevant links

DCT in TensorFlow: https://www.tensorflow.org/api_docs/python/tf/signal/dct
DCT in PyTorch: https://pypi.org/project/torch-dct/
DCT in NumPy: https://docs.scipy.org/doc/scipy/reference/generated/scipy.fft.dct.html

As you can see, all backends already provide an implementation, so we're not planning on adding DCT as a Kymatio primitive
