### ISSUE TITLE
Preallocation for speed

### ISSUE THREAD

**Issue by OverLordGoldDragon** [kymatio/kymatio#758]
I found a x1.7 speed gain via simple reused preallocation:

```python
U_1_c0 = zeros_like(U_0_hat)
for n1 in range(len(psi1)):
    cdgmm(U_0_hat, psi1[n1][0], out=U_1_c0)
    U_1_hat = subsample_fourier(U_1_c0, 2**K1)
    # etc
```
Runtime: `901ms -> 540ms`. This can repeat for other basic ops to speed up the entire pipeline.

The caveat is [breaking differentiability](https://stackoverflow.com/q/68043831/10133797) for torch. Workarounds include:

 - A) `differentiable=True` kwarg
 - B)  `try-except` to detect differentiable context at runtime and set internal flag

@lostanlen raises the concerns of (correct me if I'm wrong) 1) added kwarg; 2) increased testing complexity, requiring additional branches akin to additional backends. My response:

 1. Non-differentiability is a common use case and a kwarg is a small price to pay for 50%+ overall speedup. Worst case, there's B)
 2. Only tests explicitly for differentiability are affected, and there's only one in all of Kymatio: `test_differentiability_scattering()` in `test_torch_scattering1d.py`. All that's needed is setting a kwarg for this one test (or nothing with B) - and easy enough if there are more tests. This does not require additional testing branches, workflows, etc
     - Can add a `test_outputs_agree()` but that's again simple

What are your takes @janden @eickenberg ?

**Comment by eickenberg** [comment]
Was going to ask about differentiability.
The reasons we don't have much preallocation (or actually got rid of it) was because the deep learning packages didn't support it (which is odd, because it's not that hard - even Theano had `set_subtensor`).

So the kwarg you are suggesting is not one to be found in the DL packages, but rather one that we add, in order to turn this preallocation on and off?

I am all for speedups, but if this is the case, then it indeed adds a lot of complexity. Question is what our threshold factor is for being willing to incur that. 10x would definitely pass that threshold for me. <2x I'm a bit on the fence about

**Comment by eickenberg** [comment]
That said, our skcuda backend doesn't have differentiability either.

**Comment by OverLordGoldDragon** [comment]
> kwarg you are suggesting ... turn preallocation on and off?

Yes, but it need not be a kwarg; torch will raise an exception when one of inputs to an `out=` op has `requires_grad=True`, and we can catch this once and set an internal flag to disable further preallocation.

> adds a lot of complexity

For example?

**Comment by OverLordGoldDragon** [comment]
So, a kwarg isn't needed. It's as easy as `sc(x)` --> `preallocate = x.requires_grad` --> `scattering1d(x, ..., preallocate)`.

Code will look like:

```python
if preallocate:
    var0, var1, ... = zeros(), zeros(), ...
else:
    var0, var1, ... = None, None, ...

for n1 in ...:
    U_1_c = cdgmm(U_0_hat, psi1[n1][0], out=var0)
    ...
```
```python
def cdgmm(self, A, B, out=None):
    if out is None:
        # standard behavior
    else:
        multiply(A, B, out=out)
        return out
```
So all that changes in `core` is a few extra variables to hold `zeros` or `None`, done before any looping, and every op will have an `out=` added. For backends, every primitive gets an `out`. Clean and simple.

**Comment by lostanlen** [comment]
@eickenberg also worth noting that it's a 1.7x speed gain for the multiplication only. When combined with the cost of FFT and modulus, the speed gain is lower than that (around 1.3x)

**Comment by OverLordGoldDragon** [comment]
x1.6 is what I'm seeing

<img src="https://user-images.githubusercontent.com/16495490/124337892-fa4f5a00-dbb5-11eb-862f-3e1f292d7492.png" width="450">

and since dyadic FFT grows sublinearly, the befit grows for larger inputs. Further, since the effect is global, it's multiplicative with other speedups - so a x1.5 here with my x2 faster convs is a net speedup of x3.
