### ISSUE TITLE
Input length requirement

### ISSUE THREAD

**Issue by robertanto** [kymatio/kymatio#759]
Is it possible to modify the implementation of the scattering transform to avoid the need for a fixed-length input?

It could be very interesting if it can be done, especially in real-time audio analysis systems where the input length can change. For instance, a speech analysis tool.

**Comment by OverLordGoldDragon** [comment]
It's indeed a [planned feature](https://github.com/kymatio/kymatio/issues/305). For now the closest alternative is to generate several `Scattering1D` objects of different lengths, and pad inputs to match them, then unpad the output. E.g.

```python
import numpy as np
from kymatio.numpy import Scattering1D

def scatter(x):
    if len(x) > N0:
        assert len(x) <= N1
        to_pad = N1 - len(x)
        ts = ts1
    else:
        to_pad = N0 - len(x)
        ts = ts0
        
    xp = np.pad(x, [0, to_pad])  # not best pad scheme, just example
    out = ts(xp)
    
    stride = len(xp) // out.shape[-1]
    unpad = - to_pad // stride
    if unpad == 0:
        unpad = None
    return out[:, :unpad]

N0, N1 = 1024, 8192
ts0 = Scattering1D(shape=N0, J=6)
ts1 = Scattering1D(shape=N1, J=6)

for N in (800, 1000, 6000, 7000):
    x = np.random.randn(N)
    out = scatter(x)
    print("len(x) = {:<5} | out.shape = {}".format(len(x), out.shape))
```
```
len(x) = 800   | out.shape = (28, 12)
len(x) = 1000  | out.shape = (28, 15)
len(x) = 6000  | out.shape = (28, 93)
len(x) = 7000  | out.shape = (28, 109)
```

**Comment by robertanto** [comment]
Thank you for your answer, it is very useful.

I will wait for this feature! 

Is the dependency of the time that changes the time for creating the scattering layer? I report some results:

```
# Time needed to create an instance of the scattering function given an input of length equal to T (samples).

Numpy - T=1000 0.08490094661712647
Numpy - T=10000 0.705208249092102     # < 1 sec @ 16KHz

Tensorflow - T=1000 0.17213822841644288
Tensorflow - T=10000 0.9110619783401489 # < 1 sec @ 16KHz
```

**Comment by OverLordGoldDragon** [comment]
Yes: greater `shape` will create longer filters, which takes more time. This is done only once, then `ts` are reused.

**Comment by robertanto** [comment]
Ok. Thank you.

**Comment by robertanto** [comment]
I close the issue due to the duplication with #305
