### ISSUE TITLE
scikit-cuda install error

### ISSUE THREAD

**Issue by amiltonwong** [kymatio/kymatio#769]
Hi, all,

When I perform `pip install scikit-cuda`, I got the following error:
```
ERROR: Failed building wheel for pycuda
Failed to build pycuda
ERROR: Could not build wheels for pycuda which use PEP 517 and cannot be installed directly

```

Any hints to solve this issue?

Thanks~

**Comment by OverLordGoldDragon** [comment]
Hello, 

The relevant repository is [here](https://github.com/lebedov/scikit-cuda/issues).
