### ISSUE TITLE
`concatenate` & `stack`

### ISSUE THREAD

**Issue by OverLordGoldDragon** [kymatio/kymatio#771]
JTFS requires former, everything else in Kymatio uses latter. Options:

 1. `concatenate` & `stack` backend methods
 2. Single backend method that takes `stack` as boolean kwarg

Two ways to implement latter; A) use `stack` and `concatenate` directly; B) emulate `stack` via dim-expand + concatenate:

```python
def concatenate(cls, arrays, axis=1, stack=False):
    if stack:
        # emulate `np.stack`
        if axis < 0:
            slc = (slice(None),) * (arrays[0].ndim + axis + 1) + (None,)
        else:
            slc = (slice(None),) * axis + (None,)
        arrays = [a[slc] for a in arrays]
    return cls._np.concatenate(arrays, axis=axis)
```

 3. Do the dim expanding before passing into `backend.concatenate`, but that's unclean

Thoughts?

**Comment by lostanlen** [comment]
> JTFS requires former, everything else in Kymatio uses latter. 

Can you give us some context? I don't understand what the problem is.
