### ISSUE TITLE
Place for implementation notes

### ISSUE THREAD

**Issue by OverLordGoldDragon** [kymatio/kymatio#772]
`core/timefrequency_scattering1d.py` contains a docstring with detailed notes explaining implementation logic. It is [583 lines long](https://github.com/lostanlen/kymatio/blob/5869df48edc11265f26dce8d3ade8b7aca0a305e/kymatio/scattering1d/core/timefrequency_scattering1d.py#L11-L593).

While keeping it inserts a massive block before code, there's significant convenience to having it in the same file: no need to keep an extra file open, and more importantly, variable names highlighted in code will also be highlighted in the docstring without having to search manually. Some editors support docstring folding, which null the problem.

However, majority of the docstring (420 lines) explains stride computation, which is highly technical and mainly for devs. Same arguments apply, but less is lost by moving only this rather than everything.

What do we think? If moving, where to?

**Comment by MuawizChaudhary** [comment]
Stale
