### ISSUE TITLE
Fourier Subsampling?

### ISSUE THREAD

**Issue by robertanto** [kymatio/kymatio#778]
Why do we need to perform the subsampling in the frequency domain?

It seems from the original scattering transform that we just need to make the convolution and then a modulus.

```python3
U_1_c = cdgmm(U_0_hat, psi1[n1][0])
U_1_hat = subsample_fourier(U_1_c, 2**k1)
U_1_c = fft(U_1_hat, "C2C", inverse=True)

# Take the modulus
U_1_m = modulus_complex(U_1_c)

if average or max_order > 1:
    U_1_hat = fft(U_1_m, "C2C")

if average:
    # Convolve with phi_J
    k1_J = max(J - k1 - oversampling, 0)

    S_1_c = cdgmm(U_1_hat, phi[k1])
    S_1_hat = subsample_fourier(S_1_c, 2**k1_J)
    S_1_r = fft(S_1_hat, "C2R", inverse=True)

    S_1 = unpad(S_1_r, ind_start[k1_J + k1], ind_end[k1_J + k1])
```

**Comment by eickenberg** [comment]
It is not technically necessary, but leads to faster computation of order 2
and preserves all information, at least in the l2 sense, if the subsampled
wavelet transform was sufficiently band limited

**Comment by robertanto** [comment]
Thank you!
