### ISSUE TITLE
Time support of wavelets & time resolution

### ISSUE THREAD

**Issue by robertanto** [kymatio/kymatio#779]
Dear developers,

I am trying to in-depth understand the scattering transform while using it through the kymatio library.
I compared the first-order coefficients with the Mel Spectrogram to better understand the time resolution and I obtained the following result (mel and scattering transform are both log scaled):

Mel 32 ms window with 32 ms hop
![immagine](https://user-images.githubusercontent.com/23097044/132819822-4f07e520-d1c6-4e4d-987c-c6bddffdb364.png)

Scattering transform J=9 Q=8 (32 ms)
![immagine](https://user-images.githubusercontent.com/23097044/132819864-4d666590-8e16-44c8-b4f6-9a5db1bb31b1.png)

Scattering transform J=6 Q=8 (4 ms)
![immagine](https://user-images.githubusercontent.com/23097044/132819967-51bc0ec7-7103-4952-8db6-767bededb672.png)

As I understood from the documentation and from [here](https://it.mathworks.com/help/wavelet/ug/wavelet-scattering-invariance-scale-and-oversampling.html), the maximum time support of the wavelets within the filters is 2**J samples.
If this statement is true, it is strange that I need a maximum time support of 4 ms to obtain the same resolution of the mel spectrogram with 32 ms win.

Do I miss something?

**Comment by OverLordGoldDragon** [comment]
The Mel Spectrogram builds on STFT, whose kernel time-frequency resolution is fixed, while scattering builds on CWT, whose resolution varies exponentially: the two aren't directly comparable. What do you mean with `4 ms to obtain the same resolution of the mel spectrogram with 32 ms win`?

[This post](https://dsp.stackexchange.com/a/78513/50076) might help with scattering, and [these visuals](https://dsp.stackexchange.com/a/72044/50076) on resolution.

**Comment by robertanto** [comment]
> What do you mean with 4 ms to obtain the same resolution of the mel spectrogram with 32 ms win?

I am referring to the averaging window, in particular, to the ratio between the initial length of the signal and the final number of time steps.

**Comment by OverLordGoldDragon** [comment]
Marking as solved, feel free to reopen if further concerns.
