### ISSUE TITLE
Number of first order scattering coefficients 

### ISSUE THREAD

**Issue by robertanto** [kymatio/kymatio#780]
I am trying to understand the number of filters in the first layer of the scattering transform.

They should be J*Q filters, shouldn't they? When I compute the scattering transform with max_order=1 I obtain fewer coefficients.
Moreover, I expect a minimum centre frequency of 2**(-J) but if I plot the filters I find smaller centre frequencies.

Am I forgetting something?

Thank you in advance.

**Comment by lostanlen** [comment]
Hello @robertanto , this is explained in Deep Scatterin Spectrum, between Equations 12 and 13
https://arxiv.org/abs/1304.6763

**Comment by robertanto** [comment]
Thank you for the answer!

**Comment by OverLordGoldDragon** [comment]
[Further discussion](https://dsp.stackexchange.com/a/78515/50076) under "Filterbank implementation".
