### ISSUE TITLE
Reviewing `core` JTFS

### ISSUE THREAD

**Issue by OverLordGoldDragon** [kymatio/kymatio#785]
I recommend focusing on the "standard" variant:

 - `average=True; average_fr=True/False; aligned=True; out_3D=False; sampling_filters_fr='resample'; out_exclude=None`

All other code can be ignored (e.g. `if out_3D: ...`). This should cut code to under 25% of full size. The rest can be validated via `test_jtfs.py`.

### Pseudocode

Up to a spinned pair:

```python
# first order time scattering
U1 = []
for p1t in psi1_t:
    U1.append(abs(conv(x, p1t)))

# joint scattering
U2 = []
for p2t in psi2_t:
    # second order time scattering
    U2_tm = []
    for u1 in U1:
        U2_tm.append(conv(u1, p2t))
    U2_tm = array(U2_tm)  # shape == (freq, time)

    # frequential scattering
    for p1f in psi1_fr_up:
        U2.append(abs(conv(U2_tm, p1f, axis=-2)))
```
JTFS is exactly this, but with

 1. padding, unpadding
 2. lowpass filtering
 3. subsampling
 4. other joint pairs

Majority of complexity goes into 3; implementation subsamples as much as possible, ~losslessly, which is very complicated in light of all variants.

### Complete validation

The most complicated method, by far, is `_get_stride` in `timefrequency_scattering1d.py`; a 300+ line docstring dedicates to explaining it. Validating this requires familiarity with the entire implementation, and accounting for every possible kwarg combination.

The rest can be traversed in an exploratory fashion: picking a test signal, and tracking the output back to input - breakpointing into various stages, and printing all pertinent attributes and plotting intermediate outputs.

It's also helpful to familiarize with `compute_meta_jtfs`, which encodes the entire computational graph into a dictionary.

Lastly, majority of features are explained in depth in [Discussions](https://github.com/kymatio/kymatio/discussions) via my posts and discussions with @lostanlen. For those without an IDE preference, I recommend [Spyder](https://github.com/kymatio/kymatio/discussions/782).

**Comment by MuawizChaudhary** [comment]
Stale
