### ISSUE TITLE
reconstruct signal example fails

### ISSUE THREAD

**Issue by milchada** [kymatio/kymatio#787]
I went through plot_real_signal, and generated the scattering coefficients Sx. Then I tried to use reconstruct_signal to reproduce the original sound file. Even after converting x and Sx from the first example to torch-friendly tensors, I hit the folliowing error:
`TypeError                                 Traceback (most recent call last)
<ipython-input-183-245942b8469e> in <module>
----> 1 Sx = scattering(x)

~/miniconda3/lib/python3.9/site-packages/torch/nn/modules/module.py in _call_impl(self, *input, **kwargs)
   1100         if not (self._backward_hooks or self._forward_hooks or self._forward_pre_hooks or _global_backward_hooks
   1101                 or _global_forward_hooks or _global_forward_pre_hooks):
-> 1102             return forward_call(*input, **kwargs)
   1103         # Do not call functions when jit is used
   1104         full_backward_hooks, non_full_backward_hooks = [], []

~/miniconda3/lib/python3.9/site-packages/kymatio/frontend/torch_frontend.py in forward(self, x)
     21         input_checks(x)
     22 
---> 23         return self.scattering(x)
     24 
     25     _doc_array = 'torch.Tensor'

~/miniconda3/lib/python3.9/site-packages/kymatio/scattering1d/frontend/torch_frontend.py in scattering(self, x)
    112 
    113 
--> 114         S = scattering1d(x, self.backend.pad, self.backend.unpad, self.backend, self.J, self.psi1_f, self.psi2_f, self.phi_f,\
    115                          max_order=self.max_order, average=self.average,
    116                        pad_left=self.pad_left, pad_right=self.pad_right,

~/miniconda3/lib/python3.9/site-packages/kymatio/scattering1d/core/scattering1d.py in scattering1d(x, pad, unpad, backend, J, psi1, psi2, phi, pad_left, pad_right, ind_start, ind_end, oversampling, max_order, average, size_scattering, vectorize, out_type)
     82 
     83     if average:
---> 84         S_0_c = cdgmm(U_0_hat, phi[0])
     85         S_0_hat = subsample_fourier(S_0_c, 2**k0)
     86         S_0_r = fft(S_0_hat, 'C2R', inverse=True)

~/miniconda3/lib/python3.9/site-packages/kymatio/backend/torch_backend.py in cdgmm(A, B, inplace)
    191 
    192     if A.dtype is not B.dtype:
--> 193         raise TypeError('Input and filter must be of the same dtype.')
    194 
    195     if B.device.type == 'cuda':

TypeError: Input and filter must be of the same dtype.` 

As far as I can tell, the only input I have specified is x. What is going on?

**Comment by OverLordGoldDragon** [comment]
Please provide code to reproduce the error.

**Comment by redvox1** [comment]
Hi, had issue on same file with Mac OS Monterrey on M1 Pro Silicon chip with latest requirements, fixed it with:
history.append(err.detach().numpy())
If changing out x, verify type matches float32 as with original x in the example.

**Comment by OverLordGoldDragon** [comment]
Marking as solved, feel free to reopen with further information.
