### ISSUE TITLE
Make tests friendlier

### ISSUE THREAD

**Issue by OverLordGoldDragon** [kymatio/kymatio#793]
I ask Kymatio make tests more developer-friendly. That is, make each test file like `test_jtfs.py` at bottom.

Currently one must run them via a unit test suite like pytest, via a Python terminal. Even if one manages to run it via `pytest.main`, it'll still run the entire test, then print a grand report for us to look through.

There's a much better way. Execution can be stopped as soon as there's an exception, and we can jump directly to the offending line at any point of the stack trace with a click, by using an IDE. That's just one benefit - I created the [Spyder tutorial](https://github.com/kymatio/kymatio/discussions/782) for this reason. Much work goes into making IDEs that give power to and save time for developers.

Put directly, the current approach is a waste of time, and I'm not eager to do testing moving forward. Yes, it makes the testing code look a bit uglier, but if I didn't do it, I'd _still_ be working on JTFS.

@janden @eickenberg

**Comment by rastegah** [comment]
you should consider that not everybody uses an IDE. this implies that everyone wants to work this way. some are content with `pdb`. 

i don't think this would make it to `main`. it's too risky and messy ... 

You can still do this without making it a feature? All you have to do is paste that conditional block to execute the tests you want

**Comment by OverLordGoldDragon** [comment]
> some are content with pdb

This doesn't affect `pdb` users.

> All you have to do is paste that conditional block to execute the tests you want

That's much work to do each time.

Kymatio is free to remove it after JTFS is merged. I ask it be in effect at least while we review and test. But if my input on tests isn't needed, by all means.
