### ISSUE TITLE
JTFS mess

### ISSUE THREAD

**Issue by OverLordGoldDragon** [kymatio/kymatio#796]
Long story short, I made a significant mistake in implementation that affects all configurations. Namely, unpadding and striding along frequency, in freq scattering. My bad.

Good news is, only `aligned=False` and `'recalibrate'` are severely affected. `aligned=True` and `'resample'` may oversample for non-smallest `N_frs`, and `out_3D=False` may unpad incorrectly. It's possible, and likely, that `True` and `'resample'` work entirely correctly for a given config, just not guaranteed. Implications are "excess data" and "some info lost", and latter should be negligible in most cases.

I will fix it, hopefully soon. I'll open it as a PR to #781, write a summary of changes to guide reviewers, and take any questions. For now, `'resample'` and `aligned=True` should work well enough.

@lostanlen @rastegah @lylyhan @changhongw

**Comment by OverLordGoldDragon** [comment]
Actually I think `aligned=True` && `'resample'` is completely fine. To be sure, add the following in `core/timefrequency_scattering1d.py`:

```python
    # sanity checks (see "Subsampling, padding") #############################
    if aligned and not global_averaged_fr:
        # if `average_fr and sampling_filters_fr == ('resample', 'resample')`
        assert (stride_ref if out_3D else _stride) == scf.log2_F - oversampling_fr
```

**Comment by OverLordGoldDragon** [comment]
Had to nearly completely overhaul JTFS. In interest of time, I'm sharing what's ready: all tests pass (np/torch), but I can't guarantee it's actually good to go: [LINK](https://github.com/lostanlen/kymatio/pull/30) -- If possible, I recommend trying this variant on existing experiments - it's a drop-in, except the output shape may be a bit different. Didn't update all `toolkit`/`visuals`, so let me know if anything that's needed broke, I'll prioritize.

Good news for reviewers is, it's simply a corrected re-execution of same design objectives, and this variant is vastly easier to understand. Though, it's still a lot new code. I'll complete the code and write a report, then we decide how to proceed.

Lastly, this is a fork of the JTFS I've been developing further privately, and includes a substantial FDTS sensitivity and info preservation enhancement, as well as `J=(J1, J2)` (for `J2 <= J1`) and `paths_exclude` (i.e. #791; e.g. ` = {'n2': (3, 4)}`). Don't plan on keeping latter two for the review, but they're there now, and work correctly as far as I can tell.

Let me know if any questions.

@lostanlen @rastegah @lylyhan @changhongw

**Comment by MuawizChaudhary** [comment]
> Had to nearly completely overhaul JTFS. In interest of time, I'm sharing what's ready: all tests pass (np/torch), but I can't guarantee it's actually good to go: [LINK](https://github.com/lostanlen/kymatio/pull/30) -- If possible, I recommend trying this variant on existing experiments - it's a drop-in, except the output shape may be a bit different. Didn't update all `toolkit`/`visuals`, so let me know if anything that's needed broke, I'll prioritize.
> 
> Good news for reviewers is, it's simply a corrected re-execution of same design objectives, and this variant is vastly easier to understand. Though, it's still a lot new code. I'll complete the code and write a report, then we decide how to proceed.
> 
> Lastly, this is a fork of the JTFS I've been developing further privately, and includes a substantial FDTS sensitivity and info preservation enhancement, as well as `J=(J1, J2)` (for `J2 <= J1`) and `paths_exclude` (i.e. #791; e.g. ` = {'n2': (3, 4)}`). Don't plan on keeping latter two for the review, but they're there now, and work correctly as far as I can tell.
> 
> Let me know if any questions.
> 
> @lostanlen @rastegah @lylyhan @changhongw


How is the report coming along?  I assume that currently we are waiting until you have incorporated these changes into #781? Please correct me if I am wrong.

**Comment by lostanlen** [comment]
This seems like a priority issue. Let's work on getting it closed (possibly discussing on the Discord server)
