### ISSUE TITLE
STFT too thin

### ISSUE THREAD

**Issue by OverLordGoldDragon** [kymatio/kymatio#800]
The non-CQT portion routinely under-tiles

<img src="https://user-images.githubusercontent.com/16495490/159599961-9ef21996-612b-4cdf-9a37-0870d260edd4.png" width="700">

so parts of input are attenuated - bad news where low frequencies matter, which is always for second-order scattering (and JTFS). Increasing the number of said filters fixes this: `num_intermediate = Q - 1` -> `Q` (`filter_bank.compute_params_filterbank`):

<img src="https://user-images.githubusercontent.com/16495490/159600274-fd41d283-a8f6-4fb5-b44c-fd4f47d74baf.png" width="700">

Note for `Q=1` we added an entire wavelet while changing nothing else, and it fit right in, suggesting we're missing an entire wavelet.

Worst case on performance is with `Q=1`; one extra wavelet at second order with `Q2=1` is a small compute overhead since it's a large kernel convolution (max stride), and not a memory overhead since we can discard it if we wish. Larger `Q` has negligible overhead in any sense. I recommend this as the new default.

**Comment by OverLordGoldDragon** [comment]
Turns out the frequency domain can be misleading and we may even be okay with zero coverage depending on padding... need to rethink

**Comment by OverLordGoldDragon** [comment]
Indeed zero coverage is fine, but only in the _padded_ region. Discussed [here](https://github.com/kymatio/kymatio/pull/737#issuecomment-1079602056), but no verdict on this Issue yet; had to resolve `xi_min` per design decision in JTFS.

**Comment by MuawizChaudhary** [comment]
@janden reopen if needed
