### ISSUE TITLE
General TODOs

### ISSUE THREAD

**Issue by OverLordGoldDragon** [kymatio/kymatio#802]
To avoid opening lots of Issues I'll just comment here, and comments can be converted to Issues if needed. If they're already Issues then I don't put them here. These can wait until after JTFS is merged or mostly reviewed to avoid increasing workload. First two:

### ~~1. False docs: `J`~~ done

```
The maximum log-scale of the scattering transform. In other words,
the maximum scale is given by :math:`2^J`
```
`J` and `j` are not scale. They are maximum permitted subsampling, which is related to scale, but can be very different from. 

Scale is a function of `J`, `Q`, `r_psi`, and `xi` (for `xi` near 0), and indirectly of `sigma0` and `criterion_amplitude`. Namely, the "direct" params determine [`'width'`](https://github.com/kymatio/kymatio/pull/766), and `'width'` is defined in terms of `phi`, which is built via the "indirect". I recommend 

```
Controls the maximum log-scale and number of octaves of the scattering transform. There 
are approx. `Q` wavelets per octave, and bandwidth halves with each octave. Hence, largest 
scale wavelet is about `2**J` larger than smallest scale wavelet.
```

### 2. `'scale'` meta

Per 1, it'd be neat to have a `'scale'` meta and color the filter plots in terms of those instead of `'j'`, as information on `'j'` is already conveyed by black vertical bars marking dyadic scales. 

It'd be computed by centering `psi_f` at dc in Fourier then applying `compute_temporal_support` logic on it, i.e. finding first point to drop below `psi_f.max() * criterion_amplitude`, converted to scale via `log2(len(psi_f) // 2 // result)` (this is by how much we can subsample, and directly computes `T` and `log2_T` for `phi_f` - rather, that's how they're defined to begin with).

### ~~3. Extend docs: `J`~~ done

```
...
Greater `J` extends time-warp stability to lower frequencies, and other desired properties,
as greater portion of the transform is CQT (fixed `xi` to `sigma` ratio and both exponentially
spaced, as opposed to fixed `sigma` and linearly spaced `xi`).
```

**Comment by MuawizChaudhary** [comment]
@janden I'm closing, please reopen if needed.
