### ISSUE TITLE
HarmonicScattering3D should output real coefficients (Numpy)

### ISSUE THREAD

**Issue by janden** [kymatio/kymatio#811]
Currently this outputs coefficients with dtype `complex64` (or `complex128`) but have zero imaginary part. Should be `float32` (or `float64`).

**Comment by MuawizChaudhary** [comment]
Lack of testing in the 3D frontend code ultimately led to this problem (see #337)

**Comment by MuawizChaudhary** [comment]
Hi, It seems like its outputing `float32`. in the torch backend. Is this issue occurring for the numpy?
