### ISSUE TITLE
Examples fail

### ISSUE THREAD

**Issue by edouardoyallon** [kymatio/kymatio#817]
Hi, I'm just noticing that many examples of the repo (e.g. https://www.kymat.io/gallery_2d/plot_invert_scattering_torch.html#sphx-glr-gallery-2d-plot-invert-scattering-torch-py which doesn't recover the original image or the scattering disk which makes no sens given the image&scattering features https://www.kymat.io/gallery_2d/plot_scattering_disk.html#sphx-glr-gallery-2d-plot-scattering-disk-py ) fail to achieve what they claim to do - I think it's a bit crucial to fix, as these are literally the showcase of the package, which is thus not really convincing, or even sounds wrong.

**Comment by MuawizChaudhary** [comment]
@edouardoyallon @anakin-datawalker 

I'm not sure what is the fix to to scattering disk. do you have an image of what is supposed to be shown there/whats the correct/expected output? 

It looks to be pretty similar to Joan Bruna's figure from their seminal Invariant Scattering Networks paper. 

![image](https://user-images.githubusercontent.com/39755015/171216834-d8666d57-284a-449e-b300-c2283c5614d0.png)

![image](https://user-images.githubusercontent.com/39755015/171217732-f43cf1fc-b4c1-4102-b50f-b93a2ac3560c.png)

**Comment by MuawizChaudhary** [comment]
@edouardoyallon  @anakin-datawalker  This seems hard. It seems like the ordering might be different than what's shown in Bruna's paper. The oscillations are a bit confusing. Is the ordering of our coefficents different than Bruna's original presentation? 

[Here is my notebook.](https://colab.research.google.com/drive/1jacon162Xtg0PKapC07AGAPbCMupaXG7?usp=sharing) To get the angles to better match, I simply negate the angle. 

Here I plot the first order disk. The first image is my regeneration of the disk for first order, second image is Bruna's disk from the paper. I was able to get most of the angles to match, but there are differences. 
![image](https://user-images.githubusercontent.com/39755015/171493828-9615619b-62f1-48a9-a1a7-31a6c0ffbb15.png)
![image](https://user-images.githubusercontent.com/39755015/171493855-494284a1-2334-47b4-8caa-5d4e293de66e.png)

Here I plot the second order disk. The first image is my regeneration of the disk for second order, second image is Bruna's disk from the paper. I'm wondering if the spacing is too close. 

![image](https://user-images.githubusercontent.com/39755015/171494914-9b928222-e34d-449e-a73b-bd854d0b4641.png)
![image](https://user-images.githubusercontent.com/39755015/171494858-487630fe-bcbe-4041-b3db-b7027b98e31a.png)

**Comment by MuawizChaudhary** [comment]
I tested out example recontruct_torch.py, [it fails.](https://colab.research.google.com/drive/13HHEwMZvPL1VqyIhyZzcc_hedRTOjgJj?usp=sharing). I'll submit a pull request fixing it soon enough.

**Comment by MuawizChaudhary** [comment]
Using 50 epochs in the script here are the results for 

J=2
![image](https://user-images.githubusercontent.com/39755015/171545912-2f6fb73a-bdff-43f4-9045-a661b02ddd25.png)
J=4 
![image](https://user-images.githubusercontent.com/39755015/171546035-f7595417-6d00-48d9-b4da-e9e9c3aaff84.png)

OG image for comparison.
![image](https://user-images.githubusercontent.com/39755015/171546194-902b5786-9c3c-46d3-b5a0-d646cf73757d.png)


It takes about 3 minutes and 25 seconds to generate both. I suggest we remove J=4 and just use J=2 for the example. This will take 1 minute and 9 seconds. 

What do you think Dr. Oyallon?

**Comment by edouardoyallon** [comment]
It's good

**Comment by edouardoyallon** [comment]
the disks are however quite different .. 👎 might be difficult to fix
