### ISSUE TITLE
`morlet_1d` and `gauss_1d` should be simpler

### ISSUE THREAD

**Issue by lostanlen** [kymatio/kymatio#825]
In a previous unmerged PR (#514), i suggested to remove `normalize`, `Pmax`, and `eps`  from 1D filterbank construction. I doubt anyone uses non-default values. So we could replace them by constants: `normalize="l1"`, `Pmax=5`, `eps=` machine precision. Furthermore, gauss1d and morlet1d could be unified into a single function.

@MuawizChaudhary has suggested to revive this PR. This will be backwards compatible.

**Comment by MuawizChaudhary** [comment]
+1 in support of this. would be nice to have for 0.3 release.

**Comment by janden** [comment]
Agree. I don't even remember what these parameters were for.
