### ISSUE TITLE
`precompute_size_scattering` should always return a tuple (`detail=False`)

### ISSUE THREAD

**Issue by lostanlen** [kymatio/kymatio#838]
Came up in conversation with @MuawizChaudhary 

The `detail` kwarg in `precompute_size_scattering` isn't really justified:
* it is `True` by default
* it creates type instability (`int` or `tuple`)
* getting the `False` version is trivial: it suffices to call `sum` on the output
* our object-oriented method `self.output_size`, has `detail=False` by default. I suggest removing that kwarg and simply summing across orders after calling `precompute_size_scattering`

Hence i propose to remove it. The only occasion where we need `self.output_size()` in the codebase is in the Keras frontend. 
Perhaps we can set up a helpful error message if people ever call the non-default: `self.output_size(detail=True)`, telling them to call `self.meta()` instead?

**Comment by MuawizChaudhary** [comment]
I agree alot with having a tuple output, and also agree with the idea of calling sum on the tuple output if need be. We need to be careful about erroneously counting order 2 scattering coefficients when there arent any; a test can provide a check of correctness. 

I don't believe we should add a error message.

**Comment by lostanlen** [comment]
So should we keep accommodating both `self.output_size(detail=True)` and `self.output_size(detail=False)` ?

**Comment by MuawizChaudhary** [comment]
`self.output_size(detail=False)`.

**Comment by lostanlen** [comment]
That's a breaking change, but OK

**Comment by MuawizChaudhary** [comment]
If you think its a good idea, we can add a error message stating that we removed `detail=True`. 

I wouldn't expect many users to have used `self.output_size`. however. Personally, I think we should have a variable in `Scattering1D` that holds the size of the scattering, and this variable should be named `num_coefficents` or something like that.

**Comment by lostanlen** [comment]
> If you think its a good idea, we can add a error message stating that we removed detail=True.

Then, i suggest we go with the breaking change, release v0.3, and if anyone complains about `output_size() got an unexpected keyword argument 'detail'`, i'll write a helpful error message for v0.3.1. Deal?

**Comment by MuawizChaudhary** [comment]
Sounds like a plan : )

**Comment by janden** [comment]
> Then, i suggest we go with the breaking change, release v0.3, and if anyone complains about `output_size() got an unexpected keyword argument 'detail'`, i'll write a helpful error message for v0.3.1. Deal?

Sounds good to me.



> I disagree. If it's a variable in the state of the program, then potentially people can modify/delete it, which will lead to antipatterns and strange hacks. Whereas making it the return value of a method (`self.output_size()`) prevents that problem. I see this method as a "getter" on a private field.

Yes let's not mix styles here. We already have `meta` as a function, so the same should be true of `output_size`. I see @MuawizChaudhary's point about the need for the function (technically all the information is already in `meta`), but it's still useful to have as a shorthand for `len(scattering.meta)` or something similar.

**Comment by janden** [comment]
So just to make sure I've got this right, `precompute_size_scattering` will fix `detail=True` and `output_size` will fix `detail=False`?

**Comment by lostanlen** [comment]
> So just to make sure I've got this right, precompute_size_scattering will fix detail=True and output_size will fix detail=False?

Yes, that's what we just said ... but that would remove useful functionality, namely the `out_size(detail=True)` non-default. So i'm no longer in favor of it (at first, i believed that `out_size()` was currently `detail`-ed by default, but the opposite is true)

Looking back at it, i don't think there's much to be done here, except maybe removing the confusing `detail` keyword argument from `precompute_size_scattering`, and doing the summation inside `out_size`. This will be fully backwards compatible and will reduce the number of conditional branches in unit tests.

**Comment by janden** [comment]
All right. Works for me.

**Comment by lostanlen** [comment]
closed by #878
