### ISSUE TITLE
`scattering_filter_factory` should not return `t_max_phi`

### ISSUE THREAD

**Issue by lostanlen** [kymatio/kymatio#840]
Right now `scattering_filter_factory` in `filter_bank.py` does two things:
(1) construct Morlet 1D filterbanks
(2) compute the temporal support of phi (via external function `compute_temporal_support`), called `t_max_phi`

Yet, at no point in the code do we need both of these informations at once.
We need `t_max_phi` to estimate `min_to_pad` in `self.build()`
And then we pass that `min_to_pad` (under the form of a `J_pad`) to `self.create_filters()`, which itself calls `scattering_filter_factory` and discards the `t_max_phi` return value.

With @MuawizChaudhary we've realized that these two can be decoupled. My plan for this is to add these two lines of code to `Scattering1D.build` in the base frontend:
```python
phi_f = gauss_1d(self.N, self.sigma0/self.T)
min_to_pad = 3 * compute_temporal_support(phi_f.reshape(1, -1), criterion_amplitude)
```

* Net reduction in LOC count
* Simplification of the `scattering1d/filter_bank` module
* Faster `Scattering1D` constructor
* no more `criterion_amplitude` being passed to `scattering_filter_factory`
* no more `compute_minimum_support_to_pad`
* Backwards compatible as far as frontends are concerned

**Comment by lostanlen** [comment]
Note that this `min_to_pad` definition is very ad hoc and is problematic if `T` is very low, or `Q` very high, `self.sigma0` very high, or `criterion_amplitude` very high, or ... 

but this is besides the scope of this issue. here i'm only trying to decouple functionalities to ease up future maintenance.

**Comment by janden** [comment]
Agreed. We should aim to decouple these things as much as possible.
