### ISSUE TITLE
`calibrate_scattering_filters` is unnecessary

### ISSUE THREAD

**Issue by lostanlen** [kymatio/kymatio#849]
`calibrate_scattering_filters` is probably my least favorite function from `filter_bank.py`. It it called only ~once~ thrice, and has no units test. It has six inputs, seven (!) outputs, and only five lines of code. (and 50 lines of docs!)

In the spirit of #513, i suggest we remove it and have  `scattering_filter_factory` call `compute_filter_params` directly.

**Comment by janden** [comment]
What does it do (or what is it supposed to do)?

**Comment by MuawizChaudhary** [comment]
This issue was solved by #850. 

Closing.
