### ISSUE TITLE
`ScatteringBase1D` kwargs should be passed via `dict`'s 

### ISSUE THREAD

**Issue by lostanlen** [kymatio/kymatio#851]
from the `ScatteringBase1D` frontend to `compute_meta_scattering`, `precompute_size_scattering`, and `scattering_filter_factory`

This `dict` could be named `filterbank_kwargs` and eventually also contain the `spinned` boolean (#807)

This will lead to a reduction in the number of positional arguments in these prototypes. More importantly, it will better decouple hyperparameters from the choice of wavelet shape.

For me to be able to start working on this, i need #833 #842 #848 #850 to be reviewed, rebased, and merged.

**Comment by lostanlen** [comment]
Update: a more concise version that should work out of the box in v0.3:

```python
def scatnet_generator(J, Q, r_psi, sigma0):
    xi = compute_xi_max(Q)
    sigma = compute_sigma_psi(xi, Q, r=r_psi)
    sigma_min = sigma0 / 2**J

    if sigma <= sigma_min:
        xi = sigma
    else:
        yield xi, sigma
        # High-frequency (constant-Q) region: geometric progression of xi
        while sigma > (sigma_min * math.pow(2, 1 / Q)):
            xi /= math.pow(2, 1 / Q)
            sigma /= math.pow(2, 1 / Q)
            yield xi, sigma

    # Low-frequency (constant-bandwidth) region: arithmetic progression of xi
    for q in range(Q):
        xi -= 1/Q
        yield xi, sigma_min


def scattering_filter_factory(N, Js, Qs, T, generators, filters):
    lowpass, wavelets = filters[0], filters[1:]
    filterbanks = []
    n_resolutions = 1
    for J, Q, generator, wavelet in zip(Js, Qs, generators, wavelets):
        generator_fn, generator_kwargs = generator
        wavelet_fn, wavelet_kwargs = wavelet
        filterbank = []
        max_j = 0
        xi_sigmas = generator_fn(J, Q, **generator_kwargs)
        for n, (xi, sigma) in enumerate(xi_sigmas):
            j = get_max_dyadic_subsampling(xi, sigma, **wavelet_kwargs)
            psi_f = {0: wavelet_fn(N, xi, sigma, **wavelet_kwargs),
                "xi": xi, "sigma": sigma, "j": j, "n": n}
            for k in range(1+n_resolutions):
                psi_f[k] = periodize_filter_fourier(psi_f, n_periods=2**k)
            filterbank.append(psi_f)
            max_j = max(max_j, j)
        n_resolutions = max(n_resolutions, max_j)
        filterbanks.append(filterbank)

    lowpass_fn, lowpass_kwargs = lowpass
    log2_T = math.floor(math.log2(T))
    phi_f = {0: lowpass_fn(N, T, **lowpass_kwargs), "j": log2_T}
    for k in range(1+n_resolutions):
        phi_f[k] = periodize_filter_fourier(phi_f, n_periods=2**k)

    return phi_f, *filterbanks


def create_filters(self):
    sigma0 = 0.1
    r_psi = sqrt(0.5)
    generators = (
        (scatnet_generator, {"r_psi"}),
        (scatnet_generator, {"r_psi"})
    )
    filters = (
        (gauss_1d, {"sigma0": sigma}),
        (morlet_1d, {"r_psi": r_psi}),
        (morlet_1d, {"r_psi": r_psi})
    )
    self.phi_f, self.psi1_f, self.psi2_f = scattering_filter_factory(
        N, J, Q, T, generators, filters)
```

Note that the last function prepares for a number of features that could happen in v0.4 if we deem it useful:
* switching wavelet types
* varying r_psi per order
* varying wavelet type per order
* having more than two orders
* replacing the `scatnet_generator` by something else

**Comment by janden** [comment]
Looks reasonable, but why the references to `scatnet`? Do these reproduce the exact filters used in that toolbox?

Also why the choice of generators instead of lists? What do we gain from it? It seems simpler to me to use lists (which is also what's used elsewhere in the codebase AFAIK).

Finally I like the idea of skipping the filterbank construction that you show at the end, but it might be cleaner to just have two functions: one which generates the parameters of the filters (essentially coupling the generators you've defined) and another that takes the output and generates the actual filters. This means one (simpler) call if we just want the metadata and two calls if we want the filters (which is one more than before, but I think it's ok).

**Comment by lostanlen** [comment]
> why the references to scatnet? Do these reproduce the exact filters used in that toolbox?

It doesn't reproduce the value of the filters, but it's reproducing this algorithm of:
* starting from a xi_max / sigma_max pair
* updating both in a geometric sequence so that their ratio is preserved
* up until the sigma reaches a predefined sigma_low (i.e. time support ~T)
* then fill up the spectrum with equally spaced band-pass filters of bandwidth=sigma_low

This is what i'm proposing we call `scatnet_filterbank`. Part of me wanted to name it the `anden_filterbank` initially but i wasn't sure if you'd accept the shout out :D 


> Also why the choice of generators instead of lists? What do we gain from it? It seems simpler to me to use lists (which is also what's used elsewhere in the codebase AFAIK).

In this context, what we gain is code simplicity. We don't worry about initializing lists to `[]` and calling `.append` on each of them, only to `return` the fully formed lists. We just `yield` stuff as we go. In other contexts, generator can help save memory and customize/generalize the code more easily. @eickenberg would be far more eloquent than me on this matter. I don't feel very strongly about it, i just figured it was elegant (and a good exercise for myself in using the `yield` statement)


> Finally I like the idea of skipping the filterbank construction that you show at the end [...]

Thanks. This is the biggest selling point for me: not having to hack together a `compute_meta_scattering` and a `precompute_size_scattering`, because that's relatively error-prone and might have weird corner cases. Ideally this `compute_meta_scattering` would take the form of a "dry run" on the scattering transform itself. Same for `precompute_size_scattering` which would be nothing else than a counter on the metas.

> [...] but it might be cleaner to just have two functions: one which generates the parameters of the filters (essentially coupling the generators you've defined) and another that takes the output and generates the actual filters). This means one (simpler) call if we just want the metadata and two calls if we want the filters (which is one more than before, but I think it's ok).

Really interesting. What would be the output format of the first function?
What you describe sounds close to `calibrate_scattering_filters` but the issue i take with that function is that going from its output (`sigma_low, xi1, sigma1, j1, xi2, sigma2, j2`) to predict `meta` is quite involved: one has to mimick a scattering transform by running a depth-first search, check for `j1 < j2`, keep track of eight iterated variables at once (four per order), etc. That sounds benign for order-2 Scattering1D but i'm afraid that the same mimicry approach would be awfully tedious to maintain for more advanced algorithms like JTFS. So i'm looking for ways to avoid having to write all this code by hand and instead rely on core `scattering` with "empty" filters (metadata but no coefficients) so as to implement `precompute_scattering_meta` in a way that's more resilient to bugs and breaking changes.

@janden would you like to elaborate on what you're proposing?

**Comment by lostanlen** [comment]
@janden here's the "dry run" i have in mind. In `ScatteringBase1D.meta` (or its callee `compute_meta_scattering`), locally define

```python
class DryBackend:
    cdgmm = lambda *args: None
    fft = lambda *args: None
    ifft = lambda *args: None
    irfft = lambda *args: None
    subsample_fourier = lambda *args: None
```

and then call `core.scattering(None, DryBackend(), psi1, psi2, phi)` to obtain an `out_S` list (or generator!) of dicts in which all `coef`'s are `None` but their ordering and metadata is consistent with the real McCoy (namely TF/PT/NP backends).

I'm realizing that for that to happen, i actually don't need to modify the scattering filter factory. Just to make sure that `core.scattering` would accept `DryBackend()` as second argument.

The initial topic of this issue was more: how to make scattering filter factory accept spinned wavelets in the near future, and non-Morlet wavelets in the more long-term future. But maybe that's not as much a high priority as thinning down the code base of `utils.compute_meta_scattering`

**Comment by cyrusvahidi** [comment]
> Update: i believe it would be good to bundle the input arguments to `scattering_filter_factory` in terms of whether they relate to the filterbank discretization (xi's and sigma's), to the design/periodization of wavelets, or to the design/periodization of the low-pass filter.
> 
> We could expose this by means of three read-only properties in the base frontend:
> 
> ```python
> @property
> def filterbank(self):
>     return (scatnet_filterbank, {"r_psi": self.r_psi, "spinned": False})
> 
> @property
> def lowpass(self):
>     return (gauss_1d, {"sigma0": self.sigma0})
> 
> @property
> def wavelet(self):
>     return (morlet_1d, {"alpha": self.alpha, "max_subsampling": None})
> ```
> 
> where `scatnet_filterbank` is `compute_params_filterbank` under a new name, and without the third output argument. (the above is post- #832 but keywords `P_max`, `eps`, and `normalize` could live in these dictionaries!)
> 
> Those properties are a tuple of two elements, where the first element is callable and the second is a dictionary of kwargs for that callable.
> 
> Hence a cleaner prototype and control flow for `scattering_filter_factory`: (post #840 )
> 
> ```python
> def psi_factory(N, J, Q, wavelet, filterbank, n_resolutions):
>     filterbank_fn, filterbank_kwargs = filterbank
>     xis, sigmas = filterbank_fn(J, Q, **filterbank_kwargs)
>     wavelet_fn, wavelet_kwargs = wavelet
>     psis_f = []
>     for (xi, sigma) in zip(xis, sigmas):
>         j = get_max_dyadic_subsampling(xi, sigma, **wavelet_kwargs)
>         psi_f = {
>             0: wavelet_fn(N, xi, sigma, **wavelet_kwargs),
>             "xi": xi,
>             "sigma": sigma,
>             "j": j,
>         }
>         for k in range(1, n_resolutions):
>             psi_f[k] = periodize_filter_fourier(psi_f[0], 2**k)
>         psis_f.append(psi_f)
>     return psis_f
> 
> 
> def phi_factory(N, T, filterbank, lowpass, n_resolutions):
>     lowpass_fn, lowpass_kwargs = lowpass
>     log2_T = math.floor(math.log2(T))
>     phi_f = {
>         0: lowpass_fn(N, T, **lowpass_kwargs),
>         "xi": 0,
>         "sigma": sigma_low,
>         "j": log2_T,
>     }
>     for k in range(1, n_resolutions):
>         phi_f[k] = periodize_filter_fourier(phi_f[0], 2**k)
>     return phi_f
>     
> def scattering_filter_factory(N, J, Q, T, filterbank, lowpass, wavelet):
>     # First order
>     psi1s_f = psi_factory(N, J, Q, wavelet, filterbank, n_resolutions=1)
> 
>     # Second order
>     n_psi2_resolutions = max(map(itemgetter("j"), psi1s_f))
>     psi2s_f = psi_factory(N, J, 1, wavelet, filterbank, n_psi2_resolutions)
> 
>     # Low-pass filter
>     n_phi_resolutions = max(n_psi1_resolutions, max(map(itemgetter("j"), psi2s_f)))
>     phi_f = phi_factory(N, T, lowpass, filterbank, n_phi_resolutions)
> 
>     return phi_f, psi1s_f, psi2s_f
> ```
> 
> This is `spinned`-friedly (#807), is backwards compatible (v0.3!), and would open the door towards revisiting #385 (by @rleonarduzzi ) and Gammatone filters. By allowing the user to specify `self.wavelet` in the 1D constructor (long-term plan).

love the flexible choice of wavelet function here. will consider the best way to implement!

**Comment by cyrusvahidi** [comment]
> Update: a more concise version that should work out of the box in v0.3:
> 
> ```python
> def scatnet_generator(J, Q, r_psi, sigma0):
>     xi = compute_xi_max(Q)
>     sigma = compute_sigma_psi(xi, Q, r=r_psi)
>     sigma_min = sigma0 / 2**J
> 
>     if sigma <= sigma_min:
>         xi = sigma
>     else:
>         yield xi, sigma
>         # High-frequency (constant-Q) region: geometric progression of xi
>         while sigma > (sigma_min * math.pow(2, 1 / Q)):
>             xi /= math.pow(2, 1 / Q)
>             sigma /= math.pow(2, 1 / Q)
>             yield xi, sigma
> 
>     # Low-frequency (constant-bandwidth) region: arithmetic progression of xi
>     for q in range(Q):
>         xi -= 1/Q
>         yield xi, sigma_min
> 
> 
> def scattering_filter_factory(N, Js, Qs, T, generators, filters):
>     lowpass, wavelets = filters[0], filters[1:]
>     filterbanks = []
>     n_resolutions = 1
>     for J, Q, generator, wavelet in zip(Js, Qs, generators, wavelets):
>         generator_fn, generator_kwargs = generator
>         wavelet_fn, wavelet_kwargs = wavelet
>         filterbank = []
>         max_j = 0
>         xi_sigmas = generator_fn(J, Q, **generator_kwargs)
>         for n, (xi, sigma) in enumerate(xi_sigmas):
>             j = get_max_dyadic_subsampling(xi, sigma, **wavelet_kwargs)
>             psi_f = {0: wavelet_fn(N, xi, sigma, **wavelet_kwargs),
>                 "xi": xi, "sigma": sigma, "j": j, "n": n}
>             for k in range(1+n_resolutions):
>                 psi_f[k] = periodize_filter_fourier(psi_f, n_periods=2**k)
>             filterbank.append(psi_f)
>             max_j = max(max_j, j)
>         n_resolutions = max(n_resolutions, max_j)
>         filterbanks.append(filterbank)
> 
>     lowpass_fn, lowpass_kwargs = lowpass
>     log2_T = math.floor(math.log2(T))
>     phi_f = {0: lowpass_fn(N, T, **lowpass_kwargs), "j": log2_T}
>     for k in range(1+n_resolutions):
>         phi_f[k] = periodize_filter_fourier(phi_f, n_periods=2**k)
> 
>     return phi_f, *filterbanks
> 
> 
> def create_filters(self):
>     sigma0 = 0.1
>     r_psi = sqrt(0.5)
>     generators = (
>         (scatnet_generator, {"r_psi"}),
>         (scatnet_generator, {"r_psi"})
>     )
>     filters = (
>         (gauss_1d, {"sigma0": sigma}),
>         (morlet_1d, {"r_psi": r_psi}),
>         (morlet_1d, {"r_psi": r_psi})
>     )
>     self.phi_f, self.psi1_f, self.psi2_f = scattering_filter_factory(
>         N, J, Q, T, generators, filters)
> ```
> 
> Note that the last function prepares for a number of features that could happen in v0.4 if we deem it useful:
> 
>     * varying Q per order ([ Make `Q2` customizable #854](https://github.com/kymatio/kymatio/pull/854) )
> 
>     * varying J per order
> 
>     * switching wavelet types
> 
>     * varying r_psi per order
> 
>     * varying wavelet type per order
> 
>     * having more than two orders
> 
>     * replacing the `scatnet_generator` by something else
> 
> 
> It also allows to skip filterbank construction in a very concise way:
> 
> ```python
> skip_filters = repeat(lambda *args, **kwargs: None, {})
> phi_f, psi1_f, psi2_f = scattering_filter_factory(N, Js, Qs, T, generators, skip_filters)
> ```
> 
> This idiom is useful for maintaining `utils.compute_meta_scattering` and `utils.precompute_size_scattering`. I also believe it will improve our approach to padding

🔥

**Comment by lostanlen** [comment]
>  perhaps wavelet function could follow some interface and be callable rather than passing around kwargs.

@cyrusvahidi i'm trying my best (so far with success) not to introduce new object-oriented classes. So a compromise i had in mind would be a two-element tuple with the callable as first element and its kwargs as second elements.

Something like `(gauss_1d, {"sigma0": sigma})` or `(morlet_1d, {"r_psi": r_psi})`.

For a Gammatone, it would become `(gammatone_1d, {"r_psi": r_psi, "gammatone_order": 4})` or something like that. I don't think it's necessary to have a new class where that class would basically implement `__init__`, `__call__`, and maybe (maybe!) some method `T_from_sigma` which computes the temporal support as a function of the `sigma` bandwidth parameter. But we have no such method right now, as we work empirically (`compute_temporal_support`) on the `phi`. Therefore i don't believe an OO interface is necessary ... yet.

So i see my solution as one step in the journey but not the final destination. In any case this will need to be discussed with @eickenberg, who i know has thought about this for a while now.

**Comment by lostanlen** [comment]
On it.
