### ISSUE TITLE
Unnecessary arguments in `core/scattering1d/scattering1d`

### ISSUE THREAD

**Issue by lostanlen** [kymatio/kymatio#852]
Not a big priority, but an easy simplification. The current prototype of `scattering` is: (phew!)

```python
scattering1d(x, pad, unpad, backend, log2_T, psi1, psi2, phi, pad_left=0,
        pad_right=0, ind_start=None, ind_end=None, oversampling=0,
        max_order=2, average=True, vectorize=False, out_type='array')
```

This didn't come to my attention while reviewing #673 , but the 5th input parameter, `log2_T`, is unnecessary: it is already available as `phi["j"]`. So we could just remove it, and put `log2_T = phi["j"]` at the top of the function.

Thoughts?

**Comment by MuawizChaudhary** [comment]
LGTM

**Comment by lostanlen** [comment]
upon closer inspection, i'm realizing that pad, unpad, ind_start, ind_end, pad_left, pad_right are also unnecessary ...

so yeah let's alleviate this prototype

**Comment by janden** [comment]
Sounds good.
