### ISSUE TITLE
`Q2` is not customizable

### ISSUE THREAD

**Issue by changhongw** [kymatio/kymatio#853]
Currently, users can only specify the number of wavelets per octave for the first order Q1=Q because we fix that for the second order as Q2=1. It would be useful to make Q2 customizable, i.e. setting Q as a tuple Q=(Q1, Q2), so that users can change Q2 according to their own project.

**Comment by lostanlen** [comment]
Yes. In `base_frontend`, catch the Q<1 case, and redefine `self.Q` as `(Q, 1)` if user-provided `Q` is int.
The rest should flow quite nicely, especially on top of #850

You'll have to unpack the tuple (`Q = Q1, Q2`) in `precompute_size_scattering` and `scattering_filter_factory`

**Comment by lostanlen** [comment]
closed by #854
