### ISSUE TITLE
Estimating the number of parameters of a keras model with a Scattering layer

### ISSUE THREAD

**Issue by evertoneie** [kymatio/kymatio#864]
I am trying to determine the total number of parameters of a keras model that contains a scattering layer (of order 1). I believe the estimated number of parameters can be calculated by totaling all the zero-order and first-order filters coefficients (psi_t and phi_t, in the time domain). I noticed that the scattering_filter_factory method only returns filters in the frequency domain. Can someone suggest some way to estimate the number of parameters of a keras model with Scattering layers?

Thank you all.

**Comment by lostanlen** [comment]
Hello @evertoneie,

I would say that there are several levels of abstraction in which we could interpret the notion of "number of parameters":

1) as the necessary and sufficient information to build the scattering object: that boils down to the arguments you pass to the constructor: J, Q, in 1D; J, L in 2D. This will be proportional to the number of (mandatory and non-default) hyperparameters in the transform.

2) as the frequencies "xis" and bandwidths "sigmas" of all filters. This will be proportional to the number of _filters_ in the transform.

3) as the number of nonzero coefficients in the transform. This is available with `out_size()`

4) as the number of convolutions performed, weighted by their resolution (temporal/spatial support). For us, the weighting is N_k log N_k, where N_k is the input resolution for path k. This will be proportional to the _throughput_ of the transform.

5) as the cumulated size of TensorFlow/PyTorch/NumPy arrays in memory when conducting the transform. This will be proportional to the memory usage of the transform.

Just to be clear, what you have in mind is definition (4), right?

**Comment by MuawizChaudhary** [comment]
Hi, by number of parameters do you mean the total number of **optimizable** parameters or the total number of non-optimizable parameters?

If it is the earlier, it should be 0. The later, simply take the product of the shape of each wavelet and sum over all of em. Please note, some wavelets maybe defined as having a zero imaginary part in the spatial domain, so you might want to divide the above calculation by two. To note if the real part is zero, simply take the IFFT of the filters. 

please let me know if this helps.

**Comment by evertoneie** [comment]
> Hello @evertoneie,
> 
> I would say that there are several levels of abstraction in which we could interpret the notion of "number of parameters":
> 
> 1. as the necessary and sufficient information to build the scattering object: that boils down to the arguments you pass to the constructor: J, Q, in 1D; J, L in 2D. This will be proportional to the number of (mandatory and non-default) hyperparameters in the transform.
> 2. as the frequencies "xis" and bandwidths "sigmas" of all filters. This will be proportional to the number of _filters_ in the transform.
> 3. as the number of nonzero coefficients in the transform. This is available with `out_size()`
> 4. as the number of convolutions performed, weighted by their resolution (temporal/spatial support). For us, the weighting is N_k log N_k, where N_k is the input resolution for path k. This will be proportional to the _throughput_ of the transform.
> 5. as the cumulated size of TensorFlow/PyTorch/NumPy arrays in memory when conducting the transform. This will be proportional to the memory usage of the transform.
> 
> Just to be clear, what you have in mind is definition (4), right?



Hi @lostanlen and @MuawizChaudhary , thank you very much for your quick answers. I'm looking for the total number of non-optimizable parameters. For example, if the first-order coefficients are given by S_1 = | x * \Psi_(\lambda_1) | * \Phi_J, I'm interested in the sum of the number of elements of each \Psi filter and each \Phi_J filter (not the "scattering output", S_1). Is there any direct way to get each wavelet that composes the transform in the time domain?

**Comment by MuawizChaudhary** [comment]
@evertoneie  I believe that you should be able to take the 1d IFFT of the filter to get the time domain representation. Please note that the imaginary part might be zero i.e. the filter might be real. 

Take each filter, take its ifft. take product of the shape, and add to total.Tho, the ifft should not change the shape i dont believe.

**Comment by lostanlen** [comment]
"the number of elements of each \Psi" filter depends upon the resolution of the input of that filter. You could measure everything at resolution zero, which would be tantamount to full oversampling. The number you'll end up with is the number of parameters of a vanilla (single-resolution) 2D convnet that would replicate the Scattering2D architecture. 

@evertoneie is that what you're looking for? If so, yes follow @MuawizChaudhary 's advice :)

**Comment by evertoneie** [comment]
@lostanlen, I'm using a Scattering1D, and I'd like to count all elements of each convolutional filter at all resolutions (something analogous to the total number of parameters that appear in a CNN's Summary()). 

I will analyze your answers carefully so that I can understand the suggestions properly.
@MuawizChaudhary, I'll take the 1d IFFT as you suggested.

**Comment by lostanlen** [comment]
@evertoneie for a first-order scattering, that number is equal to

```python
(1+len(scattering.psis)) * len(scattering.phi[0])
```

this is roughly proportional to `J * Q * N`
