### ISSUE TITLE
`torch.*fft` is deprecated

### ISSUE THREAD

**Issue by janden** [kymatio/kymatio#867]
Getting the warnings

```
tests/scattering1d/test_torch_backend_1d.py::test_fft[cuda-TorchSkcudaBackend1D]
  /home/jenkins/workspace/kymatio_dev/kymatio/scattering1d/backend/torch_backend.py:12: UserWarning: The function torch.fft is deprecated and will be removed in PyTorch 1.8. Use the new torch.fft module functions, instead, by importing torch.fft and calling torch.fft.fft or torch.fft.fftn. (Triggered internally at  /pytorch/aten/src/ATen/native/SpectralOps.cpp:567.)
    _fft = lambda x: torch.fft(x, 1, normalized=False)


tests/scattering1d/test_torch_backend_1d.py::test_fft[cuda-TorchSkcudaBackend1D]
  /home/jenkins/workspace/kymatio_dev/kymatio/scattering1d/backend/torch_backend.py:13: UserWarning: The function torch.ifft is deprecated and will be removed in a future PyTorch release. Use the new torch.fft module functions, instead, by importing torch.fft and calling torch.fft.ifft or torch.fft.ifftn. (Triggered internally at  /pytorch/aten/src/ATen/native/SpectralOps.cpp:578.)
    _ifft = lambda x: torch.ifft(x, 1, normalized=False)


tests/scattering1d/test_torch_backend_1d.py::test_fft[cuda-TorchSkcudaBackend1D]
  /home/jenkins/workspace/kymatio_dev/kymatio/scattering1d/backend/torch_backend.py:14: UserWarning: The function torch.irfft is deprecated and will be removed in a future PyTorch release. Use the new torch.fft module functions, instead, by importing torch.fft and calling torch.fft.ifft or torch.fft.irfft. (Triggered internally at  /pytorch/aten/src/ATen/native/SpectralOps.cpp:602.)
    _irfft = lambda x: torch.irfft(x, 1, normalized=False, onesided=False)[..., None]
```

Should probably fix this soonish.

**Comment by MuawizChaudhary** [comment]
Aren't we wanting to keep pre-Torch 1.7 compatibility?

**Comment by MuawizChaudhary** [comment]
But [thats](https://github.com/kymatio/kymatio/blob/dev/kymatio/scattering2d/backend/torch_backend.py#L9) already [what](https://github.com/kymatio/kymatio/blob/dev/kymatio/scattering1d/backend/torch_backend.py#L7) we [do](https://github.com/kymatio/kymatio/blob/dev/kymatio/scattering3d/backend/torch_backend.py#L10).

**Comment by janden** [comment]
Ok but then maybe we bring it down to 1.7 so that we get rid of the deprecation warnings?

**Comment by lostanlen** [comment]
on it

**Comment by lostanlen** [comment]
so ... it's not so trivial. In Torch 1.7, there is a `torch.fft` module but  ...

```
>>> torch.fft.fft2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'torch.fft' has no attribute 'fft2'
```

(they did not only move functions from `torch` to `torch.fft`, they also changed the semantics)

If we really insist on removing this `DeprecationWarning`, i think that our simplest response is just `catch` it by means of a  `warning.simplefilter`. Otherwise, i'd have to add at least three more conditional branches to Kymatio (for 1D/2D/3D) ....

**Comment by janden** [comment]
Hmm ok. So they deprecated in 1.7 but didn't provide an upgrade path until 1.8. Not cool…

At any rate, these warnings will go away from our CI once #892 merges so I'll close this.
