### ISSUE TITLE
Remove assertions in `core/scattering1d`

### ISSUE THREAD

**Issue by MuawizChaudhary** [kymatio/kymatio#869]
Currently there are a set of assertion statements in the core scattering1d algorithm. we should either remove these or move them somewhere more appropriate, like filterbank construction.

**Comment by lostanlen** [comment]
These assertions require `oversampling` to become immutable, which i absolutely support. It will make our lives so much easier in core

**Comment by MuawizChaudhary** [comment]
in support of

**Comment by lostanlen** [comment]
closed by 876
