### ISSUE TITLE
`scattering(self, x)` could (should?) be frontend-agnostic

### ISSUE THREAD

**Issue by lostanlen** [kymatio/kymatio#870]
Right now, our methods `scattering(self, x)` are frontend-specific, not frontend-agnostic: one is defined in each frontend. Of course, the code in these frontends look very similar: they do argument check, input check, input reshape, scattering, and output reshape.

We have a `self.backend` object, so there is no reason why we couldn't perform all these operations in `base_frontend.py`, with appropriate `shape`, `reshape_input`, and `reshape_output` routines being methods of `self.backend`.

This would help us maintain the code because there would be a single point of entry for the `if out_type="array"` clause and its friends. And i believe it is compliant with #735 philosophy, since it decouples shape pre/post-processing from core scattering.

I have written a short PR where i do this in 1D, to showcase the idea. I surmise that the same would be possible in 2D and 3D.

**Comment by janden** [comment]
I think this makes sense. I remember looking over the frontend code and noticing that there is a lot of duplication here that can be reduced…
