### ISSUE TITLE
Shorten duration of `test_gradients`

### ISSUE THREAD

**Issue by MuawizChaudhary** [kymatio/kymatio#872]
`test_gradients` takes a long time to finish running. I propose we look into making the test take a smaller amount of time to finish running, or switch over to using a modulus that doesn't implement a custom backwards.

**Comment by janden** [comment]
Would be nice. Maybe there are some settings there to tweak.

But yes, if we can use a stock modulus, that would be better… Maybe now that Torch has complex numbers that should be possible?

**Comment by MuawizChaudhary** [comment]
@janden are we wanting to keep supporting torch 1.7? One thing we could do in that case to make the sqrt operation differentiable is adding a small epsilon.

**Comment by janden** [comment]
> @janden are we wanting to keep supporting torch 1.7?

I'm not sure. That's a separate discussion.

> One thing we could do in that case to make the sqrt operation differentiable is adding a small epsilon.

That would break all the tests, so it'd be nice to avoid that…

**Comment by janden** [comment]
Another option here is to test our modulus separately (using `test_gradients`) and only verify that we can run `backward` on the output of scattering (i.e., not test the gradient of the full transform).

**Comment by MuawizChaudhary** [comment]
Given that we merged #873 I believe this discussion is no longer needed. We no longer use the long version of `test_gradients`.
