### ISSUE TITLE
`self.M`, `self.N`, `self.O` should be deprecated

### ISSUE THREAD

**Issue by lostanlen** [kymatio/kymatio#881]
for consistency with 1D #857
we should rename `self.M_padded` and `self.N_padded` to `self._M_padded` and `self._N_padded`

~~same for 3D, `self._O_padded` etc.~~

**Comment by lostanlen** [comment]
closed by 863 and 886

**Comment by MuawizChaudhary** [comment]
What about 3d?

**Comment by lostanlen** [comment]
@MuawizChaudhary there is no padding in 3d, so the semantics are different.

**Comment by MuawizChaudhary** [comment]
the title  `self.O` makes no sense then

**Comment by lostanlen** [comment]
@MuawizChaudhary the main goal of this was to allow non-power-of-two inputs in Scattering1D, in the prospect of JTFS. This goal is fulfilled now.

The longer-term goal is to allow `shape=None` (i.e., shape-agnostic scattering)  in every dimension. This renaming helps a bit with the longer-term goal but we will need to have a debate in terms of how we name things. 

* do we keep `self.N_padded`, `self.M_padded` 
* do we join them as a single constant named  `self._shape_padded` in every dimension
* if so, is there a shorter name for `self._shape_padded`
* how does this interact with #859 

these are all questions worth asking between v0.3 and v0.4
