### ISSUE TITLE
MAINT deprecate `self.average` 1D

### ISSUE THREAD

**Issue by cyrusvahidi** [kymatio/kymatio#885]
in preparation for the JTFS and 0.4 we could deprecate `average` in `Scattering1D`.

While reusing the 1D frontend for frequency scattering it came to our attention that we could utilize `T` to define the semantics of frequential averaging. This would evade introduction of an additional attribute `F`. Moreover, `T` could potentially cover the semantics of averaging, allowing for removal of `average`:

* `T=None` will perform default mode averaging, i.e. `T=2^J`
* `T=0` will correspond to `average=False`
* Any other integer `T` will stride over the specified support

**Comment by lostanlen** [comment]
> we could utilize T to define the semantics of frequential averaging. This would evade introduction of an additional attribute F

I think `F` would still be nice. The other option would be to make `T` a tuple, but that will collide with #854 

For JTFS we'd have

```python
def __init__(self, J, shape, Q, J_fr, Q_fr, T=None, F=None, oversampling=0, oversampling_fr=0, out_type='array', backend=None)
```

(order of arguments to be debated)

**Comment by lostanlen** [comment]
If we do this, `average` should temporarily default to `None`.

Then we'd have something like this in `__init__`

```python
if average is not None:
    warn('`average`  is deprecated v0.3 and will be removed in v0.4. Replace `average=False` by `T=0` and set `T>1` or leave `T=None` for `average=True` (default)', DeprecationWarning)
self.average = average
```

**Comment by cyrusvahidi** [comment]
> > we could utilize T to define the semantics of frequential averaging. This would evade introduction of an additional attribute F
> 
> I think `F` would still be nice. The other option would be to make `T` a tuple, but that will collide with #854
> 
> For JTFS we'd have
> 
> ```python
> def __init__(self, *, J, shape, Q, J_fr, Q_fr, T=None, F=None, oversampling=0, oversampling_fr=0, out_type='array', backend=None)
> ```

I think it's necessary to have an `F` parameter in the JTFS frontend, but this can be passed to the Scattering1D frontend for frequential averaging as `T`?

**Comment by lostanlen** [comment]
> I think it's necessary to have an `F` parameter in the JTFS frontend, but this can be passed to the Scattering1D frontend for frequential averaging as `T`?

`F` will be passed as `T` to the frequential `scattering_filter_factory`, yes.
But there won't be a `Scattering1D` object for frequential scattering, because @eickenberg doesn't want objects inside other objects.
Rather, the JTFS object will inherit and extend from time `Scattering1D`.

**Comment by janden** [comment]
We should also think about what this implies for 2D. Right now, we don't have an equivalent for `T` there but this may change.
