### ISSUE TITLE
what should be the returned shape of `Scattering1D` paths under `out_type='dict'` ?

### ISSUE THREAD

**Issue by lostanlen** [kymatio/kymatio#895]
Spotted while reviewing #871 with @janden

Right now, `out_type='dict'`behaves strangely. 

```python
J, Q = 2, 1
length = 1024
S = Scattering1D(J, shape, Q)
x = torch.zeros((5, 10,) + shape)

Sx = S(x)
print(Sx.shape)

S.out_type = "dict"
Sx = S(x)
print(list(map(lambda v: v.shape, Sx.values())))
```

Result: 
```
torch.Size([5, 10, 4, 256])

[torch.Size([5, 10, 1, 256]),
 torch.Size([5, 10, 1, 256]),
 torch.Size([5, 10, 1, 256]),
 torch.Size([5, 10, 1, 256])]
```

In other words, `out_type="dict"` is inserting a singleton dimension in penultimate position. This penultimate position serves to concatenate coefficients under `out_type="array"` (it becomes `4` in the example above).

I am in favor of removing this extra singleton dimension, and making values in `out_type="dict"` more like `'coef'`'s of `out_type="list"`. Compare with 

```python
S.out_type = "list"
Sx = S(x)
list(map(lambda v: v['coef'].shape, Sx))
```

Result:

```
[torch.Size([5, 10, 256]),
 torch.Size([5, 10, 256]),
 torch.Size([5, 10, 256]),
 torch.Size([5, 10, 256])]
```

This would be a breaking change, which is why i didn't make it single-handedly in my open PR #871.
I'm curious to hear everyone's thought here? bug or feature?

**Comment by janden** [comment]
Sounds like an oversight from when we introduced `out_type = "dict"` back in the day. I would be in favor of removing, but it's hard to do this in a way that's backwards-compatible yet not too ugly (basically it would involve creating a new `out_type = "new_dict"` or something like that). We have three alternatives:

(1) Do nothing.
(2) Break the old behavior by removing the singleton dimension.
(3) Add a new `out_type = "legacy_dict"` that has the extra dimension and redefine `out_type = "dict"` to do the right thing.

Honestly I don't think this is a central enough feature that (2) is a problem, but am open to discuss.

**Comment by lostanlen** [comment]
> Sounds like an oversight from when we introduced out_type = "dict" back in the day. 

Yes. In fact, we didn't introduce out_type='dict' explicitly but under the form of the `out_type='array'` + `vectorize=False` combination. So it's not entirely surprising we didn't think this keyword combination through.

> Honestly I don't think this is a central enough feature that (2) is a problem, but am open to discuss.

Me too, i can have it either way. I just wanted to pin down this issue so as to explain why my #871 PR has this weird statement:

```python
n_kept_dims = 1 + (self.out_type == "dict")
```

Making `n_kept_dims = 1` systematically would simplify the `reshape_output` logic a great deal. But i can also live without it.

**Comment by janden** [comment]
So I think we're in agreement here. Let's just go with (2) and make a not in the changelog.

**Comment by lostanlen** [comment]
ok good. phew, that's good news for me: keeping score of this effect was starting to get annoying.

i don't think anyone will notice. this case is non default (setting vectorize=False yet leaving out_type='array' and not changing it to 'list'). and the fix in user code is very simple anyway
