### ISSUE TITLE
`T='global'` (global average pooling)

### ISSUE THREAD

**Issue by lostanlen** [kymatio/kymatio#902]
Now that we have a `T` parameter (#673) and that `average` is deprecated (#884), i think it's time we consider passing `T='global'` to the constructor so that it skips the `phi` and performs a 1D uniform average, also known as "global average pooling", instead. This will be faster (`O(N)` instead of `O(N log N)`) and conceptually simpler than the default `T=None` (i.e., `2**J`).

The only drawback is that this implies adding a new Kymatio primitive, namely `sum`:

`def sum(x, axis)`
where `axis` is an `int` (for 1D) or `tuple` of `int`'s (for 2D/3D)

**Comment by cyrusvahidi** [comment]
> Now that we have a `T` parameter (#673) and that `average` is deprecated (#884), i think it's time we consider passing `T='global'` to the constructor so that it skips the `phi` and performs a 1D uniform average, also known as "global average pooling", instead. This will be faster (`O(N)` instead of `O(N log N)`) and conceptually simpler than the default `T=None` (i.e., `2**J`).
> 
> The only drawback is that this implies adding a new Kymatio primitive, namely `sum`:
> 
> `def sum(x, axis)` where `axis` is an `int` (for 1D) or `tuple` of `int`'s (for 2D/3D)

Maximally on board. Check `average='global`, skip `phi` and apply averaging with new backend primitive. What about the construction of `phi`? Do we still do it with `T=2**J`?

Main implementation additions constitute `sum` across backends? No lizard.

**Comment by lostanlen** [comment]
> Main implementation additions constitute sum across backends? No lizard.

Yes. Easy, but there's a bit of an API choice here: `axis` vs `dims`.
I'm inclined to think that it should be `axis` on all backends: https://github.com/kymatio/kymatio/issues/903
