### ISSUE TITLE
understanding of output and the max scale

### ISSUE THREAD

**Issue by skolari93** [kymatio/kymatio#904]
I would like to understand which element of the array is related to which scattering coefficient. I don't understand  the metadata ‘j’ (the scale of the filter used) and ‘n’ (the filter index). How do I know which wavelets are used to compute a specific value of the output tensor?

I also don't understand the 'J' (max scale). I don't find it in the wavelet scattering transform papers. What it the purpose of this parameter?

**Comment by cyrusvahidi** [comment]
hello @skolari93 and welcome to kymatio!

you rightly state that `j` refers to the scale of the wavelet filter. these `j`s determine the temporal support of a wavelet and their centre frequency `xi`.

For a dyadic wavelet filterbank (i.e. `Q=1`) we construct a filterbank with a geometric progression that starts from nyquist frequency `pi`. Each wavelet's centre frequency is defined as `xi = pi / 2^j` for `j = {0 .. J}`. Therefore `J` determines the lowest centre frequency of the filterbank and also the number of octaves. 

Higher scale --> lower centre frequency, greater temporal support, finer frequency resolution.

We delivered this [tutorial](https://github.com/cyrusvahidi/scat1d-tutorial) for 1D scattering at the Kymatio 2022 workshop. This delves into the filterbank parameters a bit more. The `.meta()` method provides all metadata associated with the values in the output tensor. You can use it to determine the scattering path's parameters.

**Comment by skolari93** [comment]
Thank you a lot for this detailed answer! This helped a lot!
