### ISSUE TITLE
pypi is still on version 0.2.1

### ISSUE THREAD

**Issue by cyrusvahidi** [kymatio/kymatio#907]
[pypi](https://pypi.org/project/kymatio/) is still on v0.2.1. we've now released v0.3 - how do we publish to pypi?

**Comment by eickenberg** [comment]
It's on pypi test -- I had been waiting for people to try to install it. I
believe Vincent did and found that the appdirs requirement wasn't working
I can push it to pypi as is if that is helpful

**Comment by lostanlen** [comment]
yes. i confirm, i'm running into an installation with appdirs

**Comment by janden** [comment]
No longer an issue.
