### ISSUE TITLE
Test coverage is below 90%

### ISSUE THREAD

**Issue by lostanlen** [kymatio/kymatio#929]
@edouardoyallon mentioned we're below 90% test coverage and is unhappy about that
https://app.codecov.io/gh/kymatio/kymatio/compare/926?src=pr&el=h1

turns out, almost half of it is due to the fact that we ship `datasets.py` in `kymatio/` where as it should really belong to `examples/`. I can volunteer for that

other, more serious problems are:
* general Keras frontend and backend is not covered (@janden )
* 1D Keras frontend is not covered (@janden )
* general JAX backend is uncovered (@MuawizChaudhary )

**Comment by edouardoyallon** [comment]
It's not a great coding practice to do this...

**Comment by janden** [comment]
To do what?
