### ISSUE TITLE
Images missing from README

### ISSUE THREAD

**Issue by janden** [kymatio/kymatio#950]
Both on GitHub and PyPI (https://test.pypi.org/project/kymatio/0.3.0a0/). Best solution may be to upload these to `https://kymat.io` and serve them from there.

**Comment by janden** [comment]
Still a problem. Would be good to solve before 0.4 release.

**Comment by edouardoyallon** [comment]
Still a couple of images missing, it would be really nice to fix this because it looks really bad.

**Comment by MuawizChaudhary** [comment]
@vivianwhite If you are interested, I think this is an issue you could solve. There are two images in the readme, and we want to serve them through kymat.io. we can store images in a folder called `_static`. you just need to figure out which images we want to server and how to serve them through `_static`.

**Comment by MuawizChaudhary** [comment]
Closed by #1030
