### ISSUE TITLE
scal2frq equivalent?

### ISSUE THREAD

**Issue by langestefan** [kymatio/kymatio#969]
Matlab has a convenient function called scal2frq which converts scales to pseudo-frequencies. I could not find anything like this implemented in kymatio. Although convenient, if it isn't implemented is there a way to program this myself? Thanks!

**Comment by lostanlen** [comment]
Hello, this is doable by accessing the "xi" metadata.  "xi" stands for center frequency in the wavelet in Kymatio. Remember to multiply xi by the sampling frequency so to convert the value to Hertz

**Comment by langestefan** [comment]
@lostanlen Thank you for your quick answer. From the metadata I read the following:

`xi = meta['xi'][order1]` : 

```
[[0.48376008        nan]
 [0.4733941         nan]
 [0.46325024        nan]
 [0.45332374        nan]
 [0.44360995        nan]
 [0.4341043         nan]
 [0.42480234        nan]
 [0.4156997         nan]
....
```

Is this  `[scale, f_center]` ? I tried the first column but it didn't match the frequency spectrum (multiplied by `fs`) of my synthetic signal thus I suspect it's the scale. 

Unfortunately `xi` is not described in the documentation.

**Comment by lostanlen** [comment]
You're looking at the metadata of the scattering paths. The first and second column are the xi's of first- and second-order wavelet respectively: `[f_center_1, f_center_2]`

Since you've filtered by `order1` it makes sense that the values of the second column are `nan` since there is no second-order wavelet for those paths.

**Comment by langestefan** [comment]
I see, that makes more sense. I looked at my plot again and found a small mistake, the pseudo-frequencies are correct. 

ps. If you want I can send in a pull request to update this clarification of `xi`.

Thank you.
