### ISSUE TITLE
JTFS `frequency_averaging` produces IndexError

### ISSUE THREAD

**Issue by cyrusvahidi** [kymatio/kymatio#976]
I have encountered an issue with frequency averaging in JTFS. I am attempting to average over one octave.

```
import torch
from kymatio.torch import TimeFrequencyScattering
jtfs_kwargs = {'shape': 2**15, 'T': 2**15, 'Q': (12, 1), 'J': 8, 'J_fr': 6, 'F': 12}
jtfs = TimeFrequencyScattering(**jtfs_kwargs, format="time")
jtfs(torch.randn(2**15))
```

Stack trace:
```
  File "/homes/cv300/venvs/dptm-wyn/lib/python3.8/site-packages/kymatio/scattering1d/core/timefrequency_scattering.py", line 445, in jtfs_average_and_format
    path = frequency_averaging(path, backend,
  File "/homes/cv300/venvs/dptm-wyn/lib/python3.8/site-packages/kymatio/scattering1d/core/timefrequency_scattering.py", line 378, in frequency_averaging
    S_c = backend.cdgmm(U_hat, phi_fr_f['levels'][k_in])
IndexError: list index out of range
```

Frequency averaging fails as the `phi_fr_f` is selected at a resolution that is out of bounds.

the input resolution is determined by `k_in = U_2['j_fr'][-1]`. somehow this `j_fr` is larger to the number of resolutions. In this case, `J_fr = 6`, `len(phi_fr_f['levels']) == 4` and the violating `j_fr = 4`

I do not know whether we have created an insufficient number of `phi_fr_f` resolutions. 

@lostanlen

**Comment by lostanlen** [comment]
after an offline conversation with @cyrusvahidi , we have traced down the problem to line 376

https://github.com/kymatio/kymatio/blob/a175292e5cc8d8194f5fea86ed36116b66f72c31/kymatio/scattering1d/core/timefrequency_scattering.py#L370-L384
